### ISSUE TITLE
Feature request : get Nationality of selected countries 

### ISSUE THREAD

**Issue by ajitjati** [hbb20/CountryCodePickerProject#100]
for India -> Indian, for Afganistan -> Afgan etc.

**Comment by hbb20** [comment]
Thank you for the feature suggestion.
This can be a good enhancement. We will keep this in our task bucket. But as this is not crucial for the primary purpose of the library, we can not assure the implementation of the same.

For now, you can introduce a function in your app that maps selected country to nationality on top of this library.

**Comment by ajitjati** [comment]
I am getting the nationality of the selected country from another list at runtime.I just felt someone else might need this this.This is basically , if the country list have another field for 'nationality' then it would be an easy effort.

**Comment by hbb20** [comment]
Yeah, I thought about it. As nationality is a commonly used attribute, it will enhance the utility of library. But to prepare such country->nationality mapping list and translate them to all the supported languages is time-consuming so we won't be able to implement it right away. Does that make sense? We will do it as we get a chance to do it. 👍 
Thanks...

**Comment by ajitjati** [comment]
This should help - https://github.com/Dinu/country-nationality-list
