### ISSUE TITLE
Feature to remember selected country even when the app is restarted

### ISSUE THREAD

**Issue by hbb20** [hbb20/CountryCodePickerProject#102]
As per current implementation, it set default country or detected country (based on configuration) whenever app restarts it. There must be an inbuilt option to remember the last selected country.

**Comment by milaptank** [comment]
I have remember last unique 5 Selected country using `SharedPreference` and `Set<String>`
So we can use like that

**Comment by hbb20** [comment]
Right now I'm working on remembering last selection so that whenever the screen is laid out it checks for last selection in SharedPref and set that in CCP. 

Do we need more than 1 countries? Can you please explain it's use?

**Comment by hbb20** [comment]
Version 2.1.0 introduces this feature. [Refer wiki](https://github.com/hbb20/CountryCodePickerProject/wiki/Remember-last-selection) for more details.

**Comment by milaptank** [comment]
This scenario is specific to my use case 
But as we are remember recent then remember 1 or x number just thought yes we need to generalised concepts
