### ISSUE TITLE
Formatted Number don´t work in Android 7

### ISSUE THREAD

**Issue by Alejan93** [hbb20/CountryCodePickerProject#103]
Hi, I am using a phone with android 7, and when I type the phone number it doesn't get formatted, but when a I use a phone with a lower android version it works

**Comment by hbb20** [comment]
Hey, that should not happen. Because it works well for my device running on Android 7 Nougat.
Can you please show your gradle file? and what's your testing device?

**Comment by osama-taha** [comment]
same issue I see.. Huawei Mate 9.0 - Android 7.0
I am using the latest library version 2.0.5

**Comment by Alejan93** [comment]
I'm using Huawei p10 lite with Android 7

**Comment by osama-taha** [comment]
Here is my configurations:

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center_vertical">

        <com.hbb20.CountryCodePicker
            android:id="@+id/country_code_picker"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:ccpDialog_showPhoneCode="true"
            app:ccp_autoDetectCountry="true"
            app:ccp_autoDetectLanguage="true"
            app:ccp_autoFormatNumber="true"
            app:ccp_countryPreference="us"
            app:ccp_showPhoneCode="true" />

        <EditText
            android:id="@+id/phone_number_edit_text"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:editable="false"
            android:hint="@string/place_holder"
            android:inputType="phone"
            android:maxLines="1" />

    </LinearLayout>


countryCodePicker.registerCarrierNumberEditText(phoneNumberEditText);

**Comment by hbb20** [comment]
Is CCP's older version (Specifically 2.0.3) is working for you people? Can you please check and report?

**Comment by osama-taha** [comment]
still happening even in v2.0.0

**Comment by Ma-Altaiir** [comment]
Hey all;
Formatting not working properly, the hint suggested by the component do not take into acount any leading zero, however if you try with a leading zero then formatting will work, this is a confusing behaviour since as we are presented with an international code we directly enter a phone number withount a leading zero, if formatting source code is working based on digits count then you can correct it.

**Comment by hbb20** [comment]
@Ma-Altaiir , please try version 2.2.0 and post back if the issue persists.
