### ISSUE TITLE
Programmatically close dialog

### ISSUE THREAD

**Issue by AliYusuf95** [hbb20/CountryCodePickerProject#104]
The library is so powerful and great, thanks for sharing it.

In my use case I want to dismiss the dialog after certain period of time, and it seems that there is no way to dismiss dialog programmatically

I suggest that is I use `launchCountrySelectionDialog()` it returns the created dialog. Also, it possible to add listener when dialog is opened from click event which contain the created dialog.

**Comment by hbb20** [comment]
Thank you @AliYusuf95  for the suggestion. 
There is a new `DialogEventsListener` which will give you call back when dialog is opened along with dialog object. It will give you call back every time when the dialog is opened (through the tap on ccp or programmatically).
