### ISSUE TITLE
Add "UAE" as a part of United Arab Emirates's name

### ISSUE THREAD

**Issue by shoaibahmad** [hbb20/CountryCodePickerProject#105]
Please add support UAE country Support also Can you please add this because i need that country in dialog

**Comment by shoaibahmad** [comment]
i am search UAE but not include in list

**Comment by hbb20** [comment]
Because it's name "United Arab Emirates" does not contains UAE.

I agree that searching it by "UAE" is a natural way so I will add that part
in the name. Then it will be searchable by "UAE".

For now search by any part of "United Arab Emirates" or by it's name code
"ae", you will get the result.

**Comment by hbb20** [comment]
Hey, `UAE` has been added to the English name of the `United Arab Emirates`. It is now, `United Arab Emirates (UAE)`. 
Update to version 2.0.7 to get changes reflected.
