### ISSUE TITLE
setDefaultCountryUsingNameCode() doesn't work

### ISSUE THREAD

**Issue by kurosaki-tisak** [hbb20/CountryCodePickerProject#108]
I also try to use in xml like this
`app:ccp_defaultNameCode="TH"`

but stills doesn't work when I run on the emulator
please advise me :P

**Comment by hbb20** [comment]
I assume that you don't want CCP to detect country based on user's locale right? In that case please add `app:ccp_autoDetectCountry=“false”` in your CCP view. [Wiki guide](https://github.com/hbb20/CountryCodePickerProject/wiki/XML-Properties#appccp_autodetectcountryfalse-default--true-) about auto detect country might be helpful to you.

**Comment by kurosaki-tisak** [comment]
It works like a charm!! 
Thank you man

**Comment by kurosaki-tisak** [comment]
Many thank for your reply man!

After I added ` app:ccp_autoDetectCountry="false"`,  I use `setDefaultCountryUsingNameCode()` along with `setCcpClickable()` programmatically, set clickable work perfectly but `setDefaultCountryUsingNameCode()` stills doesn't work

**Comment by hbb20** [comment]
setDefaultCountryUsingNameCode will just say ccp about your new default
country it won't load that country immediately. To set (show on screen)
that default country in CCP you need to use resetToDefaultCoutry().

**Comment by kurosaki-tisak** [comment]
It works like a charm man!
Thank you
