### ISSUE TITLE
hide arrow 

### ISSUE THREAD

**Issue by zaheerpoei** [hbb20/CountryCodePickerProject#109]
how  to hide arrow ??

**Comment by hbb20** [comment]
As per v2.0.5, there is no inbuilt way to do it.

**Comment by hbb20** [comment]
hey @zaheerpoei, v2.0.7 has the option you are looking for. 
After updating version, add `app:ccp_showArrow="false"` to your XML of CCP. It should work.

[Wiki](https://github.com/hbb20/CountryCodePickerProject/wiki/XML-Properties#appccp_showarrowfalse-default--true-) might be helpful.
