### ISSUE TITLE
Is this library auto detect country based on current loaction?

### ISSUE THREAD

**Issue by AbhishekPantUK** [hbb20/CountryCodePickerProject#111]
As I can see in setAutoDetectedCountry() method in CoutryCodePicker class first conditon it's taking from locale.
In my case I want first it should take from current location, if user dont allow then only from locale.
Is it possible?

**Comment by hbb20** [comment]
RIght now (2.0.5), uses 1. locale 2.SIM 3.Network (in order) to detect country. If method 1 fails then uses method 2. and if 2 fails then use 3. 

What exactly your expectation is? How the user will "dont allow"?

**Comment by apant9972** [comment]
Thanks for the info. 
Using user current location I wanted to set the country code. My requirement is 
1. Current location
2. Locale
3. Network

**Comment by milaptank** [comment]
For this What I have done 
Just Request `http://ip-api.com/json` and from its response will set country code 
This Works for me

**Comment by hbb20** [comment]
Yeah. This can be used on top of this library. But I think this should not be included in the library as it needs API call and slower response time might result in unexpected behavior. 
Right now I'm working on the option that gives flexibility for setting such preferences.

**Comment by hbb20** [comment]
hey, new version 2.1.0 has option to set order. @apant9972 this might be helpful to you. [Refer wiki](https://github.com/hbb20/CountryCodePickerProject/wiki/Auto-detect-country) for more details.
