### ISSUE TITLE
Number formatting doesn't work as expected

### ISSUE THREAD

**Issue by ogasimli** [hbb20/CountryCodePickerProject#112]
Hi folks,

First of all, thank you very much for this awesome library. It is the most usefull and customizable UI library that I have seen. 

I need your help on below issue. 

I have implemented CountryCodePicker as described in the guide. However, it seems like number formatting doesn't work as expected. To be precise, number formatting doesn't work for some countries. I am mainly interested in AZ and AE codes. I have tested it with two devices: 
1. OnePlus One - Android 7.1.2
2. Huawei Y6 Pro - Android 5.1

Also, I have tried to manually format numbers using PhoneNumberUtils.formatNumber method and it worked correctly.

Below is a snippet from my layout xml:

```xml                
                 <LinearLayout
                    android:id="@+id/signup_user_phone_linear_layout"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:orientation="horizontal"
                    android:layout_below="@id/signup_user_phone_txt"
                    android:gravity="center_vertical">

                    <com.hbb20.CountryCodePicker
                        android:id="@+id/signup_user_ccp"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_marginBottom="@dimen/custom_code_picker_margin_bottom"
                        android:layout_marginEnd="@dimen/custom_code_picker_margin_end"
                        app:ccp_showNameCode="false"
                        app:ccp_autoDetectCountry="true"
                        app:ccp_autoDetectLanguage="true"
                        app:ccp_contentColor="@color/colorPrimaryText"
                        app:ccp_textSize="@dimen/medium_txt_size"
                        app:ccpDialog_textColor="@color/colorPrimaryText"
                        app:ccpDialog_keyboardAutoPopup="false"
                        android:background="@drawable/edit_text_background"/>

                    <com.milebyte.app.ui.custom_view.CustomTextInputLayout
                        android:id="@+id/signup_user_phone_txt_input_layout"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginTop="@dimen/edit_profile_margin_top_edit_text_text_view"
                        app:hintEnabled="false"
                        app:errorEnabled="true">

                        <android.support.design.widget.TextInputEditText
                            android:id="@+id/signup_user_phone_edit_text"
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            android:hint="@string/edit_profile_phone_number_edit_text_hint"
                            android:inputType="phone|textNoSuggestions"
                            android:digits="1234567890 ()-+"
                            style="@style/RegistrationFormEditBoxStyle"/>

                    </com.milebyte.app.ui.custom_view.CustomTextInputLayout>

                </LinearLayout>
```

I am calling this in onCreateView method of my fragment:

```java       
mCodePicker.setTypeFace(ResourcesCompat.getFont(getActivity(), R.font.comfortaa_bold));
mCodePicker.registerCarrierNumberEditText(mPhoneEditText);
if (savedInstanceState == null) {
    String countryIso = getCountryFromSimInfo();
    if (countryIso != null && !countryIso.isEmpty()) {
        mCodePicker.setCountryForNameCode(getCountryFromSimInfo());
     }
}
```

Also, i see this exception in logcat after `mCodePicker.registerCarrierNumberEditText(mPhoneEditText)`:
`E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length`

**Comment by hbb20** [comment]
@ogasimli thank you for reporting. Can you please give an example of the number that you are typing in and what is expected formatting for that number?

**Comment by ogasimli** [comment]
Hi @hbb20,

In my app I am mainly interested in UAE and Azerbaijan numbers. For example, +994504248331, should be formatted as +994 50 424 83 31, or +971529936777 should be formatted as +971 52 993 6777. I even typed some German number, which didn't get formatted either.

Also, I noticed that PhoneNumberUtils.formatNumber method formats these numbers as expected. But this method formats them as you type, it works only if the number is typed fully.

**Comment by hbb20** [comment]
Yeah, I checked that and found the problem. 
If you use `ccp.ggetFormattedFullNumber();` then it will give correctly formatted number.

But it does not format some numbers while typing because of [PhoneNumberFormattingTextWatcher](https://developer.android.com/reference/android/telephony/PhoneNumberFormattingTextWatcher.html), provided by Android. CCP uses this class for formatting. If this textWatcher is not formatting any number then CCP cannot format it while typing.

Sorry about that but hopefully this will be fixed soon.
