### ISSUE TITLE
Country English Name

### ISSUE THREAD

**Issue by EULUSOY** [hbb20/CountryCodePickerProject#115]
Hi,

I am taking the selected country name with ccp.getSelectedCountryName.

How can we get only the English name?

---
Thanks for sharing this library.

**Comment by EULUSOY** [comment]
I added ConutryCodePicker class 

public String getSelectedCountryNameEnglish () {
         return getSelectedCountry (). englishName; }

    
Problem solved.

**Comment by EULUSOY** [comment]
I added CountryCodePicker class

public String getSelectedCountryNameEnglish () {
         return getSelectedCountry (). getEnglishName; }

    
Problem solved.

**Comment by hbb20** [comment]
Hey, @EULUSOY  thank you for the request. We have added the feature in version 2.0.6. 
After updating the version to >=2.0.6,  you will be able to use ```ccp.getSelectedCountryEnglishName();``` to get the English name of country.
