### ISSUE TITLE
textGravity is not working when showflag is false

### ISSUE THREAD

**Issue by yikhinzaw** [hbb20/CountryCodePickerProject#116]
Hi 
Please kindly take a look cpp_textGravaity properties.
I noticed that it not working when I set showflag is false.
As second issue, Myanmar Flag need to update. 
Thank you so much for your contribution.

**Comment by hbb20** [comment]
@yikhinzaw , thank you for pointing at incorrect Myanmar flag. Correct flag will be placed in next version.

Regarding ccp_textGravity. Can you please tell me which library version you are using? and what is your CCP XML?

**Comment by yikhinzaw** [comment]
Thanks for your quick reply. I used  'com.hbb20:ccp:2.0.5'. my layout is  as follows:
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.example.activity.ChooseCountryActivity">

        <TextView
            android:id="@+id/lblchoosecountry"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:textSize="@dimen/text_medium_bold"
            android:textStyle="bold"
            android:layout_centerInParent="true"
            android:textColor="@color/cardview_dark_background"
            android:text="@string/str_choosecountry"/>

    <com.hbb20.CountryCodePicker
        android:id="@+id/ccp"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/lblchoosecountry"
        app:ccp_autoDetectCountry="false"
        app:ccp_autoDetectLanguage="true"
        app:ccp_clickable="true"
        app:ccp_defaultLanguage="ENGLISH"
        app:ccp_defaultNameCode="mm"
        app:ccp_showFlag="false"
        app:ccp_showFullName="true"
        app:ccp_showNameCode="false"
        app:ccp_showPhoneCode="false"
        app:ccp_textGravity="LEFT"
        app:ccp_textSize="20sp"
        tools:layout_editor_absoluteX="117dp"
        tools:layout_editor_absoluteY="8dp" />
    <Button
        android:id="@+id/btn_gettingstart"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/ccp"
        android:background="@color/colorPrimary"
        android:textColor="@android:color/white"
        android:text="@string/str_gettingstart"/>
</RelativeLayout>

**Comment by hbb20** [comment]
Yeah. It was a problem with 2.0.5. If you switch to the version 2.0.7, then you will get the expected result. 

I applied your code with `app:ccp_textGravity="LEFT"`in my sample app and used different versions:

<img width="250" alt="issue_solve" src="https://user-images.githubusercontent.com/4918760/32147446-62e1dbfc-bcb5-11e7-8079-856b3ffb729d.png">

For v2.0.7, it's working as expected.

**Comment by yikhinzaw** [comment]
Thank you so much. I really appreciate your attention and quick fix.

**Comment by hbb20** [comment]
Hey @yikhinzaw, v2.0.8 has corrected flag of Myanmar.
