### ISSUE TITLE
Manifest merge fail

### ISSUE THREAD

**Issue by rutvikbhatt9** [hbb20/CountryCodePickerProject#118]
Error:Execution failed for task ':app:processDevDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.1) from [com.android.support:support-v13:26.0.1] AndroidManifest.xml:28:13-35
  	is also present at [com.android.support:cardview-v7:26.1.0] AndroidManifest.xml:25:13-35 value=(26.1.0).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:9-28:38 to override.

**Comment by hbb20** [comment]
Can you please post your gradle file? That will help us understanding the version issue.

**Comment by rutvikbhatt9** [comment]
Thank you I have solved problem by adding this to my gradle file:

compile ('com.hbb20:ccp:2.0.7',{
        exclude group: 'com.android.support'
    })
