### ISSUE TITLE
Unable to change default country either through code or xml

### ISSUE THREAD

**Issue by prashrox** [hbb20/CountryCodePickerProject#119]
I am getting US(+1) by default in the ccp spinner, even after trying,
app:ccp_defaultNameCode="IN"  or  app:ccp_autoDetectCountry="true"  in XML.
OR
mCountryCodePicker.setDefaultCountryUsingNameCode("IN");
 or  mCountryCodePicker.setAutoDetectedCountry();   programmatically.

**Comment by hbb20** [comment]
Hey. By default autoDetectCountry is true that will take priority over default country. If you want to load default country as soon as view is prepared then add `app:ccp_autoDetectCountry="false"`. It should work.

**Comment by prashrox** [comment]
Hey thanks, it did work.
But 'app:ccp_autoDetectCountry' should have detected India as opposed to US. Which I am forcing through the above mentioned solution.

Anyways, the ccp library is awesome ! Kudos !

**Comment by hbb20** [comment]
yeah, we are noticing this problem of detecting incorrect country since we started using locale to use detect country. We are working on it to solve.

Thanks.
