### ISSUE TITLE
Custom font/typeface in the dialog

### ISSUE THREAD

**Issue by liauli** [hbb20/CountryCodePickerProject#120]
I am using custom font for my app. I can successfully changed the selected country code's font but I couldn't find how to change the font in the dialog picker.

Is there any way to do this?
Thank you!

**Comment by hbb20** [comment]
Well, there is no such way right now but it's a valid requirement. I'm adding this to my to-do list.

**Comment by hbb20** [comment]
Hey @liauli , can you please update the version of ccp to 2.0.8. It should give you the expected result.

Is it working?

For more details check [wiki page.](https://github.com/hbb20/CountryCodePickerProject/wiki/Custom-TypeFace-(FontFamily))

**Comment by liauli** [comment]
Hey, thank you for your quick response. I'm sorry  for now I still use the version 2.0.1 because my project still use SDK 25 at the moment, I got conflict when I use newer CCP version

**Comment by hbb20** [comment]
<img width="1642" alt="screen shot 2017-11-16 at 20 28 22" src="https://user-images.githubusercontent.com/4918760/32926573-999997c8-cb0d-11e7-97da-3237833c367e.png">
If you are receiving the same error it's beause latest version uses updated 26.1.0 support libraries. And it requires to add 

```
maven {
     url "https://maven.google.com"
 }
```

to project's build.gradle's repository list. so now it looks..

```
allprojects {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
}
```

This should work.

FYI: 2.0.8 uses libraries with 25's version. So meanwhile you can work on your project using 2.0.8 if this does not work and you don't want this issue to delay your project development.

**Comment by hbb20** [comment]
This also might fail, try doing this in your gradle file
```
compile ('com.hbb20:ccp:2.0.9',{
exclude group: 'com.android.support'
})
```
This will avoid inclusion of support libraries for CCP which are of 26 level and causing the error.

And make sure to include support library for recyclerview, appcompat of level 25. So part of your gradle file dependencies should look like this.
```
   compile ('com.hbb20:ccp:2.0.9',{
        exclude group: 'com.android.support'
    })
    compile 'com.android.support:recyclerview-v7:25.3.1'
    compile 'com.android.support:appcompat-v7:25.3.1'
```

 Did that work?

**Comment by liauli** [comment]
Hi Hbb20, I still have problems before with 2.0.8, haven't tried 2.0.9 but I finally upgraded my support libraries to 26 and now all is working fine. Thank you !
