### ISSUE TITLE
Disable the selection of country code picker

### ISSUE THREAD

**Issue by vjsystematix** [hbb20/CountryCodePickerProject#123]
Hello, how can I disable the country picker? I used the enable method and set it false but its not work.
Please suggest

**Comment by hbb20** [comment]
Hi @vjsystematix, you can use `app:ccp_clickable=“false"`. More details on [wiki](https://github.com/hbb20/CountryCodePickerProject/wiki/XML-Properties#appccp_clickablefalse-default--true-).
If that does not work, give comment on this issue.
