### ISSUE TITLE
app:ccp_showArrow not found.

### ISSUE THREAD

**Issue by gvklive** [hbb20/CountryCodePickerProject#124]
I tried disabling showArrow, But seems like gradle throws an error with not finding it.

**Comment by hbb20** [comment]
What is the library version you are using?

**Comment by gvklive** [comment]
v1.1.2

**Comment by hbb20** [comment]
Ccp_showArrow was introduced in version 2.0.7.  so it won't work any version before that. 

If you switch to the latest version 2.0.8, then it should work for you. But remember to read [update guide](https://github.com/hbb20/CountryCodePickerProject/wiki/Update-Guide-for-v2.0.0) for version 2.0.0. There are few changes that you'll need to do.

**Comment by gvklive** [comment]
Thanks, But, why gradle didn't say that there's an updated version?

**Comment by hbb20** [comment]
I'm not sure about that. But is it working for you after updating version?

**Comment by gvklive** [comment]
Yeah, Thanks for that.
