### ISSUE TITLE
Error:(66, 26) No resource found that matches the given name (at 'src' with value '@drawable/ic_backspace_black_24dp').

### ISSUE THREAD

**Issue by fangxiaole** [hbb20/CountryCodePickerProject#125]
Error:(66, 26) No resource found that matches the given name (at 'src' with value '@drawable/ic_backspace_black_24dp').

**Comment by fangxiaole** [comment]
Remove the wrong place, you can run

**Comment by hbb20** [comment]
For which version it's giving you error?

**Comment by hbb20** [comment]
hey @fangxiaole, I'm working on this issue. It will be helpful if you explain what exactly you meant by "Remove the wrong place, you can run"?

**Comment by hbb20** [comment]
Hellow @fangxiaole, is this resolved?

**Comment by fangxiaole** [comment]
Sorry, I forgot to reply you.The problem has been solved
My English is very poor
