### ISSUE TITLE
CountryCodePicker not resizing properly inside a DialogFragment

### ISSUE THREAD

**Issue by simonlinj** [hbb20/CountryCodePickerProject#126]
As you can see in the screenshot, the CountryCodePicker is very small. 

this is my XML file
```
    <com.hbb20.CountryCodePicker
    android:id="@+id/ccp"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:ccpDialog_keyboardAutoPopup="false"
    app:ccp_autoDetectCountry="true"
    app:ccp_countryPreference="CU,US,CA,BR,ES,IT"
    app:ccp_defaultLanguage="SPANISH"
    app:ccp_showFullName="true"
    app:ccp_showNameCode="false"
    app:ccp_showPhoneCode="true"
    app:ccp_textGravity="LEFT" />
```

tried with fixes width, without success either....  any suggestion? 

![countrycodepicker](https://user-images.githubusercontent.com/1506890/32587250-1cf88fe4-c4e6-11e7-92f5-e91bbbc8193b.png)

**Comment by hbb20** [comment]
Can you send your entire layout xml of dialog fragment?

**Comment by simonlinj** [comment]
Hi  @hbb20 
Thanks for your response.. I was able to reproduce it with your sample project. 

I created this fork with some minors changes so I can build it.
https://github.com/simonlinj/CountryCodePickerProject/tree/downsizing_bug 

As you can see, only when the textSize is the default one isn't working. 
![countrycodepickerproject](https://user-images.githubusercontent.com/1506890/32607354-77e32594-c537-11e7-9e89-d2f44db15280.jpeg)

**Comment by simonlinj** [comment]
it's showing correctly If I explicitly assign the textSize `app:ccp_textSize="18dp"`



seems that the default size calculator is broken

```java
    int textSize = a.getDimensionPixelSize(R.styleable.CountryCodePicker_ccp_textSize, 0);
    if (textSize > 0) {
        textView_selectedCountry.setTextSize(TypedValue.COMPLEX_UNIT_PX, textSize);
        setFlagSize(textSize);
        setArrowSize(textSize);
    } else { //no textsize specified
        DisplayMetrics dm = context.getResources().getDisplayMetrics();
        int defaultSize = Math.round(18 * (dm.xdpi / DisplayMetrics.DENSITY_DEFAULT));
        setTextSize(defaultSize);
    }
```

**Comment by hbb20** [comment]
Thank you for that. Looks like it's working on some devices and not on some others. Because it works on all my devices correctly. I will remove that default assignment. Hopefully, that will work well.

**Comment by hbb20** [comment]
Can you confirm if it is working for you with version 2.0.9?

**Comment by simonlinj** [comment]
@hbb20  yup, it's fixed. thank you very much.
