### ISSUE TITLE
libphonenumber is not optimized for Android

### ISSUE THREAD

**Issue by simonlinj** [hbb20/CountryCodePickerProject#127]
As stated in (https://github.com/googlei18n/libphonenumber#third-party-ports) PhoneNumberUtil is not optimized for Android.

The ported and optimized version for Android is this one: https://github.com/MichaelRocks/libphonenumber-android

Any chance this switch of library could be implemented in the future?  Thanks!

**Comment by hbb20** [comment]
Thank you for this suggestion.
Sure we will look in into this optimised version and if it’s suitable for
all of our requirements then we’ll happily go for it in the future. But we
can not promise exact time for switch. If someone is doing it then PR is
always welcomed.

**Comment by hbb20** [comment]
Hey @simonlinj , v2.1.0 uses suggested android port. Thanks again for the suggestion.

**Comment by simonlinj** [comment]
awsome! thank you :)
