### ISSUE TITLE
Manifest Merger Failed

### ISSUE THREAD

**Issue by Isabellle** [hbb20/CountryCodePickerProject#128]
Did anyone already report this error after adding the lib? Thank you very much for any assistance

`Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.1) from [com.android.support:customtabs:25.3.1] AndroidManifest.xml:24:9-31
  	is also present at [com.android.support:cardview-v7:26.1.0] AndroidManifest.xml:25:13-35 value=(26.1.0).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:9-28:38 to override.`

**Comment by hbb20** [comment]
From version 2.0.9, ccp is using 26.0.1 of support libraries. So hopefully updating library version to 2.0.9 should work. 

Or there is a [similar issue](https://github.com/hbb20/CountryCodePickerProject/issues/118) with a workaround for it.

Just let us know if it works or not..

thanks

**Comment by beast-shubham** [comment]
So the solution for similar issue worked but updating the support lib to 26.0.1 didn't work. Just an FYI
