### ISSUE TITLE
Set Country Code Programmatically

### ISSUE THREAD

**Issue by Kerosky** [hbb20/CountryCodePickerProject#13]
Hi, Harsh Bhakt,

Great code you have made here, it saves my time a lot, I have a question on this,

how do you set country code programmatically? I found in your code only written setCountryForNameCode(), what should I add in front of it?

Thanks,
Tommy Kerosky

**Comment by hbb20** [comment]
Hello @Kerosky ,

To set country using phone code, use ccp.setCountryForPhoneCode() method. [View in code](https://github.com/hbb20/CountryCodePickerProject/blob/master/ccp/src/main/java/com/hbb20/CountryCodePicker.java#L740).

But setting country using phone code is somewhat risky as more than one country can have the same country code. In that case by setting country using phone code might load another country with the same country code. If you are going to set country using phone code, look at [country preference ](https://github.com/hbb20/CountryCodePickerProject#3-country-preference)which might be helpful to you.

**Comment by Kerosky** [comment]
Sorry for reopening closed issue, I tried 

TextView ccp = (TextView)findViewById(R.id.ccp);
        ccp.setCountryForNameCode();

But it said cannot resolve method setCountryForNameCode()

Where I have done wrong?

**Comment by hbb20** [comment]
Just pass country code as parameter of the method.
try ccp.setCountryForNameCode(7); //or any other country code

**Comment by Kerosky** [comment]
it said "cannot resolve symbol ccp"

**Comment by hbb20** [comment]
hey, 
you are trying to cast CCP in TextView. 
Do the following
```
CountryCodePicker  ccp = (CountryCodePicker)findViewById(R.id.ccp);
ccp.setCountryForNameCode("RU");
```

**Comment by Kerosky** [comment]
Ohhh, now I understand. I think if possible add this code in your guide, so you will not face another people like me,

Thank you,
Tommy Kerosky

**Comment by hbb20** [comment]
Sure :+1:
