### ISSUE TITLE
Wrong Flag

### ISSUE THREAD

**Issue by apant9972** [hbb20/CountryCodePickerProject#130]
If user is connected to wi-fi, it's showing US flag and country code of India. 
Even If I am trying to set default country as India, it's not showing India's flag.

**Comment by hbb20** [comment]
oops... It's because of auto detect country. Try by adding app:ccp_autoDetectCountry="false" and setting default country india.

**Comment by hbb20** [comment]
But anyways it should not show the wrong flag even if fails to detect the country.

**Comment by apant9972** [comment]
it's working fine now. THANKS hbb20!!

**Comment by hbb20** [comment]
Cool. If you find any cause or face issue about a mismatch of flag and country, please notify in issue and post the steps to reproduce.
