### ISSUE TITLE
Can't change accent colour, so blinking cursor on Search EditText is green

### ISSUE THREAD

**Issue by NickButcher1** [hbb20/CountryCodePickerProject#131]
I think /ccp/src/main/res/values/attrs.xml is missing a ccpDialog_accentColor attribute to allow me to change the colour of the blinking cursor on the "Search..." text entry box.

**Comment by hbb20** [comment]
Hey, thank you for reporting. 
v2.1.1 will set "ccpDialog_searchEditTextTint" as cursor color.

**Comment by muhammad-hamza-shahid** [comment]
@hbb20 This feature is still missing as I am unable to get this property "ccpDialog_searchEditTextTint"
