### ISSUE TITLE
few country is not available 

### ISSUE THREAD

**Issue by KuljeetSingh96** [hbb20/CountryCodePickerProject#133]
for example Ice Land is not available

 https://en.wikipedia.org/wiki/Iceland

Please create interface so that developer  can add country to lib DB

**Comment by hbb20** [comment]
I appreciate your PR which adds the IceLand. That is more convenient way rather than interface as CCP supports multiple languages and flag conventions. Adding country through PR helps the entire Android developer community.

Thanks.
