### ISSUE TITLE
please Open to use Country

### ISSUE THREAD

**Issue by user32338** [hbb20/CountryCodePickerProject#136]
Hi! 
I need use in my custom Fragment (Search Toolbar + RecyclerView) your Country Database) 
so please open our class Country or CountryAdapter)

**Comment by Flo354** [comment]
Hi,

I am facing the same situation. I would like to store in my database the country code extracted from the chosen country (I can do that), and after, when I retrieve the country code, display the country name (without using the <CountryCodePicker>. It would be awesome if this class was usable outside the package.

As a temporary workaround for my case, I created a class **com.hbb20.MyCountry** (which is in the same package so accessible and containing the following code:

```java
package com.hbb20;

import android.content.Context;
import java.util.Locale;

public class MyCountry {

    private Country country;

    private MyCountry(Country country) {
        this.country = country;
    }

    public String getName() {
        return country.getName();
    }

    public static MyCountry fromCodeName(Context context, String codeName) {
        Locale currentLocale = context.getResources().getConfiguration().locale;

        CountryCodePicker.Language chosenLanguage = null;
        for (CountryCodePicker.Language language : CountryCodePicker.Language.values()) {
            if (language.getCode().equalsIgnoreCase(currentLocale.getLanguage())) {
                chosenLanguage = language;
            }
        }

        if (chosenLanguage == null) {
            chosenLanguage = CountryCodePicker.Language.ENGLISH;
        }

        return new MyCountry(Country.getCountryForNameCodeFromLibraryMasterList(context, chosenLanguage, codeName));
    }
}
```

**Comment by user32338** [comment]
so, this is not good))
if the structure changes, you will have to change this class((
I think better do fork..

**Comment by Flo354** [comment]
Yes, you are right. But as I said, it is only a temporary workaround. By doing this I don't need to fork, sync the changes and publish my own library to maven, which is time consuming compared to the 10 minutes I took to make this class.

It works for now and with some luck the author will open the class so I can get rid of this class in the near future :)

**Comment by hbb20** [comment]
Sorry for the trouble it is causing to you people. As this was not my own use case so I never realized need to make country class open. I will open this class and release the new version (along with other pending features) soon. If you can wait for a week then it will good enough for me.

**Comment by Flo354** [comment]
Thanks @hbb20 !

Actually, your library is much more powerful than just letting us pick some country or write number formatted as we type. You solve such a headache with your library :p

**Comment by hbb20** [comment]
Please try v2.1.1. Please note that name of the class is changed to CCPCountry from Country to avoid any possible confusion. Please let me know if you want something else. Thanks

**Comment by Flo354** [comment]
Thanks @hbb20, works well!
