### ISSUE TITLE
Fatal Exception: java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by viveksinha121** [hbb20/CountryCodePickerProject#14]
ava.util.ArrayList.throwIndexOutOfBoundsException (ArrayList.java:251)
java.util.ArrayList.get (ArrayList.java:304)
com.hbb20.CountryCodeAdapter$2.onClick (Unknown Source)
android.view.View.performClick (View.java:4084)
android.view.ViewDebug$3.run (ViewDebug.java:914)
android.os.Handler.handleCallback (Handler.java:630)
android.os.Handler.dispatchMessage (Handler.java:92)
android.os.Looper.loop (Looper.java:137)
android.app.ActivityThread.main (ActivityThread.java:4791)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:511)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:786)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:553)
dalvik.system.NativeStart.main (NativeStart.java)

**Comment by hbb20** [comment]
Thank you for reporting. Please explain in which case it crashed? Is it consistent? XML file and programmatic operations on CCP will help in fixing.

**Comment by viveksinha121** [comment]
Hi,
I found later that this mobile is a test environment in which crash is
reported. This doesn't support all the services like actual mobile.
CPP is working fine in all actual mobile devices which I tested.

Thanks.

**Comment by hbb20** [comment]
:+1: Ohk..
