### ISSUE TITLE
Can we have `textView_selectedCountry` Public

### ISSUE THREAD

**Issue by bliveinhack** [hbb20/CountryCodePickerProject#144]
- if we have `textView_selectedCountry` Public then we have more customization option.

**Comment by hbb20** [comment]
Yes sure. I will make their getter-setter public. Thank you for pointing that.

**Comment by hbb20** [comment]
Switch to v2.1.2, you will be able to access country TextView, Flag ImageView, and Arrow ImageView through their getter-setters.
