### ISSUE TITLE
Trying to select pk as default country but unable to.It still shows US

### ISSUE THREAD

**Issue by Ume1931** [hbb20/CountryCodePickerProject#146]
<com.hbb20.CountryCodePicker
        android:id="@+id/count"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:gravity="center"
        app:ccp_defaultNameCode="pk"
        app:ccp_showFullName="true"
        app:ccp_showPhoneCode="false"
        app:ccp_showNameCode="false"
        app:ccp_countryPreference="PK"
        android:textColor="@color/appTextColor"/>

**Comment by hbb20** [comment]
@Ume1931 , thank you for reporting.

The most probable reason is the use of library version lower than `2.1.0` . For those older versions, default value of [app:ccp_autoDetectCountry](https://github.com/hbb20/CountryCodePickerProject/wiki/XML-Properties#appccp_autodetectcountrytrue-default--false-) is `true`.  But that was confusing for many developers (just like you), so we changed the default value to `false` after version `2.1.0`.

Currently, your ccp is detecting the country automatically.
To fix this do one of the following:
**Option A. Use the latest library version (Recommended)** 
- In your gradle file, update the library version to the latest one. (that is `2.1.2` as per Jan 10, 2018)

**Option B. Turn off auto detection**
-  Add `app:ccp_autoDetectCountry=“false"` to your code. 


Comment back if that does not work, I will reopen the issue.
