### ISSUE TITLE
Exclude or include specific countries

### ISSUE THREAD

**Issue by junaidyasin** [hbb20/CountryCodePickerProject#147]
Hello,

Your library is great! However, I cannot find a way to include or exclude specific countries in the picker. For example if I only need to include 10 countries in the picker list, or exclude 10 countries from the total list. Is there something I am missing?

**Comment by hbb20** [comment]
Thank you so much for posting the query.

Definitely, you can restrict the country list in CCP. To do so, you will need to define the custom master list. Once the custom master list is defined, it will include only those countries in the list for selection. Check [wiki page](https://github.com/hbb20/CountryCodePickerProject/wiki/Custom-Master-Country-List) for more details.
