### ISSUE TITLE
Picker listener

### ISSUE THREAD

**Issue by beersheba** [hbb20/CountryCodePickerProject#15]
I need to listen for country code picker changes. How to do it?

**Comment by hbb20** [comment]
There is a pending pull request for this which is not merged yet. I will do it tomorrow and will publish new version of the library so that you can set change listener.

**Comment by hbb20** [comment]
hi @beersheba, selection change listener has been added to the library. Please update library version to 1.6. Read [documentation](https://github.com/hbb20/CountryCodePickerProject#2-choose-and-set-country) for details.
