### ISSUE TITLE
How to hide country codes in the dialog of country to search

### ISSUE THREAD

**Issue by gyallapu** [hbb20/CountryCodePickerProject#159]
Something like     app:ccpDialog_showNameCode = "false"

**Comment by hbb20** [comment]
Sure. Good suggestion. I just implemented this feature. Will be available from next version. But it will take some time before next release goes live as I have some other fixes to do as well. I will update on this thread as soon as new version is released.

**Comment by gyallapu** [comment]
Great. 
By the way i have one more suggestion . It's great if this have alpha 3 country codes. Thank's for your quick response

**Comment by hbb20** [comment]
The requested feature is live in version 2.1.5. You should get the expect result by adding `app:ccpDialog_showNameCode="false"`. 

We don't see any need of using alpha 3 country codes. If you see some advantage, please open new issue with details.

Again, thank you for the reporting.
