### ISSUE TITLE
Make changeDefaultLanguage to use locale

### ISSUE THREAD

**Issue by Studentessa** [hbb20/CountryCodePickerProject#160]
It's support multilanguage but to set the default language it is necessary to use the specific class  `CountryCodePicker.Language` and it should use the  `Locale` from Android.

**Comment by hbb20** [comment]
Thank you for asking.
The reason why Locale is not directly used is sometimes you might don't want to use that device locale. 

If you want to get the advantage of Locale language attribute, you can specify `app:ccp_autoDetectLanguage=“true"` ([read more](https://github.com/hbb20/CountryCodePickerProject/wiki/XML-Properties#appccp_autodetectlanguagetrue-default--false-)). It will detect the language based on Locale.
