### ISSUE TITLE
Can you update compile->implementation in build.gradle.

### ISSUE THREAD

**Issue by NickButcher1** [hbb20/CountryCodePickerProject#161]
Can you update compile->implementation in https://github.com/hbb20/CountryCodePickerProject/blob/master/app/build.gradle

I _think_ this is causing the following warning on my app builds.  I am reasonably certain I have ruled out all other dependencies and that the warning is not coming from my own app code.

`WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation'.
It will be removed at the end of 2018`

Thanks for your help.

**Comment by NickButcher1** [comment]
testCompile->testImplementation too?

**Comment by hbb20** [comment]
Sure, thank you for the suggestion. I will do that. Changes will be reflected in the next version.

**Comment by ntsparis** [comment]
@NickButcher1 i add testImplementation too, my mistake. I create pull request in https://github.com/hbb20/CountryCodePickerProject/pull/162

**Comment by hbb20** [comment]
Version 2.1.5 is live with suggested changes. Please switch to the latest version.

**Comment by wallpaperapp2018** [comment]
i have a same problem like this...
Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation' and 'testApi'.
Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'.

**Comment by wallpaperapp2018** [comment]
i am new for this ...
can you describe in detail...
please

**Comment by wallpaperapp2018** [comment]
yes i update compile->implementation in build.gradle

On Sat, Apr 28, 2018 at 11:55 PM, wallpapers app <wallpaperapp2018@gmail.com
> wrote:

> i am new for this ...
> can you describe in detail...
> please
>
> On Sat, Apr 28, 2018 at 11:51 PM, Harsh B. Bhakta <

**Comment by wallpaperapp2018** [comment]
i am new for this ...
can you describe in detail...
please

yes yes i update compile->implementation in build.gradle

**Comment by wallpaperapp2018** [comment]
check this

https://github.com/wallpaperapp2018/m3m/issues/1
