### ISSUE TITLE
Formatting of Ukrainian phone numbers

### ISSUE THREAD

**Issue by ViTVetal** [hbb20/CountryCodePickerProject#163]
For both cases (starts with 0 and without 0 at first position) `.getFullNumberWithPlus()` return correct number (+380311234567 and +380391234567). `.isValidFullNumber()` also works correct in both cases.

Why formatting works only when phone number starts with 0 but `app:ccp_hintExampleNumber="true"` show format without 0?

![mu3a0zfegiu](https://user-images.githubusercontent.com/4107233/36949181-86a8ccbc-1fed-11e8-85a8-eb1b1ee60e70.jpg)
![sd64x_4idze](https://user-images.githubusercontent.com/4107233/36949193-ae85b056-1fed-11e8-88da-de91f06a0557.jpg)
![ya9wnulihly](https://user-images.githubusercontent.com/4107233/36949221-02257502-1fee-11e8-8020-c778275153a2.jpg)
![ic-ygtkhi7e](https://user-images.githubusercontent.com/4107233/36949251-620782d0-1fee-11e8-8bf4-be2ea0c828ce.jpg)
![3xppz89jl4e](https://user-images.githubusercontent.com/4107233/36949254-6a333242-1fee-11e8-8bf0-1f0bbf3aa5e8.jpg)
![taln46zn3yc](https://user-images.githubusercontent.com/4107233/36949257-741d4b58-1fee-11e8-97c5-d4bfd4c4d54c.jpg)

**Comment by hbb20** [comment]
Sorry for the inconvenience. 

This is a known issue and we are looking for the solution. The fact here is, CCP uses google's libphonenumber library behind the scene. Example number for hint and text formatting while typing is handled by google library only. CCP does not do any alteration in it. 

Still, we will try our best to solve this as soon as possible. If you find any solution, we will be happy to get a pull request.

**Comment by hbb20** [comment]
For now in version 2.1.5, to get the hint in the national format we have introduced `app:ccp_hintExampleNumberFormat="NATIONAL"`. This should give hint number with leading zeros.

We understand that asYouTypeFormatter should be improved in order to support other formats as well. We will be looking around for the solution.
