### ISSUE TITLE
GB - United Kingdom country code and Isle of Man

### ISSUE THREAD

**Issue by Arasthel** [hbb20/CountryCodePickerProject#168]
Hello,

First of all, thanks for the library, I'm doing a cross-platform app for both Android and iOS phones and I'm using this library for the Android side, it works a lot better than it's iOS counterpart, nice job 👍 .

However, I've found this weird issue, where pre-filling the picker with an UK phone number (+44 ...) would result on it selecting the Isle of Man country code instead of GB. I guess this is because Isle of Man's data on the xmls conflicts with UK, both having +44 as prefix. Could Isle of Man prefix be changed to `+44 1624` instead?

Thanks!

**Comment by hbb20** [comment]
Glad to know that the library is being helpful to developers. 

Thank you so much for reporting. We will look into it and fix it as soon as possible.

**Comment by hbb20** [comment]
Hey, we have fixed this issue in version 2.1.5. Please try it. 

Thank you again for the reporting.
