### ISSUE TITLE
app:ccp_excludedCountries="all" is not recognized

### ISSUE THREAD

**Issue by gyallapu** [hbb20/CountryCodePickerProject#169]
Dear Harsh Bhakta,

First of all , ccp is an excellent library . Nice job ! .

I wanted to add an item like "ALL" . I followed this steps

https://github.com/hbb20/CountryCodePickerProject/wiki/Add-New-Language-Support

and achieved .. It's working fine.

What my problem is i want to exclude "ALL" in one scenario . I was trying to handle it by 

app:ccp_excludedCountries="all"
unfortunately, this attribute is not recognized . I tried hard but didn't find result.
Could you please help me out from this. I hope i will get a response from you ASAP.
Thank you

**Comment by gyallapu** [comment]
By the way , "ALL" is the customized country with countrycode "all" in the scenario

**Comment by hbb20** [comment]
The reason is ccp expects only 2 letter name code. "All" has 3 letters and that is not supported. As a workaround, try by using some 2 letter code which is not assigned to any other country. Like "ol" or "--".

**Comment by gyallapu** [comment]
I don't think it's because of 3 letters .
Now the excluded country is India .

  app:ccp_excludedCountries="in"

and error message is

Error:(130) error: attribute 'com.test.test:ccp_excludedCountries' not found.

**Comment by gyallapu** [comment]
C:\Users\user\Desktop\CountryCodePickerProject\app\src\main\res\layout\fragment_custom_master_list.xml
Error:(114) No resource identifier found for attribute 'ccp_excludedCountries' in package 'in.hbb20.countrycodepickerproject'
C:\Users\user\Desktop\CountryCodePickerProject\app\build\intermediates\res\merged\debug\layout\fragment_custom_master_list.xml
Error:(114) No resource identifier found for attribute 'ccp_excludedCountries' in package 'in.hbb20.countrycodepickerproject'
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by hbb20** [comment]
oh.. what is the version number of the library you cloned?

**Comment by gyallapu** [comment]
Sorry , i have downloaded zip which was older version . I have just cloned the latest and will refactor my requirements over here. By the way thanks for your quick response. Thank you
