### ISSUE TITLE
how to set default country code via programmatically

### ISSUE THREAD

**Issue by Arunkrishna008** [hbb20/CountryCodePickerProject#172]

**Comment by hbb20** [comment]
I hope this[ wiki page](https://github.com/hbb20/CountryCodePickerProject/wiki/Default-Country#b-programmatically) should be helpful. If that does not work then please comment back here I will reopen the issue.

**Comment by Arunkrishna008** [comment]
hi,

countryCodePicker.setDefaultCountryUsingPhoneCode(355);

the method is deprecated and not working

Regards
Arun

**Comment by hbb20** [comment]
What is the version of the library you are using? I tested with the latest code and it seems as expected. 

FYI: As per wiki document, **default country and selected country are different**. Selected country means what you see on CCP view and Default country is set as "selected" country when ccp loads on screen or something goes during country detection. Setting `countryCodePicker.setDefaultCountryUsingNameCode("AD");` will set "AD" country as default country but it is not yet selected. You will need to call `resetToDefaultCountry(); ` to set default country as selected.

**To update the default country and set it as selected**
```
        countryCodePicker = (CountryCodePicker) getView().findViewById(R.id.ccp);
        countryCodePicker.setDefaultCountryUsingNameCode("AD");
        countryCodePicker.resetToDefaultCountry();
```

**Just to set some country on CCP (without changing default country)**
```
        countryCodePicker.setCountryForNameCode("AD");
```

Let us know if this works.
