### ISSUE TITLE
New Metadata

### ISSUE THREAD

**Issue by andregdias** [hbb20/CountryCodePickerProject#177]
Hi, in your .gradle file you are using an older version of the `io.michaelrocks:libphonenumber` library (https://github.com/hbb20/CountryCodePickerProject/blob/c33770444059bca5c5961e7aebfa5ae04c328d5e/ccp/build.gradle#L57).

In the latest version (https://github.com/MichaelRocks/libphonenumber-android/commit/0476822deec57f84c6b669990ff30e2adafd3f0f) the metadata for some countries was updated (including India and its support for Jio network). 

Can you please update your dependency? When can I expect this to be updated?

Thanks in advance.

**Comment by rodrigoborgesdeoliveira** [comment]
Yeah, this is also happening to Brazil's cellphone numbers. In 2015, a 9 started to be added to the beginning of Brazil's cellphone numbers. So now we have the following format +55 XX 9XXXX-XXXX. For landline numbers, it's still the old format +55 XX XXXX-XXXX though.

**Comment by LOG-TAG** [comment]
wow @hbb20 this is the much-needed update!! any way to fix this other than manually including library?

**Comment by hbb20** [comment]
Sorry for the manual inclusion. But yeah, in the upcoming version, CCP will be using the latest version of  MichaelRocks/libphonenumber lib so you won't need to include them manually.

**Comment by hbb20** [comment]
Version 2.2.0 of CCP uses the latest version of MichaelRocks/libphonenumber and it also solves formatting issue for international formatting. Kindly upgrade to the latest version.
