### ISSUE TITLE
Indian mobile starting with 6

### ISSUE THREAD

**Issue by mohitrajput987** [hbb20/CountryCodePickerProject#179]
Now India has mobile numbers starting with 6. 
The library is supporting numbers only starting with 9, 8 or 7.
Please update the validation code.

**Comment by andregdias** [comment]
This is related to the #177 issue that I've opened.

**Comment by LOG-TAG** [comment]
@mohitrajput987 tested with https://github.com/MichaelRocks/libphonenumber-android ? working fine!

**Comment by hbb20** [comment]
Yeah. It's working well. I am working on as you type formatting for the International format. As soon as I get that working, I will launch the new version.

**Comment by hbb20** [comment]
Try version 2.2.0 of the library that should solve this formatting issue. If the problem persists please post back here with details, I will reopen the issue.
