### ISSUE TITLE
[Question] Country flag

### ISSUE THREAD

**Issue by mychaelgo** [hbb20/CountryCodePickerProject#18]
Any plan to add country flag? 👍  :)

**Comment by hbb20** [comment]
@mychaelgo, thanks for pull requests. And yeah flags are something without which I'm feeling a part of library missing. They will come soon as I find some time to do it.  :)

**Comment by mychaelgo** [comment]
@hbb20 check this out 🚀  
PR https://github.com/hbb20/CountryCodePickerProject/pull/22

**Comment by hbb20** [comment]
Nice work done by @mychaelgo  in [feature](https://github.com/hbb20/CountryCodePickerProject/pull/22) . New v1.7 is published with flag support.
