### ISSUE TITLE
Enable / Disable CountryCodePicker

### ISSUE THREAD

**Issue by Ma-Altaiir** [hbb20/CountryCodePickerProject#181]
Hello;

Tried to disable component but it seems like it does not work at all, tried from xml and code both enabled and clickable , none is working.

**Comment by hbb20** [comment]
Hello, 
`android:clickable="false"` will not work. You can use `app:ccp_clickable="false"` from XML and `setCcpClickable(false);` from code to disable click.

If this does not work, feel free to comment back.

**Comment by kamalmeh** [comment]
I dont find setCcpClickable(false) method. Please help.

**Comment by hbb20** [comment]
oh... What is the library version you are using? I think it should be there in latest one at least. 
Here is the method in [code](https://github.com/hbb20/CountryCodePickerProject/blob/master/ccp/src/main/java/com/hbb20/CountryCodePicker.java#L1408).

**Comment by kamalmeh** [comment]
I got it. I was using older version. I am now using the latest as mentioned in README page. My mistake. It is resolved now.
Thanks! for the response.

**Comment by omzer** [comment]
> I dont find setCcpClickable(false) method. Please help.

You need to cast it to (CountryCodePicker), more likely you are dealing with abstract (View).
