### ISSUE TITLE
Swiss numbers don't format when typed without leading 0

### ISSUE THREAD

**Issue by fphilipe** [hbb20/CountryCodePickerProject#183]
Swiss phone numbers, e.g. `+41 79 123 45 67` (local format `079 769 51 41`), don't format when typed without the leading 0, which is not present in the international format.

I'd expect that I could type the number with or without the leading 0.

This happens on version 2.1.9.

**Comment by hbb20** [comment]
Try version 2.2.0 of the library that should solve this formatting issue. If the problem persists please post back here with details, I will reopen the issue.

**Comment by fphilipe** [comment]
The problem still persists.

**Comment by hbb20** [comment]
Can you show the gradle file and testing device? Because I tried it with my sample app (which uses 2.2.0 of CCP) and here is the result. I tried the exact number you provided and it worked here. 

![ch_num](https://user-images.githubusercontent.com/4918760/39190932-41922a80-479b-11e8-9229-c6011fb9266c.gif)

**Comment by eduoie** [comment]
Hi. Here is a screenshot with the same number, rendered with a leading zero and without it.
The dependency is set as follows:
`countryPhoneCodePicker     : "com.hbb20:ccp:2.2.0"`

The device used for testing is a Google Pixel, android 8.1.0

![swiss phone with leading zero](https://user-images.githubusercontent.com/2017983/39192904-8f7b6cd6-47da-11e8-8cbf-b3181ebf2e7e.png)
![swiss phone no leading zero](https://user-images.githubusercontent.com/2017983/39192905-8fa7c722-47da-11e8-8b43-6b2e851454c2.png)

**Comment by fphilipe** [comment]
@hbb20 it's possible I reported the wrong thing, i.e. the expected behavior is not happening when typing a leading zero.

**Comment by hbb20** [comment]
Yeah. That's an interesting question. As CCP is meant for international numbers, it should format only international numbers. Leading 0(s) are part of the national format of the number and not of international format.
