### ISSUE TITLE
eclipse

### ISSUE THREAD

**Issue by H1-N1** [hbb20/CountryCodePickerProject#187]
first of all thx for your amazing work !
can new plz guide me how i can implement your project in main eclipse project
thx

**Comment by hbb20** [comment]
I haven't used eclipse but you might be able to include maven using
```
<dependency>
  <groupId>com.hbb20</groupId>
  <artifactId>ccp</artifactId>
  <version>2.2.0</version>
  <type>pom</type>
</dependency>
```
