### ISSUE TITLE
Stripping leading 0 ?

### ISSUE THREAD

**Issue by alexkent** [hbb20/CountryCodePickerProject#192]
If a user types a telephone number with the national '0' prefix, the value returned from `getFullNumber()` will include this prefix and be an invalid number. e.g +460701231231

Is this intended behaviour? (is stripping this prefix considered out of scope of this library?)
Is there a suggested / preferred workaround for this?

Thanks!

**Comment by hbb20** [comment]
Hi @alexkent, Which version of the library are you using?

**Comment by alexkent** [comment]
hey @hbb20 I was using 2.1.2.
This behaviour appears to be fixed in 2.1.3
Thanks!
