### ISSUE TITLE
Cannot change fontName or fontFamily

### ISSUE THREAD

**Issue by Apurba06** [hbb20/CountryCodePickerProject#193]

**Comment by frigidBlade7** [comment]
same issue here. any ideas how to fix? clone project and add as module?

**Comment by hbb20** [comment]
What view's fonts you want to change? CCP or Dialog?

**Comment by frigidBlade7** [comment]
Hi thanks for your reply!

For the country code picker format where the flag and the country code (eg. 🇬🇧, +44 ) show, is it possible to change the font of the country code ??

Nathany, GMail Account

**Comment by hbb20** [comment]
I hope this [wiki page](https://github.com/hbb20/CountryCodePickerProject/wiki/Custom-TypeFace-(FontFamily)) about custom typeface should be helpful.

Feel free to comment back if this is not what you are looking for. I will re-open the issue.

Thanks.

**Comment by frigidBlade7** [comment]
Can’t believe it I’ve been such an idiot! Although was hoping to see it maybe implemented via the xml ui builder,
Say, some app:fontFamily so it could be set via xml. 


Thanks for your support and so sorry for wasting your time!

Nathany, GMail Account
