### ISSUE TITLE
can update picker dialog title

### ISSUE THREAD

**Issue by anoreg** [hbb20/CountryCodePickerProject#195]
Some country has many regions. If using "Select a country" may be a little  inappropriate. How about update to "Select a country or region". Or let user just hide the pick dialog title

**Comment by hbb20** [comment]
Hello @anoreg , sorry for late response but hopefully this will be helpful.
Call `CCPCountry.setDialogTitle("Select a country or region");` once CCP view is set loaded. 

Note: Internally, this property is updated every time language change is triggered. If you are changing language manually, make sure to call this every time.

**Comment by hbb20** [comment]
We are working on other suggestion for hiding title.
