### ISSUE TITLE
Issue when loading gradle

### ISSUE THREAD

**Issue by MuthuSubramaniam** [hbb20/CountryCodePickerProject#198]
When I am trying to add library 

**implementation 'com.hbb20:ccp:2.2.0'**

.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/78a984e511843b693552d73bf37c7eea/res/values-v26/values-v26.xml |  
-- | --
error: resource android:attr/colorError not found. |  
error: resource android:attr/colorError not found. |  
error: style attribute 'android:attr/keyboardNavigationCluster' not found. |

**Comment by hbb20** [comment]
Oh this is something I notices for the first time. Sometimes, clean / rebuild project solves the problem by removing intermediate files. If that does not solve the problem then post your gradle file content that will be helpful in finding the problem.

**Comment by hbb20** [comment]
Hello @MuthuSubramaniam , can you please confirm if the problem is still there?

**Comment by MuthuSubramaniam** [comment]
Hello Team,

 Thanks for keep tracking my issue. I removed that library and used my own web API. Because of consistency on both Android and iOS. The client expect both should be same. Thanks again for the follow-up. Keep rocking.
