### ISSUE TITLE
Render problem 

### ISSUE THREAD

**Issue by ISvengali** [hbb20/CountryCodePickerProject#200]
I followed the integration as it is and getting this error in my xml
`<item> tag requires a 'drawable' attribute or child tag defining a drawable`

This is my gradle conf 

`apply plugin: 'com.android.application'
android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.example.myapp"
        minSdkVersion 21
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.google.android.gms:play-services-maps:15.0.1'
    implementation 'com.android.support:support-annotations:27.1.1'
    implementation 'com.android.support:support-v4:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.hbb20:ccp:2.1.2'
    implementation 'com.android.support:support-vector-drawable:27.1.1'
    implementation 'com.android.support:recyclerview-v7:27.1.1'
    implementation 'com.android.support:support-v13:27.1.1'
}`

**Comment by hbb20** [comment]
It is hard to figure out the exact problem from the description. 
1. Is this problem still persistent?
2. Did you try by clean and rebuild project
3. If you remove CCP from dependency and CCP code from the project then clean and rebuild it. Does this problem go away?
4. It looks like you are using custom drawables. Are you sure that this is not coming from any custom XML drawable file which might be missing drawable inside <item> tag?

**Comment by ISvengali** [comment]
I rebuild-ed the project and worked fine.
