### ISSUE TITLE
Suggestions on the name of the country

### ISSUE THREAD

**Issue by RookieExaminer** [hbb20/CountryCodePickerProject#201]
First of all, thank you very much for your open source project. I also intend to apply it to the project but I found a small problem. Taiwan Hong Kong Macao belongs to China. Suffix should add China after the name. Ihope you can fix it. Thank you.

**Comment by hbb20** [comment]
Hello @RookieExaminer, glad to know that you found this project helpful. We understand your concern please follow this [wiki page](https://github.com/hbb20/CountryCodePickerProject/wiki/Change-country-names-for-personal-project) to update the names for your project.
