### ISSUE TITLE
IndexOutOFBoundsException 

### ISSUE THREAD

**Issue by SephirothLT** [hbb20/CountryCodePickerProject#203]
![image](https://user-images.githubusercontent.com/20485889/40765514-41764584-64df-11e8-94e2-30220aa1b17d.png)

**Comment by SephirothLT** [comment]
I exact the internationTextWatcher,but  Selection.setSelection(s,finalCurxx);
occur this error!

**Comment by SephirothLT** [comment]
@hbb20

**Comment by uditmukherjee** [comment]
@SephirothLT : How did you solve this?

**Comment by SephirothLT** [comment]
I have used another library.  Or you can copy this library and rewrite this method

**Comment by hbb20** [comment]
What is the version of CCP? Can you describe the scenario (selected country  and keystrokes) to reproduce this?

**Comment by Aakash9565** [comment]
I was getting the same issue, resolved it by adding:

`app:ccp_autoFormatNumber="false"`

in the XML code.
Hope this helps. :)

**Comment by MartinCazares** [comment]
Still happening in the latest version with current XML code:
```
<com.hbb20.CountryCodePicker
   android:id="@+id/country_code_picker"
   android:layout_width="wrap_content"
   android:layout_height="wrap_content"
   app:ccp_defaultNameCode="US" />

<android.support.v7.widget.AppCompatEditText
    android:id="@+id/phone_number"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:inputType="number"
    android:maxLines="1" />
```

No need to do anything special to reproduce, after registering with:

> mCountryCodePicker.registerCarrierNumberEditText(mPhoneNumberEditText);

All you need to do is type more than 4 numbers for the crash to happen...

**Comment by MartinCazares** [comment]
I was able to reproduce this crash when instead of using:

> android:inputType="phone" in the EditText for the number you use:

> android:inputType="phone"

**Comment by hbb20** [comment]
@MartinCazares , I will add this suggestion in wiki guideline.
