### ISSUE TITLE
Add country

### ISSUE THREAD

**Issue by khaledhnAbusair** [hbb20/CountryCodePickerProject#204]
Can I **add some countries** ? not all of them

**Comment by hbb20** [comment]
Do you mean only a few contries in selection box? If so, look at masterCountries [wiki page](https://github.com/hbb20/CountryCodePickerProject/wiki/Custom-Master-Country-List). 

If you are looking for something else, please comment back with details, I will reopen the issue.

**Comment by khaledhnAbusair** [comment]
Thank u , can I change the language for default country because always show in English not a language for countries just default country .
