### ISSUE TITLE
Default country language 

### ISSUE THREAD

**Issue by khaledhnAbusair** [hbb20/CountryCodePickerProject#205]
can I change the language for default country because always show in English not a language for countries just default country .

**Comment by hbb20** [comment]
I did not understand the question. Can you elaborate with the example?

**Comment by ntsparis** [comment]
You can add in xml:

`app:ccp_defaultNameCode="gr"`

**Comment by sgallese** [comment]
@hbb20 maybe @khaledhnAbusair is referring to the fact that this flag is set to default false?
https://github.com/hbb20/CountryCodePickerProject/wiki/XML-Properties#appccp_autodetectlanguagetrue-default--false-

As a user of this library (which is great!), I might expect this to be set to true by default.

@khaledhnAbusair could be referring to something completely unrelated though.

**Comment by hbb20** [comment]
Hello @sgallese, 

I can understand your concern. The only reason for keeping default `false` is to avoid _surprises_. Developer should know how their app is going behave. Before version 2.1.0, we kept `true` as default value for [app:ccp_autoDetectCountry](https://github.com/hbb20/CountryCodePickerProject/wiki/XML-Properties#appccp_autodetectcountrytrue-default--false-). We thought that will be really helpful for developers but then we started receiving issues regarding confusion like #76, #88 . Then we realised that default value `true` is surprising users. So we decided to go for `false` as default value. Developer can always enable it (with out being surprised). 

Is it helpful?

**Comment by sgallese** [comment]
Makes sense to me. Either way can be confusing- hard to win there.

Maybe developers are expecting autoDetectCountry to be true by default and that defaultNameCode would automatically override that value (even if it's set to true).

Don't want to make it more confusing for developers, but if the current implementation will stay as-is, might help to mention autoDetectCountry flag here: https://github.com/hbb20/CountryCodePickerProject/wiki/Multi-Language-Support
