### ISSUE TITLE
How to display selected country Flag image along with text in another location?

### ISSUE THREAD

**Issue by shahzadakram67** [hbb20/CountryCodePickerProject#210]
How to display selected country Flag image along with text in another location e.g. I want to show country of a user in his profile how to show this along with flag image??

**Comment by hbb20** [comment]
Hey @shahzadakram67, Can you please elaborate your requirement?

**Comment by hbb20** [comment]
Sure you can do that.
1. Add CCP as country selector in your SignUp screen. Read [How to use CCP as Country Selector](https://github.com/hbb20/CountryCodePickerProject/wiki/Use-as-a-Country-Selector)
2. Store selected country code with user profile details. Read [How to read country detail](https://github.com/hbb20/CountryCodePickerProject/wiki/Read-Selected-Country-Properties)
3. On profile screen, place CCP as Country Selector. This time you might want to set as ccpClickable = false.
4. Retrieve country code from profile data and load it in CCP using `ccp.setCountryForNameCode(String countryNameCode)`

This should work. Please post back if you have any query.
