### ISSUE TITLE
Farsi Translation Required

### ISSUE THREAD

**Issue by hbb20** [hbb20/CountryCodePickerProject#213]
We want help in translating few country names to **Farsi**.

```
<country
name="TODO: replace with  translated country name"
english_name="Aland Islands"
name_code="ax"
phone_code="358" />

<country
name="TODO: replace with  translated country name"
english_name="American Samoa"
name_code="as"
phone_code="1" />

<country
name="TODO: replace with  translated country name"
english_name="British Indian Ocean Territory"
name_code="io"
phone_code="246" />

<country
name="TODO: replace with  translated country name"
english_name="Guam"
name_code="gu"
phone_code="1" />

<country
name="TODO: replace with  translated country name"
english_name="Guernsey"
name_code="gg"
phone_code="44" />

<country
name="TODO: replace with  translated country name"
english_name="Jersey"
name_code="je"
phone_code="44" />

<country
name="TODO: replace with  translated country name"
english_name="Norfolk Islands"
name_code="nf"
phone_code="672" />

<country
name="TODO: replace with  translated country name"
english_name="Northern Mariana Islands"
name_code="mp"
phone_code="1" />

<country
name="TODO: replace with  translated country name"
english_name="Saint Martin"
name_code="mf"
phone_code="590" />
```

**Comment by hbb20** [comment]
@ayhansalami can you help here?

**Comment by ayhansalami** [comment]
Yes, of course.
`<country
name="جزایر الند"
english_name="Aland Islands"
name_code="ax"
phone_code="358" />

<country
name="ساموآی آمریکا"
english_name="American Samoa"
name_code="as"
phone_code="1" />

<country
name="قلمرو اقیانوس هند بریتانیا"
english_name="British Indian Ocean Territory"
name_code="io"
phone_code="246" />

<country
name="گوام"
english_name="Guam"
name_code="gu"
phone_code="1" />

<country
name="گرنزی"
english_name="Guernsey"
name_code="gg"
phone_code="44" />

<country
name="جرسی"
english_name="Jersey"
name_code="je"
phone_code="44" />

<country
name="جزیره نورفک"
english_name="Norfolk Islands"
name_code="nf"
phone_code="672" />

<country
name="جزایر ماریانای شمالی"
english_name="Northern Mariana Islands"
name_code="mp"
phone_code="1" />

<country
name="سنت مارتین"
english_name="Saint Martin"
name_code="mf"
phone_code="590" />`

@hbb20

**Comment by ayhansalami** [comment]
Yes, of course.
`<country
name="جزایر الند"
english_name="Aland Islands"
name_code="ax"
phone_code="358" />

<country
name="ساموآی آمریکا"
english_name="American Samoa"
name_code="as"
phone_code="1" />

<country
name="قلمرو اقیانوس هند بریتانیا"
english_name="British Indian Ocean Territory"
name_code="io"
phone_code="246" />

<country
name="گوام"
english_name="Guam"
name_code="gu"
phone_code="1" />

<country
name="گرنزی"
english_name="Guernsey"
name_code="gg"
phone_code="44" />

<country
name="جرسی"
english_name="Jersey"
name_code="je"
phone_code="44" />

<country
name="جزیره نورفک"
english_name="Norfolk Islands"
name_code="nf"
phone_code="672" />

<country
name="جزایر ماریانای شمالی"
english_name="Northern Mariana Islands"
name_code="mp"
phone_code="1" />

<country
name="سنت مارتین"
english_name="Saint Martin"
name_code="mf"
phone_code="590" />`

**Comment by ayhansalami** [comment]
Yeas of course.
```
<country
name="جزایر الند"
english_name="Aland Islands"
name_code="ax"
phone_code="358" />

<country
name="ساموآی آمریکا"
english_name="American Samoa"
name_code="as"
phone_code="1" />

<country
name="قلمرو اقیانوس هند بریتانیا"
english_name="British Indian Ocean Territory"
name_code="io"
phone_code="246" />

<country
name="گوام"
english_name="Guam"
name_code="gu"
phone_code="1" />

<country
name="گرنزی"
english_name="Guernsey"
name_code="gg"
phone_code="44" />

<country
name="جرسی"
english_name="Jersey"
name_code="je"
phone_code="44" />

<country
name="جزیره نورفک"
english_name="Norfolk Islands"
name_code="nf"
phone_code="672" />

<country
name="جزایر ماریانای شمالی"
english_name="Northern Mariana Islands"
name_code="mp"
phone_code="1" />

<country
name="سنت مارتین"
english_name="Saint Martin"
name_code="mf"
phone_code="590" />
```
@hbb20

**Comment by ayhansalami** [comment]
Yeas of course.
```
<country
name="جزایر الند"
english_name="Aland Islands"
name_code="ax"
phone_code="358" />

<country
name="ساموآی آمریکا"
english_name="American Samoa"
name_code="as"
phone_code="1" />

<country
name="قلمرو اقیانوس هند بریتانیا"
english_name="British Indian Ocean Territory"
name_code="io"
phone_code="246" />

<country
name="گوام"
english_name="Guam"
name_code="gu"
phone_code="1" />

<country
name="گرنزی"
english_name="Guernsey"
name_code="gg"
phone_code="44" />

<country
name="جرسی"
english_name="Jersey"
name_code="je"
phone_code="44" />

<country
name="جزیره نورفک"
english_name="Norfolk Islands"
name_code="nf"
phone_code="672" />

<country
name="جزایر ماریانای شمالی"
english_name="Northern Mariana Islands"
name_code="mp"
phone_code="1" />

<country
name="سنت مارتین"
english_name="Saint Martin"
name_code="mf"
phone_code="590" />
```
@hbb20

**Comment by hbb20** [comment]
Thank you @ayhansalami , these countries are added to v2.2.2. Thank you.
