### ISSUE TITLE
Action event click setOnClickListener

### ISSUE THREAD

**Issue by cahyofendhi** [hbb20/CountryCodePickerProject#218]
can i handling event click, like `setOnClickListener`, i try like that but always select `country code`, when i enable false, event click not working,

**Comment by hbb20** [comment]
You want to override the click event or want to get a callback when clicked in addition to launch country selector?

**Comment by cahyofendhi** [comment]
i want to override the click, and disable launch country selector when clicked

**Comment by victsomie** [comment]
I too am looking for this option.

I need to disable pop-up if for example I have only one country.
The current work around is having custom countries. Check doc: https://github.com/hbb20/CountryCodePickerProject/wiki/Custom-Master-Country-List

Could this be added as a new feature?

**Comment by hbb20** [comment]
Hello @victsomie , @cahyofendhi.
Please upgrade to v2.2.3 and use `ccp.overrideClickListener()` method for custom clicklistener.
[Read more](https://github.com/hbb20/CountryCodePickerProject/wiki/Handle-CCP-ClickListener-Manually)
