### ISSUE TITLE
SetSelection

### ISSUE THREAD

**Issue by kishan2212** [hbb20/CountryCodePickerProject#219]
How can i " ccp.setSelection(position or name) " ?

**Comment by hbb20** [comment]
List position and name are not reliable property to identify and set the country. 

A country can be uniquely identified using its name code. You can use country name code to set as the selection. Try `ccp. setCountryForNameCode("nc")`. *"nc" should be 2 letter name code of the country you want set in ccp*

Did it answer your question?

**Comment by kishan2212** [comment]
found it bro thanks :)
