### ISSUE TITLE
Remove country code

### ISSUE THREAD

**Issue by mahesh517** [hbb20/CountryCodePickerProject#221]
How to remove or hide one country code

**Comment by Aakash9565** [comment]
Can you be more specific about whether you want to hide country code shown in the spinner or in all the items. If you just want to hide from the spinner you can do this in xml part:

`app:ccp_showNameCode="false"`

**Comment by hbb20** [comment]
@mahesh517 , as @Aakash9565 suggested, this question is open to multiple interpretations.

1. Remove country code from CCP view
    - As suggested by @Aakash9565 , add `app:ccp_showNameCode="false"` to your xml.
2. Remove country code from CCP selection dialog
   - add `app:ccpDialog_showNameCode ="false"` to your xml.
3. Remove country entry from the selection list
   - To exclude country from selection list, use `ccp_excludedCountries` property. [Read more](https://github.com/hbb20/CountryCodePickerProject/wiki/Exclude-specific-countries).

Did this answer your query? Please post back.
