### ISSUE TITLE
Language defaults to english when Proguard is enabled

### ISSUE THREAD

**Issue by lfweigel** [hbb20/CountryCodePickerProject#227]
It seems that when proguard's obfuscation is enabled, the language defaults to english and ignores both app:ccp_defaultLanguage and app:ccp_autoDetectLanguage values. Everything works just fine when             minifyEnabled is set to false.

After some testing, it seems that the correct language is being detected, but for some reason it fails to apply:

`08-09 23:34:22.862 32196-32196/? D/CCP: getCCPLanguageFromLocale: current locale languagept
    updateLanguageToApply: PORTUGUESE`

But language is still set to english.

**Comment by hbb20** [comment]
oops, that's weird. What rules are you using for proguard?

**Comment by lfweigel** [comment]
Originally i had none (related to this cool lib!), but adding `-keep class com.hbb20.** { *; }` does not seem to solve the issue, which is kind of weird and probably indicates it may not be proguard's fault after all. (although im no proguard expert)

The only other difference was the build variant, which was previously set to debug when everything was working fine. Tried enabling proguard on the debug variant, and the problem persists.

Maybe the issue is related to something else which is somehow triggered by the obfuscation. The language is always set to english, regardless of the phone's locale or the default language set.

**Comment by lfweigel** [comment]
I was unable to reproduce the issue on a sample app, guess the problem is hiding somewhere else.

Will investigate a little bit further and update if I found a solution which may be of help to others.

**Comment by lfweigel** [comment]
Forgot to post an update: this is caused by proguard's _shrinkResources_ flag. I was able to reproduce this issue on the demonstration app provided by turning the flag on and setting a default language on a random picker.

My guess would be that it flags the translation related stuff on src/raw as unused and removes it at compile-time when the flag is set.

**Comment by rolgalan** [comment]
Maybe we should add a `keep.xml` file to make sure proguard is not messing anything up?
https://developer.android.com/studio/build/shrink-code#keep-resources

I have a branch where I added that and avoided the filtering crash, I can do a PR of this:
https://github.com/rolgalan/CountryCodePickerProject/commit/4cabde94e60419c80138ea492daa2368a70a8d4b

**Comment by hbb20** [comment]
keep.xml is added in version 2.2.3. So theoretically CCP (>2.2.3) is pro-guard compatible.  If the problem remains persistent or you face any other issue regarding Proguard, feel free to report here.

**Comment by Mihir3646** [comment]
> keep.xml is added in version 2.2.3. So theoretically CCP (>2.2.3) is pro-guard compatible. If the problem remains persistent or you face any other issue regarding Proguard, feel free to report here.

Where is Keep.xml? Not able to find it.

**Comment by hbb20** [comment]
This should open the file:
https://github.com/hbb20/CountryCodePickerProject/blob/master/ccp/src/main/res/raw/keep.xml
