### ISSUE TITLE
Auto detect function

### ISSUE THREAD

**Issue by ceddyb** [hbb20/CountryCodePickerProject#23]
Looking for an automatic way to detect the country from a string/phone number.

For example i have an edit text then a user enters a phone number, is there a method to detect the country code/info then update the flag and code automatically.

**Comment by hbb20** [comment]
Yeah definitely that can be done using CCP library. You have to use CCP's
functionality for "Full number support". For more detail and live demo of
feature download the app from
https://play.google.com/store/apps/details?id=in.hbb20.countrycodepickerproject&hl=en
and check the feature with "full number support". Demo has exactly the same
feature as what you asked. Hope that will work for you. And update your
response on this issue.

**Comment by ceddyb** [comment]
Oh yes! Awesome Lib!

Just downloaded your app, it has great documentation.

Last question, is there a way to simply have a listener on the edit text to detect the full number instead of pressing the "Load" button?

Thank

**Comment by hbb20** [comment]
You can add textwatcher to the edit text where you are expecting full
number... Adding textwatcher will allow you to call that function everytime
the edit text is updated.
