### ISSUE TITLE
Brazilian number is not validating even if it's valid number 84 9219-xxxx

### ISSUE THREAD

**Issue by parthh** [hbb20/CountryCodePickerProject#237]

**Comment by hbb20** [comment]
CCP does not do any verification on it's own. It relies on google phone library for that. But I did some search this might be helpful.

For Brazil number,

(two-digit Country Code) + (two-digit Area code) + (five-digit Prefix) + (four-digit unique number)

Two-digit Country code: +55

Two-digit Area code: depends on the state For example: Sao Paulo is 11; Rio de Janeiro is 21…

Five-digit Prefix: usually starts with 9

Four-digit unique number

EXAMPLE: +55 11 98456 5666

https://www.quora.com/What-is-a-cellphone-number-from-Brazil-look-like

**Comment by hbb20** [comment]
hello @parthh , any update on this?

**Comment by parthh** [comment]
Actually,
The number that I have provided you is from Brazil but somehow even if
library is using the goole library as parent it's not verifying as
Brazilian number.


Regards
Parth Gadhiya
+14388757211

**Comment by hbb20** [comment]
I also tried with some other validators like https://www.textmagic.com/free-tools/phone-validator but it also detected as invalid number. Looks like something is wrong with that format.
