### ISSUE TITLE
Feature request: make rlClickConsumer public

### ISSUE THREAD

**Issue by rndk** [hbb20/CountryCodePickerProject#243]
Hi,
Can you make RelativeLayout "rlClickConsumer " public to able to setBackgroundColor or setBackgroundDrawable?

**Comment by hbb20** [comment]
Hello @rndk,
Please update ccp to v2.2.3. `getHolder()` method is public now which will return relative layout. For custom background you should use this. Thank you.

**Comment by rndk** [comment]
Thank you!
