### ISSUE TITLE
Adding line below country code

### ISSUE THREAD

**Issue by Vengat121** [hbb20/CountryCodePickerProject#246]
Hi,
    I need to add line below country and and adjust that line

**Comment by hbb20** [comment]
Hello,

Can you please explain more in detail? You need line in the country list
(dialog) or name code (ccp view)? And what do you mean by "adjust that
line"? Rough hand sketch will be greatly helpful.

**Comment by hbb20** [comment]
That mobile number is simple edittext or wrapped in text input layout?

**Comment by Vengat121** [comment]
text input layout, Here is my code

            <LinearLayout
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:orientation="horizontal">

                <android.support.design.widget.TextInputLayout
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:textColorHint="@color/colorPrimary">

                    <com.hbb20.CountryCodePicker
                        android:id="@+id/spinner_update_country_code"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        app:ccpDialog_keyboardAutoPopup="false"
                        android:ems="5"
                        android:singleLine="true"
                        android:textSize="@dimen/eighteen_sp"
                        app:ccp_showNameCode="false"
                        app:ccp_autoDetectCountry="false"
                        style="@style/Widget.AppCompat.Spinner.Underlined"/>
                    
                </android.support.design.widget.TextInputLayout>


                <android.support.design.widget.TextInputLayout
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="@dimen/twenty_dp"
                    android:singleLine="true"
                   android:textColorHint="@color/colorPrimary"
                    android:layout_marginStart="@dimen/twenty_dp">

                    <android.support.design.widget.TextInputEditText
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:singleLine="true"
                        android:ems="10"
                        android:textSize="@dimen/eighteen_sp"
                        android:hint="@string/mobile_number"
                        android:id="@+id/editText_update_mobile"
                        android:textColor="@color/black"
                        android:inputType="number"
                        android:maxLength="15"/>
                </android.support.design.widget.TextInputLayout>

            </LinearLayout>

**Comment by hbb20** [comment]
Match the line is tricky part and very specific requirement. So probably we won't be able to add as functionality but if you need it, you can try following.

1. Create a layout file named "layout_code_picker.xml" (Name should match)
2. In that layout file add xml code (given at the end).
3. Modify margin (and background color probably) of view with id = viewHorLine so that it matches your requirement.
(Note: this will override ccp's default layout. In future release, if CCP decides to modify this file then you will have to do modifications in your this local to use that new version.)
```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/countryCodeHolder"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content">

    <RelativeLayout
        android:id="@+id/rlClickConsumer"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="@drawable/ccp_selectable_bg"
        android:padding="8dp">
        
        <!--You should modify color and top margin of this view to get underline-->
        <View
            android:id="@+id/viewHorLine"
            android:layout_width="match_parent"
            android:layout_height="1dp"
            android:layout_alignRight="@+id/imageView_arrow"
            android:layout_below="@id/textView_selectedCountry"
            android:background="@android:color/black"
            android:layout_marginTop="4dp"/>

        <LinearLayout
            android:id="@+id/linear_flag_holder"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerVertical="true"
            android:layout_gravity="center_vertical"
            android:layout_marginEnd="@dimen/google_1x"
            android:layout_marginRight="@dimen/google_1x">

            <LinearLayout
                android:id="@+id/linear_flag_border"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:background="@android:color/transparent">

                <ImageView
                    android:id="@+id/image_flag"
                    android:layout_width="wrap_content"
                    android:layout_height="18dp"
                    android:layout_margin="0.5dp"
                    android:adjustViewBounds="true"
                    android:src="@drawable/flag_india" />
            </LinearLayout>
        </LinearLayout>

        <!--</LinearLayout>-->
        <TextView
            android:id="@+id/textView_selectedCountry"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerVertical="true"
            android:layout_toEndOf="@+id/linear_flag_holder"
            android:layout_toRightOf="@+id/linear_flag_holder"
            android:singleLine="true"
            android:text="(IN) +91"
            android:textColor="@android:color/black"
            android:textSize="18sp" />

        <ImageView
            android:id="@+id/imageView_arrow"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerVertical="true"
            android:layout_toEndOf="@+id/textView_selectedCountry"
            android:layout_toRightOf="@+id/textView_selectedCountry"
            android:adjustViewBounds="true"
            android:alpha="0.6"
            android:src="@drawable/ccp_down_arrow"
            android:tint="@android:color/black" />
    </RelativeLayout>
</RelativeLayout>
```

**Comment by Vengat121** [comment]
Thanks :)
