### ISSUE TITLE
isValidFullNumber functionality

### ISSUE THREAD

**Issue by ritesh-karmare** [hbb20/CountryCodePickerProject#249]
Keep up the great work and support. This library has been quite helpful!

Just to confirm, based on what factors/conditions does `isValidFullNumber()` return true

**Comment by hbb20** [comment]
Hello @ritesh-karmare, glad to know that CCP is being helpful.
As per current implementation:
isValidFullNumber() uses google PhoneNumberUtil's Android Port to validate the number. 
It will create a full number by combining country code and carrier number. Then parses and validate that number using PhoneNumberUtil's Android Port. 

If it validates the number then it returns true.
If editText is not registered or full number was not parsed correctly or PhoneNumberUtil does not recognize it as valid number then it returns false. 

Feel free to comment back if this does not answer what you were looking for.
