### ISSUE TITLE
How to use with databinding

### ISSUE THREAD

**Issue by IEnoobong** [hbb20/CountryCodePickerProject#250]
Please how can I use with databinding to get `selectedCountryCodeWithPlus`

Thanks!

**Comment by pankajnegii** [comment]
-In your xml, inside <hbb20>
                       <com.hbb20.CountryCodePicker
                        ......
                        bind:countryValue="@{viewmodel.code}"    />

-In your adapter class, do something like this.

 @BindingAdapter("bind:countryValue")
    public static void setCountryValue(final CountryCodePicker picker, ObservableField<String> code) {
        picker.setOnCountryChangeListener(new CountryCodePicker.OnCountryChangeListener() {
            @Override
            public void onCountrySelected() {
                 code.set(picker.getSelectedCountryCodeWithPlus().toString());
            }
        });

-Inside Viewmodel class, 

               public final ObservableField<String> code = new ObservableField<>();

Now, You can get the values using-           code.get();

**Comment by hbb20** [comment]
@pankajnegii, thank you for the answer. @IEnoobong , we hope @pankajnegii's answer worked for you. If you have any further question feel free to comment back.

**Comment by IEnoobong** [comment]
Thank you very much @pankajnegii and @hbb20 ! Much appreciated!

**Comment by Makinul** [comment]
Can anyone help me with LiveData instead of ObservableField.

- Thanks in advance

**Comment by phixtalk** [comment]
Hello hbb20, thanks for this wonderful library.
I've been able to implement it inside of a fragment using android databinding,
however i'm finding it a bit of a challenge getting the country code
inside of a viewmodel (MVVM) with databinding
Would really appreciate any help.
Thanks
