### ISSUE TITLE
How to change the color of the arrow ? It doesn't change.

### ISSUE THREAD

**Issue by Mirmuhsin** [hbb20/CountryCodePickerProject#256]
I used app:ccp_contentColor="{white color}", but it doesn't work. It works on the XML, however when I run the app the country code text is WHITE and the arrow still remains as BLACK. I tried different colors and it doesn't seem to work.
Am I doing something wrong in my code ?

**Comment by hbb20** [comment]
Can you please confirm one thing? Is this happening in demo app as well?
Demo app has a screen for theme where color is changed dynamically.

**Comment by Mirmuhsin** [comment]
Just checked the demo app, it is working fine. In this case, the problem is
in my part. Thanks for the quick response. I am gonna check out the demo
app source code then :)

**Comment by Mirmuhsin** [comment]
I checked my app on other phone (Android Nougat) and the arrow changes, no
problem. But on the other phone, which runs Lollipop (5.0) the arrow is
always black. No change. Have you encountered this problem before?

**Comment by hbb20** [comment]
Yes.. I just checked it. It's happening on Lollipop only. For even Kitkat it's working well. Interestingly color is applied when setContentColor is called (when color tile is clicked in sample app) but when cpp is clicked, arrow goes black.... No idea about the reason... If anyone knows the solution, please post back here...

**Comment by hbb20** [comment]
@Mirmuhsin. Finally, I found the issue and the solution. Explicit declaration of tint in XML file was the issue. (But don't know why. Probably some platform specific issue). But this problem will be solved in next release of the library.

**Comment by hbb20** [comment]
Problem has been fixed in version 2.2.4. If it does not work, please comment back with details.
