### ISSUE TITLE
check input number?

### ISSUE THREAD

**Issue by zoro238** [hbb20/CountryCodePickerProject#260]
How can I make sure that the input number is correct?
An example of a function is possible to verify the input so that if it is true, it will give a correct message.
How can I get the number entered in a variable

**Comment by hbb20** [comment]
Well, looks like you want something like [number validation](https://github.com/hbb20/CountryCodePickerProject/wiki/Full-Number-Support#3-number-validation) feature. If this did not solve your query, feel free to post back with details.

**Comment by hbb20** [comment]
Just remove the "return true;" line and you will be all set. The function is not asking to return anything. This is the callback from CCP whenever validity of number is changed.

**Comment by zoro238** [comment]
I want to make sure the number is true and there is And gives in the case to make sure that it is true gives the value of shouting
Or wrong but the class rejects it

**Comment by zoro238** [comment]
ex 

if( userCheck() && cityCheck() && numberCheck)
                Toast.makeText(Register.this, "ok number", Toast.LENGTH_SHORT).show();

**Comment by hbb20** [comment]
//declare an instance variable numberCheck 
```java
boolean numberCheck = false;
```

//update this variable value with callback
```java
 ccp.setPhoneNumberValidityChangeListener(new CountryCodePicker.PhoneNumberValidityChangeListener() {
        @Override
        public void onValidityChanged(boolean isValidNumber) {
           numberCheck = isValidNumber;
           onFormFieldChanged();
        }
    });
```

and finally make function `onFormFieldChanged()` and call it when city or user details are changed as well.

```java
void onFormFieldChanged(){
    if( userCheck() && cityCheck() && numberCheck){
        //now here your form is valid and go ahead....
    }else{
       //handle other conditions (one or more conditions did not match)
    }
}
```

**Comment by zoro238** [comment]
thank you a lots for replay


but same error

this my code

public class MainActivity extends AppCompatActivity {
    CountryCodePicker ccp;
    boolean numberCheck = false;
    EditText editTextCarrierNumber;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        ccp = (CountryCodePicker) findViewById(R.id.ccp);
        editTextCarrierNumber = (EditText) findViewById(R.id.editText_carrierNumber);
        ccp.setPhoneNumberValidityChangeListener(new CountryCodePicker.PhoneNumberValidityChangeListener() {
            @Override
            public void onValidityChanged(boolean isValidNumber) {
                numberCheck = isValidNumber;
                Log.v("hihi","test ok");
                Toast.makeText(MainActivity.this, "ok", Toast.LENGTH_SHORT).show();
            onFormFieldChanged();
            }
        });


    }



    void onFormFieldChanged(){
        if(  numberCheck){
            Toast.makeText(this, "thi test ok", Toast.LENGTH_SHORT).show();        }
            else{
            Toast.makeText(this, "thi test error", Toast.LENGTH_SHORT).show();        }

        //handle other conditions (one or more conditions did not match)
        }

}

**Comment by hbb20** [comment]
Looks like setup is missing.

Add

ccp.registerCarrierNumberEditText(editTextCarrierNumber);

Before setting Validity change listener...

**Comment by zoro238** [comment]
i am tested but not save number phone

V/testcreate: value input =  +91
V/testcreate: check isValidNumber=  false
value number false

code 
`public class MainActivity extends AppCompatActivity {

    CountryCodePicker ccp;
    boolean numberCheck = false;
    EditText editTextCarrierNumber;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        ccp = (CountryCodePicker) findViewById(R.id.ccp);
        editTextCarrierNumber = (EditText) findViewById(R.id.editText_carrierNumber);
        ccp.registerCarrierNumberEditText(editTextCarrierNumber);
        Log.v("testcreate", "value input =  " + ccp.getFullNumberWithPlus());
        ccp.setPhoneNumberValidityChangeListener(new CountryCodePicker.PhoneNumberValidityChangeListener() {
            @Override
            public void onValidityChanged(boolean isValidNumber) {
                numberCheck = isValidNumber;
                Log.v("testcreate", "check isValidNumber=  " + numberCheck);
                onFormFieldChanged();
            }
        });


    }


    void onFormFieldChanged() {
        if (numberCheck) {
            Toast.makeText(this, "thi test ok", Toast.LENGTH_SHORT).show();
        } else {
            Log.v("testcreate", "value number false");

            //handle other conditions (one or more conditions did not match)
        }
`

**Comment by hbb20** [comment]
Initially it will be an invalid number as edittext won't have valid number
in it. Try typing some valid number in the edit text...

**Comment by zoro238** [comment]
I tried writing a number that did not show me a message to confirm or anything
Is there a specific code that I am sure of at the same time and I am writing that the number is correct?

**Comment by hbb20** [comment]
Is full number support page working in the demo app? ([Code reference](https://github.com/hbb20/CountryCodePickerProject/blob/master/app/src/main/java/in/hbb20/countrycodepickerproject/FullNumberFragment.java#L112))

regarding your last comment's check method:
- you do not need to reregister the edittext if it was done during onCreate
- to use the full number later, you need to store in some variable. standalone `ccp.getFullNumberWithPlus();` is meaningless. Use String `String fullNumberText = ccp.getFullNumberWithPlus();`
- After that dont log entire ccp object. To log the entire phone print `fullNumberText` that we just created.  `Log.v("Current Full Number", fullNumberText);`

**Comment by zoro238** [comment]
ti is ok 
thank you a lots my brother >>
