### ISSUE TITLE
setting up the fullnumber to ccp  without countrycode and +

### ISSUE THREAD

**Issue by pgadhiya-jive** [hbb20/CountryCodePickerProject#263]
I am trying to set ccp.setFullNumber("8013845678") but it's not showing correctly in edit text. there is no country code but it supposes to automatically detect the US because area code 801 is from US. but instead doing that it's showing on 3845678 as a number. do you know how to fix this?

**Comment by hbb20** [comment]
If number does not start with the country code then it is not a fullNumber and does not qualify for this method. Leading "+" is optional  but it expects country code.
