### ISSUE TITLE
Wrong code for Trinidad and Tobago

### ISSUE THREAD

**Issue by MukFlex** [hbb20/CountryCodePickerProject#264]
There is  country code +1 for Trinidad and Tobago in library. When I try to send a sms for account verification by  selecting  Trinidad and Tobago then I get number (+1- 7 digits number). Sms gateway  show a "illegal sender address message".

 I have found 868 or +1868 from below link.
https://countrycode.org/
https://en.wikipedia.org/wiki/Area_code_868
http://www.bsnl.co.in/opencms/export/sites/default/BSNL/services/landline/downloads/isd-countries.pdf

**Comment by hbb20** [comment]
Hello. I checked that.
Trinidad and Tobago is member of NANP. So it's country code is "+1" and area code (digits immediately after country code) is 868.

Library is correctly mapped for 868 as area code of Trinidad and Tobago. See in sample CCP, hint number got 868 area code when Trinidad and Tobago was selected.
![image](https://user-images.githubusercontent.com/4918760/51948004-91fc5d00-23ec-11e9-84fb-0fb8cc98497e.png)

If I misunderstood your question, feel free to comment back. I will reopen the issue and will be happy to help.
