### ISSUE TITLE
Not supporting 6 series Indian mobile numbers

### ISSUE THREAD

**Issue by ram-wavity** [hbb20/CountryCodePickerProject#266]
Our app supports min SDK version 5.1 & API level 22.

**Comment by hbb20** [comment]
what is the version of CCP in your project?

**Comment by ram-wavity** [comment]
I am using 2.1.9 version.

**Comment by hbb20** [comment]
Can you please try the latest version (2.2.3 as of now)? This [issue](https://github.com/hbb20/CountryCodePickerProject/issues/179) might be the same issue.

If version update do not solve the issue, feel free to comment back. I will be happy to help and reopen the issue.
