### ISSUE TITLE
inside number phone full in ccp at view ccp

### ISSUE THREAD

**Issue by zoro238** [hbb20/CountryCodePickerProject#268]
I have a variable with a full phone number and I want it to appear in ccp
How can it be?

**Comment by hbb20** [comment]
Sure, full number (which contains country code) can be loaded in the CCP directly. [Documentation here](https://github.com/hbb20/CountryCodePickerProject/wiki/Full-Number-Support#5-load-full-number) should help you.

**Comment by zoro238** [comment]
I used the code
Sring phonenumber="+317548758";
ccp.setFullNumber(phonenumber);
But the figure does not appear with the state

**Comment by zoro238** [comment]
The country has been changed only without showing the phone number at carrierNumber

**Comment by zoro238** [comment]
The country has been changed only without showing the phone number at carrierNumber

**Comment by hbb20** [comment]
Kindly download the demo app from play store using https://goo.gl/zI2cY2

**Comment by zoro238** [comment]
setup 5
Attach CarrierNumber editText to CCP.
   ccp.registerCarrierNumberEditText(editTextCarrierNumber);

editTextCarrierNumber is edittext and number phone is String 
How do slove problem?

**Comment by hbb20** [comment]
So basically ccp does not know anything about your carrierNumberEditText
until you register it using ccp. registerCarrierNumberEditText().

Once this is done, ccp knows where to put carrier number when you load full
number.

So now you can call ccp.loadFullNumber() and ccp will load country code in
ccp view and carrier number in edittext.

Hope this helped. Otherwise check demo app and it's code in this repo.

**Comment by zoro238** [comment]
porgraaming 

Enable / disable click of ccp.

**Comment by zoro238** [comment]
> So basically ccp does not know anything about your carrierNumberEditText until you register it using ccp. registerCarrierNumberEditText(). Once this is done, ccp knows where to put carrier number when you load full number. So now you can call ccp.loadFullNumber() and ccp will load country code in ccp view and carrier number in edittext. Hope this helped. Otherwise check demo app and it's code in this repo.

that is ok > i am tested it is working 

thank a lots
