### ISSUE TITLE
Enable or clickable on/off

### ISSUE THREAD

**Issue by GeylaniArca** [hbb20/CountryCodePickerProject#27]
I think you understand my problem from title :) Is it possible?

**Comment by hbb20** [comment]
ohh.. I never needed to turn ccp OFF so I did not think about this. I will handle it correctly in next version till then you can place some other view  on top of ccp which consumes click so that click does not reach to ccp.

**Comment by hbb20** [comment]
new v7.1.2 gives you an option to enable / disable click. [Check document](https://github.com/hbb20/CountryCodePickerProject#15-enable--disable-click)
