### ISSUE TITLE
There is a bug, NPE in constructor.

### ISSUE THREAD

**Issue by 1001101** [hbb20/CountryCodePickerProject#278]
![image](https://user-images.githubusercontent.com/12015910/51739885-96afd100-20cd-11e9-945e-a6521d6d8f52.png)

I can't call this constructor programmatically.

**Comment by hbb20** [comment]
Thank you for reporting. We never used it that way so did not face it. We will fix it soon.

**Comment by hbb20** [comment]
It has been fixed in version 2.2.4. If it does not work, please comment back with details.
