### ISSUE TITLE
Country code 358 defaults to Åland Islands, even if it should show Finland

### ISSUE THREAD

**Issue by etanhatch** [hbb20/CountryCodePickerProject#280]
Åland Islands are an autonomous part of Finland, and it's strange that for Finnish users CCPCountry.getCountryForCode(..., "358") returns Åland Islands.

**Comment by hbb20** [comment]
We understand your concern. `getCountryForCode()` go through alphabetically sorted country list and return the first matching country. That's why `Åland Islands` is returned for 358. Due to this problem we encourage to get country from name code instead of phone code.
