### ISSUE TITLE
Please update the following country list

### ISSUE THREAD

**Issue by sanjeevkarat** [hbb20/CountryCodePickerProject#282]
The following issues I mention are from this file.  [https://github.com/hbb20/CountryCodePickerProject/blob/master/ccp/src/main/java/com/hbb20/CCPCountry.java](LINK)
1. Aland Islands is Åland Islands and for flags it is ax and az in arraylist.
2. Change to Curaçao 
3. Viet Nam to Vietnam as it does not recognize from java library when comparing.
4. Change Pitcairn to Pitcairn Islands.
5. Change Macao to Macau
6. Macedonia, The Former Yugoslav Republic Of to Macedonia (FYROM)

P.S All these are compared with countries using following code

```
            Locale locale = new Locale("", code);
            // Get country name for each code.
            String name = locale.getDisplayCountry(Locale.ENGLISH);
```

Overall thanks for this amazing library! :+1:  :1st_place_medal:

**Comment by hbb20** [comment]
Updated in the latest version 2.2.4. If we missed something to change, please comment back with details. Thank you.

**Comment by sanjeevkarat** [comment]
Thanks for the update. Glad most of the items I mentioned is solved. 

Please check the following places:
1. Cote de Ivoire (cu)
2. Laos (la)
3. Kosovo (xk)
4. French Guyana (gf)
