### ISSUE TITLE
Arrow color 

### ISSUE THREAD

**Issue by julietilleul** [hbb20/CountryCodePickerProject#283]
Could you please add method to change just the arrow color? Without changing the content color

**Comment by sirlag** [comment]
If not an arrow color, at least a way to change the arrow drawable could also work

**Comment by hbb20** [comment]
Try to add one drawable to your drawable resource folder with name
"ccp_down_arrow"
this should override existing resource. If that does not work, please let
me know here.

**Comment by sirlag** [comment]
Trying to override the drawable resource doesn't seem to have worked for me. Also tried ccp_ic_arrow_drop_down, and that didn't seem to work either. Thank you so much for the quick response by the way

**Comment by hbb20** [comment]
Just a question, did you add that drawable for all drawable densities?
Anyways I will check that once I reach to my machine.

**Comment by sirlag** [comment]
Just managed to get the image override to work with `ccp_down_arrow` (renaming our AVD directly rather than embedding it inside another root drawable). Only issue now is, ironically, getting the color set

**Comment by hbb20** [comment]
Well, we will include this option in library in future release. Meanwhile, you can use following

```java
        ImageView arrowImage = ccp.findViewById(R.id.imageView_arrow);
        arrowImage.setColorFilter(Color.BLUE, PorterDuff.Mode.SRC_IN); //use your custom color instead of Color.BLUE
```
This code could change arrow color without changing the text color.
![image](https://user-images.githubusercontent.com/4918760/52522777-76e0e700-2c4f-11e9-92f5-6915982a9d6c.png)

If you redraw CCP, you will need to reapply this to set your custom arrow color.

**Comment by sirlag** [comment]
thank you so much

**Comment by hbb20** [comment]
@sirlag , @julietilleul From version 2.2.5, you can use `app:ccp_arrowColor="@color/custom_arrow_color"` property to change arrow color other than content color.

**Comment by carvalho2707** [comment]
@hbb20 The color seems to have some alpha on it by defaut. Can you check it?
