### ISSUE TITLE
How can i change the Dialog title?

### ISSUE THREAD

**Issue by lvaizer** [hbb20/CountryCodePickerProject#286]

**Comment by hbb20** [comment]
Hello @lvaizer. Call `CCPCountry.setDialogTitle("Select a country or region");` once CCP view is loaded. 

Note: Internally, this property is updated every time when the language change is triggered. If you are changing language manually, make sure to call this every time.

**Comment by lvaizer** [comment]
And how can i change it dynamically ?
In my case I'm using more then 1 country picker.

**Comment by hbb20** [comment]
We know this solution is not the best. But you can try following solution. 
In CCP there is a way to override CCP click and also there is a way to open ccpDialog manually.... If we combine both, you will get what you want...

```java
        //bind CCP views
        ccp1 = findViewById(R.id.ccp1);
        ccp2 = findViewById(R.id.ccp2);


        //override CCP1 click, change the title and launch selection dialog for CCP1  
        ccp1.overrideClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                CCPCountry.setDialogTitle("Title for CCP1");
                ccp1.launchCountrySelectionDialog();
            }
        });

        //override CCP2 click, change the title and launch selection dialog for CCP2
        ccp2.overrideClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                CCPCountry.setDialogTitle("Title for CCP2");
                ccp2.launchCountrySelectionDialog();
            }
        });
```

**Comment by lvaizer** [comment]
Ok Thank you!
I saw that solution myself but i thought you have a better way.
Thanks again.

**Comment by hbb20** [comment]
We will integrate a better way in future for sure. Cases like yours help us improve the library. Thanks.
