### ISSUE TITLE
As you type formatting national numbers

### ISSUE THREAD

**Issue by JoshuaBradbury** [hbb20/CountryCodePickerProject#287]
Hello,

I was wondering if support for formatting of national numbers into international numbers was coming soon as in #192 you mention that there were plans to implement it eventually but in #183 you didn't indicate a desire to implement such a feature as this library focuses primarily on international numbers. It still sees the number as valid and removes the leading 0 but it doesn't display it formatted if you have the leading 0 which I think would be a cool feature to have.

Let me know if you feel it is out of scope and I would happily submit a PR in a few weeks.

**Comment by hbb20** [comment]
Yeah, we definitely like to include national number formatting. But it did not become priority. PRs are the heart of any open-source project. If you are interested in that, you are always welcome. One thing we need to figure out is example number. We need to provide some option to show example number in national format too.

**Comment by hbb20** [comment]
Thank you for reporting. We just released new version `v2.3.0` with this. Please check and let us know if it does not work as expected.
