### ISSUE TITLE
Regarding library licence

### ISSUE THREAD

**Issue by satheesh424** [hbb20/CountryCodePickerProject#288]
Is it free of cost  library or paid version?

**Comment by hbb20** [comment]
Hello @satheesh424 , this library is licensed Apache 2.0 and it's free for use. 👍  

![image](https://user-images.githubusercontent.com/4918760/53176012-d2499800-35b2-11e9-997e-77214b7d2987.png)

**Comment by satheesh424** [comment]
Thank you for the confirmation.
