### ISSUE TITLE
How to create countrycodepicker programmatically?

### ISSUE THREAD

**Issue by satheesh424** [hbb20/CountryCodePickerProject#289]
Hi, Is it possible to create Country code picker programmatically. Actually as per my project requirement I need to create country code picker dynamically, So how to create. Please help me on this.

**Comment by hbb20** [comment]
As the CCP is extended from the Relative Layout, you can create CCP just like Relative Layout. 
Almost all properties can be set programmatically as well as XML. For more detail on that, please read [wiki](https://github.com/hbb20/CountryCodePickerProject/wiki).
