### ISSUE TITLE
How to remove setPhoneNumberValidityChangeListener & registerCarrierNumberEditText after we submit form

### ISSUE THREAD

**Issue by Maxwell6635** [hbb20/CountryCodePickerProject#294]
Wish to reset everything back to normal when user already submit the form. But currently when we registerCarrierNumberEditText this already added a text watcher it on validate.

**Comment by hbb20** [comment]
registerCarrierNumberEditText(null) will remove that edittext from ccp. If
you are looking for something else please let me know..

**Comment by Maxwell6635** [comment]
registerCarrierNumberEditText(null) but it return error as below

Process: com.picsus.cus, PID: 8688
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.addTextChangedListener(android.text.TextWatcher)' on a null object reference
        at com.hbb20.CountryCodePicker.updateValidityTextWatcher(CountryCodePicker.java:1115)
        at com.hbb20.CountryCodePicker.setEditText_registeredCarrierNumber(CountryCodePicker.java:1066)
        at com.hbb20.CountryCodePicker.registerCarrierNumberEditText(CountryCodePicker.java:1650)

**Comment by hbb20** [comment]
Oh I see...

**Comment by hbb20** [comment]
I just released new version 2.2.6. Use that and to detach the edittext use ```ccp.deregisterCarrierNumberEditText();```

If that does not work, please let us know here.

**Comment by Maxwell6635** [comment]
Thanks alot 👍 appreciate that.
