### ISSUE TITLE
Change icon flag

### ISSUE THREAD

**Issue by nguyenxuanhoi2903** [hbb20/CountryCodePickerProject#295]
I want to change icon country flag.

**Comment by hbb20** [comment]
Flags are coming from [drawable-nodpi](https://github.com/hbb20/CountryCodePickerProject/tree/master/ccp/src/main/res/drawable-nodpi) resource directory. If you create the same directory under your project's *res* directory and put some flag file by keeping the file name same, your flag file will be picked during build. For example if you want to change flag of Afghanistan, then rename your flag file name to "flag_afghanistan.png" (to match library flag name) and put it under _res/drawable-nodpi_ directory of your project. Let us know the result. Thanks.
