### ISSUE TITLE
Auto Detect Country

### ISSUE THREAD

**Issue by Faiyyaz** [hbb20/CountryCodePickerProject#297]
Hey,

Just a question if i keep ``` app:ccp_autoDetectCountry="true" ``` and i have a tablet which doesn't have sim then what will be the output. Does it will get the right country or it will switch to default country?

**Comment by hbb20** [comment]
CCP uses 3 different strategies to detect a country i.e. SIM, NETWORK, LOCALE. By default, if it fails to detect SIM country, it will look for country using NETWORK and if that fails it will pick locale country.

We know different developers have different needs in terms of order of method usage and fall back strategy when one method fails to detect the country. CCP also provide flexibility to specify the order of these methods.

Detailed explanation is available on [Auto Detect Country Wiki page](https://github.com/hbb20/CountryCodePickerProject/wiki/Auto-detect-country)  . Please let me know if it was helpful. Thanks.

**Comment by Faiyyaz** [comment]
I know this i just meant that suppose i have a tab which works only on wifi so will tbe detection of country will be accurate or it will fail?

**Comment by hbb20** [comment]
Ideally it will detect network based country.

**Comment by Faiyyaz** [comment]
Ok will check it then... Because i think telephonymanager class which is used for network purposes will not work on some tablets as per the android documentation. That's why i m confused about this.
