### ISSUE TITLE
Manifest merger failed with multiple errors

### ISSUE THREAD

**Issue by danielnyerere** [hbb20/CountryCodePickerProject#299]
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.project.smartcard.api.payment"
        minSdkVersion 17
        targetSdkVersion 28
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
    buildToolsVersion '28.0.3'
}

repositories {
    google()
    jcenter()
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation files('libs/core-3.1.0.jar')
    //    implementation files('libs/SmartCardLib.jar')
    //    implementation files('libs/telpo_api.jar')
    implementation files('libs/universal-image-loader-1.9.3.jar')
    implementation 'com.mcxiaoke.volley:library:1.0.19'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support:cardview-v7:28.0.0'
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'org.mod4j.org.apache.commons:lang:2.1.0'
    implementation 'com.google.android.gms:play-services-maps:16.1.0'
    implementation 'com.squareup.retrofit2:retrofit:2.5.0'
    implementation 'com.squareup.retrofit2:converter-scalars:2.5.0'
    implementation 'com.google.firebase:firebase-core:16.0.8'
    implementation 'com.google.firebase:firebase-database:16.0.1'
    implementation 'com.google.firebase:firebase-auth:16.2.0'
//    implementation 'com.redmadrobot:inputmask:4.0.0'
    implementation 'com.hbb20:ccp:2.2.6'
//    implementation("com.hbb20:ccp:2.2.6",{
//               exclude group: 'com.android.support'
//            })
//    implementation 'uk.co.chrisjenx:calligraphy:2.3.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

apply plugin: 'com.google.gms.google-services'
`

**I got the error**

 `org.gradle.execution.MultipleBuildFailures: Build completed with 1 failures.
	at org.gradle.initialization.DefaultGradleLauncher$ExecuteTasks.run(DefaultGradleLauncher.java:358)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
	... 34 more` 

**Any solution?**

**Comment by hbb20** [comment]
Sorry to hear about that but the posted trace does not give much information about what went wrong. As mentioned in this trace (before your edit), please get the error log with debug and post here.

Just one question
```androidTestImplementation 'com.android.support.test🏃1.0.2'``` is the actual line in your code?

**Comment by dleonett** [comment]
Hello, I'm getting some errors and it seems to be related to what @danielnyerere mentioned:
```
Attribute application@allowBackup value=(false) from AndroidManifest.xml:14:9-36
is also present at [com.hbb20:ccp:2.2.9] AndroidManifest.xml:12:9-35 value=(true).
Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:12:5-82:19 to override.
```
```
Attribute application@supportsRtl value=(false) from AndroidManifest.xml:20:9-36
is also present at [com.hbb20:ccp:2.2.9] AndroidManifest.xml:14:9-35 value=(true).
Suggestion: add 'tools:replace="android:supportsRtl"' to <application> element at AndroidManifest.xml:12:5-82:19 to override.
```

**Comment by hbb20** [comment]
@dleonett, thank you for sharing your finding. I will remove "allowBackup" from next release as CCP should not be declaring that. It's there because it's was part of initial project by AS and never changed. After little more evaluation, we might do the same  for supportRtl to let app decide and declare. 

Meanwhile, @danielnyerere please let us know if the solution by overriding (from @dleonett) worked for you. Thanks.
