### ISSUE TITLE
Set Text Size

### ISSUE THREAD

**Issue by Rajakh** [hbb20/CountryCodePickerProject#3]
I have a register form in which the EditText fields have TextSize of 22sp. But the CountryCodePicker TextSize is 18sp.
How do I set the CountryCodePicker TextSize to 22sp?

Thanks

**Comment by hbb20** [comment]
@Rajakh, I have prepared next version with options to modify the size of text and the size downArrow. I will upload the new version within one day.

**Comment by hbb20** [comment]
@Rajakh , newer version 1.2 ( not 0.1.2) is published. Read [document](https://github.com/hbb20/CountryCodePickerProject#6-custom-textsize) to know how to modify textSize and arrowSize (optional).

**Comment by Rajakh** [comment]
Thanks for the new options.
