### ISSUE TITLE
Country nameCode are different if from XML or from code

### ISSUE THREAD

**Issue by CmoaToto** [hbb20/CountryCodePickerProject#307]
Hello,

Is there any reason why the country nameCode are in lowerCase when coming from the LibraryMasterCountriesEnglish code:

https://github.com/hbb20/CountryCodePickerProject/blob/master/ccp/src/main/java/com/hbb20/CCPCountry.java#L1412
```java
    public static List<CCPCountry> getLibraryMasterCountriesEnglish() {
        List<CCPCountry> countries = new ArrayList<>();
        countries.add(new CCPCountry("ad", "376", "Andorra", DEFAULT_FLAG_RES));
        // ...
    }
```

and in uppercase when coming from XML:

https://github.com/hbb20/CountryCodePickerProject/blob/master/ccp/src/main/java/com/hbb20/CCPCountry.java#L92
```java
    static void loadDataFromXML(Context context, CountryCodePicker.Language language) {
        // ...
                        case XmlPullParser.END_TAG:
                        if (name.equals("country")) {
                            CCPCountry ccpCountry = new CCPCountry();
                            ccpCountry.setNameCode(xmlPullParser.getAttributeValue(null, "name_code").toUpperCase());
        //...
    }
```

This leads to inconsistency, especially in UnitTest when there is no ressource to use to test.
Am I missing something?

**Comment by hbb20** [comment]
Thank you so much for catching it and reporting. There is truly no reason for that. I missed it. I will make it consistent in next version. Please allow some time.

**Comment by fuckinjen** [comment]
Yeah it means stay the fuck out of my information nigger

**Comment by CmoaToto** [comment]
Hey @hbb20 , I had a few minutes so I leave you a PR to fix this issue. :)

**Comment by CmoaToto** [comment]
Merged -> Fixed
