### ISSUE TITLE
Country currency 

### ISSUE THREAD

**Issue by Amitdygon** [hbb20/CountryCodePickerProject#309]
its a awsoom .can u pls add the all country currency

**Comment by hbb20** [comment]
Thank you for feedback and valuable suggestion. A while ago we discussed about this possible extension in our team. It seemed very practical as library has strong foundation for that. But doing so, we might loose our focus. So we decided to implement a separate library in future for this. Unfortunately, we don't have one right now. And fortunately, rich android community has many alternative libraries available.
