### ISSUE TITLE
Country not present

### ISSUE THREAD

**Issue by dondragon2** [hbb20/CountryCodePickerProject#31]
How do I add a country to the master list? My country along with a few others are not listed and I want to add them to my master list.

**Comment by dnwilson** [comment]
+1 having the same issue

**Comment by hbb20** [comment]
- Clone the library code
- [Country.java](https://github.com/hbb20/CountryCodePickerProject/blob/master/ccp/src/main/java/com/hbb20/Country.java) file is handling countries list.
- Add your country in _getLibraryMasterCountriesEnglish();_ in alphabetical order of country name.
- Now add your country to same position (as alphabetical order in above step) for each supported  language with correct translation.
- Add a flag file to res/drawable(s) 
- add entry for flag in getFlagResID(Country country)

**Comment by dnwilson** [comment]
@hbb20 https://github.com/hbb20/CountryCodePickerProject/pull/32
