### ISSUE TITLE
keep.xml rules issues

### ISSUE THREAD

**Issue by freszu** [hbb20/CountryCodePickerProject#314]
While using CCP library i ran into following issue related to current keep.xm config
- When any consuming app creates it's own keep.xml file the one from library will be overridden this is actually mistake that is quite easy to make when following official guides which suggest such name : https://developer.android.com/studio/build/shrink-code and caused some crashes for me on some of the languages - the keep.xml could be renamed.
- The rules included in the keep.xml include pretty much every raw file in consumer app. So once this library is included all raw files are kept (reproduced in sample: https://github.com/freszu/CCPKeepBug/) , so the rule should be narrowed down. Maybe it's a good idea to start each translation file with some prefix as a quick win.

Results from apk analyzer: 
Without code picker dependency:
![Screenshot 2019-05-28 at 16 20 00](https://user-images.githubusercontent.com/12448300/58485762-f0e89d80-8164-11e9-882c-c308b2caa8ac.png)
With code picker dependency:
![Screenshot 2019-05-28 at 16 20 58](https://user-images.githubusercontent.com/12448300/58485767-f34af780-8164-11e9-8a50-dd0af75d949d.png)

**Comment by Stackustack** [comment]
👍

**Comment by hbb20** [comment]
Thank you for reporting. We just released a new version `v2.3.0` with the suggested fixes. Please check and let us know if it does not work as expected.
