### ISSUE TITLE
Suggested to put all of the String into the string.xml file

### ISSUE THREAD

**Issue by kenneth2008** [hbb20/CountryCodePickerProject#34]
To prevent all of the content retrieved into the memory. Thank you.

**Comment by hbb20** [comment]
@kenneth2008, thank you for taking genuine interest in library development and progress. Can you please elaborate your point for this issue?

**Comment by kenneth2008** [comment]
As an example, getLibraryMasterCountriesEnglish() is not a good idea.
When i was using English as my language, all of the other language has been copied into memory because of in the same classes. (Not Sure)

Besides, if we need to add new language support. We have to add getLibraryMasterCountriesXXXXXXX every time. if we use the localization system of android, we save many line of codes and workload.

Honestly, for now, the effect is not big.

**Comment by hbb20** [comment]
Yeah, for now it is a downside of this library.  Probably we will need to handle many things along with Localization to optimize memory usage. But yeah, you pointed a correct issue. I'm figuring out some better way to handle this and will implement it soon.

**Comment by hbb20** [comment]
Finally it's done. Now each language had independent XML file with list of countries. Only one list will be loaded in to memory as per requirement.
