### ISSUE TITLE
When we add dependencie this error is occur

### ISSUE THREAD

**Issue by UmarAlyas0078** [hbb20/CountryCodePickerProject#345]
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.1.0] AndroidManifest.xml:24:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:8:5-22:19 to override.

**Comment by hbb20** [comment]
Thank you for reporting. #299 is of similar nature. As suggested in your error log and on the [thread](https://github.com/hbb20/CountryCodePickerProject/issues/299#issuecomment-491561180), it should be gone if you add `tools:replace="android:appComponentFactory"` to your app manifest file. Just a quick question, are you using AndroidX? If that does not work please post back here, we will open the issue.

**Comment by UmarAlyas0078** [comment]
Thanks it's resolve 👍
