### ISSUE TITLE
Auto formate number

### ISSUE THREAD

**Issue by UmarAlyas0078** [hbb20/CountryCodePickerProject#347]
if I select the Pakistan county in the list . it's not change to autofaromate number in the editText
and the other on is not properly work this method ccpp.isValidFullNumber(); please check it out and give me the solution Thanks

please look at my XML Code
<com.hbb20.CountryCodePicker
        android:id="@+id/ccp"
        android:layout_width="99dp"
        android:layout_height="49dp"
        android:layout_marginStart="8dp"
        android:layout_marginTop="8dp"
        android:layout_marginEnd="8dp"
        android:layout_marginBottom="8dp"
        app:ccpDialog_showCloseIcon="true"
        app:ccpDialog_showFlag="true"
        app:ccpDialog_showTitle="false"
        app:ccp_arrowSize="20dp"
        app:ccp_autoDetectCountry="true"
        app:ccp_autoDetectLanguage="true"
        app:ccp_autoFormatNumber="true"
        app:ccp_clickable="true"
        app:ccp_countryAutoDetectionPref="SIM_ONLY"
        app:ccp_hintExampleNumber="true"
        app:ccp_hintExampleNumberType="FIXED_LINE"
        app:ccp_selectionMemoryTag="signupCCP"
        app:ccp_showArrow="true"
        app:ccp_showFlag="false"
        app:ccp_showFullName="true"
        app:ccp_showNameCode="false"
        app:ccp_showPhoneCode="true"
        app:ccp_textGravity="RIGHT"
        app:ccp_textSize="15sp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.081"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintVertical_bias="0.199">

    </com.hbb20.CountryCodePicker>

    <EditText
        android:id="@+id/editText_carrierNumber"
        android:layout_width="228dp"
        android:layout_height="56dp"
        android:layout_marginStart="8dp"
        android:layout_marginTop="8dp"
        android:layout_marginEnd="8dp"
        android:layout_marginBottom="8dp"
        android:hint="phone"
        android:inputType="phone"
        android:singleLine="true"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.222"
        app:layout_constraintStart_toEndOf="@+id/ccp"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintVertical_bias="0.201" />

java code

 ccpp = (CountryCodePicker) findViewById(R.id.ccp);
        edittextNumber = (EditText) findViewById(R.id.editText_carrierNumber);
        login = (Button) findViewById(R.id.loginbtn);
        ccpp.registerCarrierNumberEditText(edittextNumber);
        ccpp.isValidFullNumber();
        ccpp.getFormattedFullNumber();

        ccpp.setOnCountryChangeListener(new CountryCodePicker.OnCountryChangeListener() {
            @Override
            public void onCountrySelected() {
                Toast.makeText(MainActivity.this, "Updated " + ccpp.getSelectedCountryName(), Toast.LENGTH_SHORT).show();
            }
        });

    }

**Comment by hbb20** [comment]
Sorry to hear that. Are you entering a valid phone number before calling
getFormattedFullNumber()?

**Comment by UmarAlyas0078** [comment]
if we don't use this method just with the help of this method ccpp.isValidFullNumber();
can we check the valid number ?

**Comment by UmarAlyas0078** [comment]
and the other one if i change the pk county in the listView the autoformate auto fill in the editText is not work please look have a look at this issue

**Comment by hbb20** [comment]
Please send me a valid number that you are testing. I will check once I get
back home tonight.

**Comment by UmarAlyas0078** [comment]
![Annotation 2019-09-18 085944](https://user-images.githubusercontent.com/48212129/65164973-c1e78780-d9f2-11e9-9487-578505d5a714.png)

**Comment by UmarAlyas0078** [comment]
if i change this country it's show me like this in editText

**Comment by hbb20** [comment]
I tried the same config of your ccp and tested on the demo app:
## Invalid / incomplete number
![image](https://user-images.githubusercontent.com/4918760/65197111-0a2c9700-da3f-11e9-82a0-a92edec36c9b.png)

## Valid number
![image](https://user-images.githubusercontent.com/4918760/65196874-43b0d280-da3e-11e9-8173-9c88603fc0d0.png)


- Number was formatted (edit text has that)
- Validity change is working (status below the ccp says "Valid Number")
- getFormattedFullNumber returned formatted number (at the bottom of the screen shot)

So ideally this configuration should work. What is the library version that you are using?

**Comment by UmarAlyas0078** [comment]
implementation 'com.hbb20:ccp:2.3.2'
this library version i'm using 
Biscally when I select the Pakistan country it does not show me like this "+92- ........."
it shows me like this or select another country . it does not show me invalid number 

Before

![before](https://user-images.githubusercontent.com/48212129/65241196-d6ca2680-da97-11e9-8b34-37fe070e4dc1.png)

**Comment by UmarAlyas0078** [comment]
After
![after](https://user-images.githubusercontent.com/48212129/65241263-f4978b80-da97-11e9-99bc-a776f176467e.png)

And this is my MainActivity Code 

![ppc](https://user-images.githubusercontent.com/48212129/65241332-23156680-da98-11e9-9bb5-4fbe6c0fefae.png)

**Comment by hbb20** [comment]
Oh I see...
I thing following should clarify your doubts:
1. Why hint number does not include +92
- Since country picker already shows the code +92, edittext is only meant for carrier number (without country code) that's why it does not include +92
2. Why does not show me invalid number?
- The screenshots I posted had custom implementation to show "valid" or "invalid" number using `setPhoneNumberValidityChangeListener`. [Code Reference](https://github.com/hbb20/CountryCodePickerProject/blob/master/app/src/main/java/in/hbb20/countrycodepickerproject/FullNumberFragment.kt#L79)
3. `ccpp.isValidFullNumber` returns a boolean if edittext has valid phone number is entered in at the time. It does not show "Valid" or "Invalid" status in any view automatically...

**Comment by UmarAlyas0078** [comment]
yes some confusion is clear about the country code :)

1) When i run this code my app is crash 

![check](https://user-images.githubusercontent.com/48212129/65281115-a8276c80-dae6-11e9-950a-0b2015d6ae63.png)


2 ) please also give me the suggestion of using the method of .isValidFullNumber() , that were I need to put it in my code

**Comment by hbb20** [comment]
1. Most probably app is crashing because msg variable is not bounded with any view. You might wanna call `msg = findViewById(R.id.your_msg_view_id)` before setting validity change listener.
2. Purpose of `isValidFullNumber()` is to do onetime check of current state.
For example,
```java
void onSignupButtonClicked(){
      Boolean isValidForm = true;
     
     if(isEmailBlank() || isInvalidEmail()){
         showEmailError();
         isValidForm = false;
    }

    if(isPasswordBlank())){
         showPasswordError();
         isValidForm = false;
    }

    if(!ccp.isValidFullNumber()){
         showPhoneError();
         isValidForm = false;
   }

   if(isValidForm){
        signup()
   }
}
```

Was it helpful?

**Comment by UmarAlyas0078** [comment]
Thanks now it's not crashing .It's working good :)
1)Please Review my main Activity java code and check it where i am going missing something 
   now it's showing me valid or invalid number . when i enter some random number it show me valid number 

Code

package com.example.ccp;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import com.hbb20.CountryCodePicker;


public class MainActivity extends AppCompatActivity {

    CountryCodePicker ccpp;
    EditText edittextNumber;
    TextView msg;
    Button login;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        ccpp = (CountryCodePicker) findViewById(R.id.ccp);
        msg = (TextView) findViewById(R.id.show_message);
        login = (Button) findViewById(R.id.loginBtn);
        edittextNumber = (EditText) findViewById(R.id.editText_carrierNumber);
        ccpp.registerCarrierNumberEditText(edittextNumber);

        msg.setVisibility(View.INVISIBLE);
        ccpp.getFullNumber();

        ccpp.getFormattedFullNumber();
        ccpp.getFullNumberWithPlus();

        ccpp.setPhoneNumberValidityChangeListener(new CountryCodePicker.PhoneNumberValidityChangeListener() {
            @Override
            public void onValidityChanged(boolean isValidNumber) {
                if (isValidNumber)
                {
                    msg.setText("Valid Number");
                    msg.setVisibility(View.VISIBLE); //here we are setting the visiblity to show our message if it's right
                }
                else {
                    msg.setText("In Valid");  //this message will be show if the it's invalid number
                }

            }
        });

        login.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                Boolean isValidForm = true;

                if (ccpp.isValidFullNumber())
                {
                    Intent intent = new Intent(MainActivity.this,Main2Activity.class);
                    startActivity(intent);
                }
                if (!ccpp.isValidFullNumber())
                {
                    Toast.makeText(MainActivity.this,"Invalid Number", Toast.LENGTH_LONG );
                    isValidForm = false;
                }
            }
        });

        ccpp.setOnCountryChangeListener(new CountryCodePicker.OnCountryChangeListener() {
            @Override
            public void onCountrySelected() {
                Toast.makeText(MainActivity.this, "Updated " + ccpp.getSelectedCountryName(), Toast.LENGTH_SHORT).show();
            }
        });

    }
}

**Comment by UmarAlyas0078** [comment]
![valid](https://user-images.githubusercontent.com/48212129/65445271-ac090680-dde6-11e9-9f0c-76d8836f0d96.png)

And This is my outPut

**Comment by hbb20** [comment]
CCP uses google phone lib underneath to validate the phone number. If random number passes all checks of google phone lib then it will be detected as valid number. Hope that answers your query. If there is some other query, feel free to open a new issue.
