### ISSUE TITLE
Wrong country code

### ISSUE THREAD

**Issue by divyachaturvedi16** [hbb20/CountryCodePickerProject#348]
Hi 
Some country have country code 1.Please update country code.

**Comment by hbb20** [comment]
It will be helpful if you can give some example. There are multiple countries which have +1 as country code (they have different area code though)

**Comment by divyachaturvedi16** [comment]
Yeah u r right then how we can pick region code also in that spinner.

**Comment by hbb20** [comment]
With spinner, you can not pick area code. But it will auto switch country based on area code in edit text (if you are using full number support). 

For example, 
Once you setup everything for [Full Number Support](https://github.com/hbb20/CountryCodePickerProject/wiki/Full-Number-Support)
Now say you have selected US(+1) and start typing 671XXXXXXX (this is "Guam(+1)" phone number) in Carrier edittext. As soon as you type "671", ccp will detect that this area code is of Guam and not US, it automatically correct country from "US(+1)"to "Guam(+1)"

**Comment by dijashub** [comment]
@hbb20  How do i show countries with +1 will full code in picker +1 268 ?

For example it shows +1 for ANTIGUA_AND_BARBUDA_AREA_CODES but it should show as +1 268?

**Comment by hbb20** [comment]
Unfortunately that's not supported by the library. Although, it will auto
detect country based on entered area code... For example, if you select any
country with 1 say US and start typing 268 in your CCP registered edittext,
country will be changed to correct country.

**Comment by dijashub** [comment]
@hbb20  
Okay.. Help me with method that can get full code after selection of +1 codes.. I may be missing something.

ccp.fullNumber still giive me +1 instead of +1 268

**Comment by hbb20** [comment]
Full number = Country  Code + Carrier Number (in editText). So full number will only make sense if you have registered your edit text with ccp. Please read more in wiki [here](https://github.com/hbb20/CountryCodePickerProject/wiki/Full-Number-Support).
