### ISSUE TITLE
HUAWEI AppGallery

### ISSUE THREAD

**Issue by niktses** [hbb20/CountryCodePickerProject#353]
Uploading to HUAWEI AppGallery is rejected because of string "Select a country". They say it needs to be changed to "Select a country / region", obviously because Hong Kong is included in the list. I don't know if they check all languages but I believe it will need to be changed on all supported languages.

**Comment by hbb20** [comment]
Sorry to hear that..
Can you try [Custom title feature](https://github.com/hbb20/CountryCodePickerProject/wiki/Custom-Dialog-Title--%7C-Search-Hint-%7C-Empty-result-ACK) and provide what they want..?

**Comment by niktses** [comment]
ok that helped, thanks
