### ISSUE TITLE
How to update country flag and phone code for any country?

### ISSUE THREAD

**Issue by rohantalukder** [hbb20/CountryCodePickerProject#359]
I want to change Cayman islands phone code and add a flag. How to do it? I have added this library in build Gradle I don't want to add the whole project as a module.

**Comment by hbb20** [comment]
Can you please tell me what area code you want to put? I just checked flag and country code, they are accurate. Did I miss anything?

**Comment by rohantalukder** [comment]
I already mentioned the country name. It is Cayman island's phone code that is wrong and the country flag is missing. Can I update it by calling any methods in your library?

**Comment by hbb20** [comment]
In the latest version of CCP, we already have flag of Cayman Island
![image](https://user-images.githubusercontent.com/4918760/69485157-c10b1180-0df8-11ea-811e-479b21a46a73.png)

and country code is +1:
![image](https://user-images.githubusercontent.com/4918760/69485160-da13c280-0df8-11ea-85af-7d642384078e.png)

In addition to that, we have added it's area code in group of +1 coutnries:
![image](https://user-images.githubusercontent.com/4918760/69485176-27902f80-0df9-11ea-943a-9ce317b4d489.png)


In order to use custom phone code and flag, you will have to override XML file (ccp_<language>.xml) and flag file (ccp/src/main/res/drawable-nodpi/flag_cayman_islands.png) in your project.

**Comment by rohantalukder** [comment]
![Screenshot_20191125-124932_AirCloudProPilot](https://user-images.githubusercontent.com/11829221/69491021-a8166500-0eb9-11ea-9f76-3fc4b7e3a298.jpg)

Ok in latest build Cayman island flag is there. 
1.But I want to change phone code from +1 to +1345 after a search in the dialog (just like the attached picture )and also in country picker field.
2. Also how to hide short form (KY) beside the country name for all countries when inflating?

**Comment by hbb20** [comment]
1. You will need to override XML file if you want to change from +1 to +1345... The only reason why CCP does not keep it +1345 is +1 is country code and 345 is area code.

2. You can do this easily: just add `app:ccp_showNameCode="false"` and it should be gone..

**Comment by rohantalukder** [comment]
Actually I have added the library in build.gradle section not as a project. That's why if there was any common method to update country data I would call that method and update the country list. But there is not any.

**Comment by rohantalukder** [comment]
![Screenshot_20191125-124932_AirCloudProPilot (1)](https://user-images.githubusercontent.com/11829221/69491961-71931700-0ec6-11ea-8a16-4ec921be1b0a.jpg)
And also showNamecode attribute works for country picker view but I wanted to hide the short form in dialog.see the picture please.

**Comment by hbb20** [comment]
Use `app:ccpDialog_showNameCode="false"` to hide that namecode.

**Comment by rohantalukder** [comment]
Thanks yes it is there I missed that.
But I can't update country info like phone code or flag, Please in the next version keep there a scope where I can update country info like phone code and others. (i am talking about implementing it as a library in build gradle, not as project library where I can edit code) 
Thanks again.

**Comment by lindersonk** [comment]
"Use app:ccpDialog_showNameCode="false" to hide that namecode." is still showing code on mine

**Comment by hbb20** [comment]
Did you add 
`app:ccp_showNameCode="false"` in addition to `app:ccpDialog_showNameCode="false"` as well?

**Comment by rohantalukder** [comment]
yes. All are good now. Thanks.
    On Wednesday, December 18, 2019, 03:55:06 AM GMT+6, Harsh B. Bhakta <notifications@github.com> wrote:  
 
 
Did you add
app:ccp_showNameCode="false" in addition to app:ccpDialog_showNameCode="false" as well?
