### ISSUE TITLE
How to change spinner or arrowcolor ?

### ISSUE THREAD

**Issue by poojashah23996** [hbb20/CountryCodePickerProject#360]

**Comment by poojashah23996** [comment]
I somehow change color of the text of selected country name but with country name there's spinner arrow which I am unable to set color to white because there's no such getImageViewArrow method through which I can update color ...

**Comment by hbb20** [comment]
Can you please try `app:ccp_contentColor="@color/custom_color"`? Please post back with result.

**Comment by poojashah23996** [comment]
Yes..it worked....Thanks a lot!
