### ISSUE TITLE
Error inflating class com.hbb20.CountryCodePicker in android 10

### ISSUE THREAD

**Issue by EleshBaraiya** [hbb20/CountryCodePickerProject#362]
App crash in android 10

**Comment by hbb20** [comment]
Can you please provide detailed crash report? Unable find issue based on title.

**Comment by AlexeyGodyaev** [comment]
Android 10 use sdk 29 
https://developer.samsung.com/remote-test-lab

> Можете ли вы предоставить подробный отчет о сбое? Невозможно найти проблему, основанную на заголовке.

**Comment by AlexeyGodyaev** [comment]
not sure, but it seems the problem is in the layout

**Comment by hbb20** [comment]
Thank you for reporting. It seems like this issue is similar to #403. It will be helpful if we continue discussion on a single thread. Further discussion can be found on #403.
