### ISSUE TITLE
Hanna

### ISSUE THREAD

**Issue by chanaso** [hbb20/CountryCodePickerProject#364]
Hi,

I've implemented the library to my program, and the dialog does not show up.
In the matter of fact, nothing shows up.
Any idea what could have gone wrong?

Thanks a lot!

**Comment by hbb20** [comment]
Can you post your code? XML and Java/Kotlin related to CCP?

**Comment by hbb20** [comment]
Thank you for your email and glad to know that it's working for you now 👍
