### ISSUE TITLE
Inclusion of fast scroll or scroll

### ISSUE THREAD

**Issue by HungerNHeart** [hbb20/CountryCodePickerProject#37]
Hey there,

Thanks for the widget it doing great. I have a suggestion that will improve the user experience more convenient by including fast scroll like contacts page in android stock dialer.

Thanks.
Guru Karthi

**Comment by hbb20** [comment]
Hey @HungerNHeart, it was really a good suggestion. 
Fast Scroller has been integrated in v1.8. Hopefully this will work for you.

**Comment by HungerNHeart** [comment]
Great! Thanks for the response and including the suggestion.
