### ISSUE TITLE
getFullNumberWithPlus() returns only prefix with country code when entering single digit

### ISSUE THREAD

**Issue by gorlogorius** [hbb20/CountryCodePickerProject#370]
Issue: getFullNumberWithPlus() only returns prefix and country code (for example, +91 or +7) when only single digit is typed into editTextCarrierNumber.

 Same problem happens when you clear editText until only one digit is left.

It seems that NumberParseException (error type: NOT_A_NUMBER. The string supplied did not seem to be a phone number.) happens in this class.

Potential inconvenience: I want to keep entered value for further use, even if it's just prefix+countryCode+one single value.

**Comment by hbb20** [comment]
Thanks for reporting.

**Comment by hbb20** [comment]
Please try v2.3.7. It should have the fix.
![image](https://user-images.githubusercontent.com/4918760/73038117-803a7380-3e0e-11ea-9953-19eaa35b29e7.png)
