### ISSUE TITLE
Problem with layout

### ISSUE THREAD

**Issue by mohsen-m78** [hbb20/CountryCodePickerProject#386]
Hello. the country code picker from version 2.0.0 and above won't show in the layout...
I'm using version 2.3.8 in my layout and in the layout I see NOTHING...!!!!!

my code:
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <com.hbb20.CountryCodePicker
        android:id="@+id/ccp"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:ccp_defaultNameCode="US"/>

</RelativeLayout>

and the interesting point is that the code above works perfectly fine for version 2.1.9.....
I don't know what's so special about this particular version.....can anyone help?
thanks in advance.......

**Comment by hbb20** [comment]
That’s interesting... when you say you see nothing, is it in Android Studio
layout preview or in app when your run? Will check changes in 2.1.9
tomorrow morning.

**Comment by mohsen-m78** [comment]
I meant in the layout preview, but it's working fine on the device........
The real problem is that although it appears on the device and works fine there, but because I can't see it on the layout preview I can't adjust the layout... 
I mean the size of ccp is zero and it's not adjustable to wrap_content...

**Comment by hbb20** [comment]
Does that happen in a new layout file where ccp is the only view? Can you
send me layout file, I would like to check it on my Computer.

**Comment by mohsen-m78** [comment]
yes...
if you just quickly review this video https://www.youtube.com/watch?v=YIdxPbuqQog 
you can see that in the video the designer is designing and the ccp won't show itself and its sizes until the designer gives it a width and hight....and as I said before he can't set the width and height to wrap_content....

this is my layout file : 
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.hbb20.CountryCodePicker
        android:layout_centerInParent="true"
        android:layout_width="200dp"
        android:layout_height="100dp" />

</RelativeLayout>

so in both cases (the youtube video and me), the layout is not showing the ccp...
i don't think that happens just because it's the only view in the layout

and I found a new problem
these two methods : 
getFullNumber()
getFullNumberWithPlus()

crash the application on version 2.3.8 but they work fine on 2.3.1 and 2.1.9
thank you for your time

**Comment by mohsen-m78** [comment]
yes...
if you just quickly review this video https://www.youtube.com/watch?v=YIdxPbuqQog 
you can see that in the video the designer is designing and the ccp won't show itself and its sizes until the designer gives it a width and hight....and as I said before he can't set the width and height to wrap_content....

this is my layout file : 

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.hbb20.CountryCodePicker
        android:layout_centerInParent="true"
        android:layout_width="200dp"
        android:layout_height="100dp" />

</RelativeLayout>
so in both cases (the youtube video and me), the layout is not showing the ccp...
i don't think that happens just because it's the only view in the layout

and I found a new problem
these two methods : 
getFullNumber()
getFullNumberWithPlus()

crash the application on version 2.3.8 but they work fine on 2.3.1 and 2.1.9
thank you for your time

**Comment by hbb20** [comment]
Hey,

thanks for your response.

I tried this on my trial project and was able to reproduce it. When I
switched the version. It showed attribute error but worked well after
"Clean Project" and "Rebuild". Please try that. If that doesn't work, click
on
error icon on layout preview:
[image: Screen Shot 2020-04-11 at 14.39.43.png]

and that will open the error window. You may find option of "Show
Exception". Click that and send me the screenshot.

getFullNumber() issue:
I saw that in video, they are using getFullNumber() without registering
phonenumber edit text.
If you need to get selected phone code then just use `
getSelectedCountryCode()`.
Read this wiki documentation
<https://github.com/hbb20/CountryCodePickerProject/wiki/Full-Number-Support>for
more detail about how use full number support with getFullNumber().

Thanks,
Harsh Bhakt

**Comment by hbb20** [comment]
Feel free to comment here if you still face this issue.
