### ISSUE TITLE
Is there any way to hide country name or country code or both with showing flags?

### ISSUE THREAD

**Issue by codebyme111** [hbb20/CountryCodePickerProject#388]
My country picker:
It's showing country flag, country name code: US, and country code: +1

I want like this:
country flag +1 or only country flag

Is there any attribute for this customized look?

**Comment by hbb20** [comment]
If you add 
```
app:ccp_showPhoneCode="false" 
app:ccp_showNameCode="false"
```

you should see flag only.

See more properties [here](https://github.com/hbb20/CountryCodePickerProject/wiki/XML-Properties).

**Comment by hbb20** [comment]
Let me know if that does not work. I will reopen the issue.
