### ISSUE TITLE
How to change Background color or text color in the List Country Code layout

### ISSUE THREAD

**Issue by yongkimayongga** [hbb20/CountryCodePickerProject#39]
Hello, how i can change the background color or text color when the country code layout is showing?
right now, the background and text color look similar and i want to change their color.

![screen shot 2017-02-24 at 12 56 17 pm](https://cloud.githubusercontent.com/assets/25190275/23292814/da748d2e-fa94-11e6-9ae8-2b81302a9bce.png)

Thanks

**Comment by kenneth2008** [comment]
It seems that affected by your application or activity them style.

2017-02-24 14:26 GMT+08:00 yongkimayongga <notifications@github.com>:

**Comment by yongkimayongga** [comment]
thanks, you're right 👍
