### ISSUE TITLE
Typo on Wiki

### ISSUE THREAD

**Issue by danielgomezrico** [hbb20/CountryCodePickerProject#391]
![image](https://user-images.githubusercontent.com/76348/80731264-4a252380-8ad0-11ea-82f7-d3f1b3fa0633.png)

The parameter name is bad its ccp_rememberLastSelection but should be `ccp_rememeberLastSelection`. (error -> `rememeber`)

**Comment by hbb20** [comment]
Thanks for reporting. I just corrected.
