### ISSUE TITLE
Default country code ignores duplicate codes

### ISSUE THREAD

**Issue by willrichman** [hbb20/CountryCodePickerProject#4]
If a user attempts to set a country code that applies to more than one country, only the first country in countries.xml will be selected as the default. As a result, there is no way to set US +1 as the default country, as the `getCountryForCode` loop will find Canada first, and set that as the default.

**Comment by hbb20** [comment]
Thank you, @willrichman for reporting.That's a problem, definitely. I'll be implementing some way to set manual preferences for countries with same country code. But it may take some time. Once it's fixed, I'll notify on the issue.

**Comment by hbb20** [comment]
Hey, the problem has been solved in v1.4 of the library. 
- Please look at new options for [setting default country](https://github.com/hbb20/CountryCodePickerProject#1-default-country).
- Moreover, now country preference can be set as well. See [document.](https://github.com/hbb20/CountryCodePickerProject#3-country-preference)
