### ISSUE TITLE
not able to change text color or font 

### ISSUE THREAD

**Issue by MahmoudMabrok** [hbb20/CountryCodePickerProject#401]
![Screen Shot 2020-05-13 at 4 40 12 PM](https://user-images.githubusercontent.com/13488900/81826817-72813900-9538-11ea-8502-65e29dcf5989.png)

I want to use same text color and font that exist in phone to be used at country

**Comment by hbb20** [comment]
Did you try by changing content color as mentioned on [wiki](https://github.com/hbb20/CountryCodePickerProject/wiki/CCP-Theme-Customization)?

**Comment by Jorikua** [comment]
I have the same problem. But I load the font via `ResourcesCompat.getFont(context, resId)`. Will it work?

**Comment by MahmoudMabrok** [comment]
Thanks, it worked @hbb20
