### ISSUE TITLE
How to remove "ripple effect"

### ISSUE THREAD

**Issue by skfaisal93** [hbb20/CountryCodePickerProject#407]
I want to know how can I disable the **ripple effect** when clicking on the country code drop down.

**Comment by hbb20** [comment]
I am trying a solution for a crash. Not sure if this fixes that issue but one of my effort is to remove ripple. Can you try : `v2.4.1-alpha3`?

**Comment by hbb20** [comment]
Please try `v2.4.1`. If you still face this issue, then feel free to comment back.
