### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by tmct** [hbb20/CountryCodePickerProject#41]
Hi, please could you add a licence (e.g. MIT, Apache) to this project, so that we know how it can be used? Thanks.

http://choosealicense.com

**Comment by hbb20** [comment]
Hello Tom McTiernan, I already have added apache license. You can find it on [read me](https://github.com/hbb20/CountryCodePickerProject#license).

**Comment by tmct** [comment]
Oh I see, yes! It just wasn't being picked up by GitHub's [licensee](https://github.com/blog/2252-license-now-displayed-on-repository-overview) system because it's in the Readme.

Thanks! :)
