### ISSUE TITLE
setEnabled and setClickable do not work

### ISSUE THREAD

**Issue by verilog15** [hbb20/CountryCodePickerProject#411]
I want to be able to enable and disable the CCP dynamically with Java. It looks like both `setClickable`  and `setEnabled` do nothing. I looked in the previous issues (like #395) but you suggested to use `clickable` in the the XML file instead of the Java code. How do I enable and disable the CCP within Java?

**Comment by hbb20** [comment]
Can you please try "ccp.setCcpClickable()" method and let me know if that's what you are looking for?

**Comment by hbb20** [comment]
Feel free to comment if suggested solution does not work for you. Thanks.
