### ISSUE TITLE
ccp_hintExampleNumberFormat not found

### ISSUE THREAD

**Issue by masiwa** [hbb20/CountryCodePickerProject#416]
Hi,

I am using the library and I need to show the leading '0' in front of phone number.

Gradle build fails with `ccp_hintExampleNumberFormat not found` and i can't find a way to solve this, may be I have missed something.

I have joined the android layout file, the grable file and a screenshot of the activity.

Thaks in advance.
Fawzi.

[ccp_hintExampleNumberFormat.zip](https://github.com/hbb20/CountryCodePickerProject/files/4858365/ccp_hintExampleNumberFormat.zip)

**Comment by hbb20** [comment]
Unfortunately, as of now CCP supports "International" format of a number. Looks like leading 0 is part of "National" format of the phone. 

![image](https://user-images.githubusercontent.com/4918760/87846761-82e2c680-c88f-11ea-90ca-e77cf2593c86.png)

**Comment by masiwa** [comment]
Ok thanks.
