### ISSUE TITLE
countrt code cursor color 

### ISSUE THREAD

**Issue by gouthamsivakumar1** [hbb20/CountryCodePickerProject#419]
is it possible to change country code cursor color

**Comment by hbb20** [comment]
I assume you mean down arrow color? you can follow [this](https://github.com/hbb20/CountryCodePickerProject/wiki/CCP-Theme-Customization#using-xml-4)? Let me know if that does not work.

**Comment by gouthamsivakumar1** [comment]
> I assume you mean down arrow color? you can follow [this](https://github.com/hbb20/CountryCodePickerProject/wiki/CCP-Theme-Customization#using-xml-4)? Let me know if that does not work.

 hi, not the arrow  down color  i meant about in  edittext cursor color  in Cppdialog box (the dialog which is used to type and  selected color )
