### ISSUE TITLE
Suggestion - "Select a country" to "Select a country/region"

### ISSUE THREAD

**Issue by yasirahmedkhan** [hbb20/CountryCodePickerProject#420]
I was uploading my app on Huwai AppGallery, and app is using CountryCodePicker Library, In review they suggested me to update the title of Country Code Picker Dialog with "Select a country" to **"Select a country/region"**.
So i would like to suggest this change.

please check attached screenshot of review message
![review](https://user-images.githubusercontent.com/15723951/87407120-26578100-c5db-11ea-83b2-22f84e90ff33.PNG)

**Comment by hbb20** [comment]
Thanks for reporting. It's best to customize title based on your need.


https://github.com/hbb20/CountryCodePickerProject/wiki/Custom-Dialog-Title--%7C-Search-Hint-%7C-Empty-result-ACK

**Comment by hbb20** [comment]
I hope that worked for you. Feel free to comment back if that does not work.
