### ISSUE TITLE
Widget doesn't support match_parent, or gravit attributes

### ISSUE THREAD

**Issue by ibnekhan** [hbb20/CountryCodePickerProject#43]
I want to use this widget and make its width to match_parent but it's not working either it support gravity or layout gravity attributes or set alignment..

**Comment by zhenyuan0502** [comment]
I have the same issue, @hbb20 can you improve match_parent on your textview?  According to #54, when I use as Country Selector which need to dynamic width and gravity in the layout.

**Comment by hbb20** [comment]
I'm working on it. 👍 I will notify you once update is released.

**Comment by hbb20** [comment]
Hey @zhenyuan0502 , @tam0407 and @karljamoralin. Finally version 2.0.0 supports "match_parent" for width.

 _ccp_textGravity_ property can be used for alignment. 

Please read [update guide](https://github.com/hbb20/CountryCodePickerProject/wiki/Update-Guide-for-v2.0.0) before upgrading to v2.0.0.
