### ISSUE TITLE
No touch feedback on click (on picker and in countries list) in 2.4.1

### ISSUE THREAD

**Issue by benju69** [hbb20/CountryCodePickerProject#432]

**Comment by benju69** [comment]
up
No workaround for this ?

**Comment by hbb20** [comment]
I could not reproduce that. Are you sure there isn't any view on top of it to consume click?

**Comment by benju69** [comment]
No view on top no

Before (2.4.0) when I click an item : 
![device-2020-12-08-093940](https://user-images.githubusercontent.com/2486590/101460303-b656e800-3939-11eb-8909-159317787074.png)

After (2.4.1+)  when I click an item : 
![device-2020-12-08-094614](https://user-images.githubusercontent.com/2486590/101460811-5ad92a00-393a-11eb-95b9-3ab9d3f0e924.png)

Also from the changelog : No ripple effect (as a potential fix for #403)

**Comment by hbb20** [comment]
This was removed as a potential fix for crashes on certain devices.

**Comment by benju69** [comment]
Can we have an option to have it back ? Or don't use ripple, just use `android:background="?attr/selectableItemBackground"`

**Comment by hbb20** [comment]
Please try the latest version.
