### ISSUE TITLE
huawei AppGallery

### ISSUE THREAD

**Issue by mustafamemis** [hbb20/CountryCodePickerProject#433]
Your application submitted at 19:38:44,August 19,2020 for releasing Gm Direct 1.tr.1 was rejected.
Reason for rejection:
[Description]: We found that it does not display correctly when selecting country for the phone number (for example, some of the regions should not be shown as countries). Please see the attachment. Please refer to the rule 4.9 of "AppGallery Review Guidelines": https://developer.huawei.com/consumer/en/doc/distribution/app/30202
­[Suggestion]: Please change [Country ] to [Country / region], and rule out such problems under other modules or other languages.

pleace help..

**Comment by hbb20** [comment]
Duplicate of #420 

Thanks for reporting. It's best to customize title based on your need.

https://github.com/hbb20/CountryCodePickerProject/wiki/Custom-Dialog-Title--%7C-Search-Hint-%7C-Empty-result-ACK

Please comment back if that does not work.

**Comment by mustafamemis** [comment]
> Kopyası [# 420](https://github.com/hbb20/CountryCodePickerProject/issues/420)
> 
> Bildirdiğiniz için teşekkürler. Başlığı ihtiyacınıza göre özelleştirmek en iyisidir.
> 
> https://github.com/hbb20/CountryCodePickerProject/wiki/Custom-Dialog-Title--%7C-Search-Hint-%7C-Empty-result-ACK
> 
> Bu işe yaramazsa lütfen tekrar yorum yapın.

it worked thank you.
