### ISSUE TITLE
Country code Canada related issue

### ISSUE THREAD

**Issue by sathishmscict** [hbb20/CountryCodePickerProject#436]
Step - 1 : open ccp dialog 
Step - 2 : Search and select Canada
Step - 3 : Enter any invalid mobile no 972 (example: Not a valid Canada mobile no)
 Now  Canada country code automatically updated to "US +1" (With US flag)

lib version  : 2.4.0

**Comment by hbb20** [comment]
Hello Satish,

That is actually a feature CCP provides. Canada and USA both have +1
country code. But they differ by area code. If you select Canada but then
start typing area code which is in USA then CCP will auto change country.
In your case 972 area code is for DALLAS, TX, USA.



You are not stuck with this though. If you want to disable this then simply
add "app:ccp_areaCodeDetectedCountry=false" To your xml layout.

**Comment by sathishmscict** [comment]
Thank you, its working fine.
