### ISSUE TITLE
How can i change the coloring of the Pop up dialog 

### ISSUE THREAD

**Issue by veeranath** [hbb20/CountryCodePickerProject#44]
How can i change the coloring of the Pop up dialog ?

**Comment by hbb20** [comment]
Colors of popup dialog are set from application's theme colors. Changing theme colors will change the color of dialog.

**Comment by veeranath** [comment]
i am using Theme.AppCompat.NoActionBar theme then how can i initialization it can i do like this 

 <com.hbb20.CountryCodePicker
                    android:id="@+id/codepicker"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center_vertical"
                    android:layout_weight="1.5"
                    app:textSize="14sp"
                    style="@style/AppTheme"/>

**Comment by hbb20** [comment]
Specifically what color do you want to change?

**Comment by veeranath** [comment]
Done...thanks i had done like the below style name

`<item name="android:dialogTheme">@style/CountryDialogbox</item> `

**Comment by mpierucci** [comment]
Isnt a way of customizing dialog theme just for cpp dialog and not all my dialogs?

**Comment by hbb20** [comment]
Yes..
If you are using latest version (>=2.0.1) then it has options for modifying
ccp dialog Colors. Try by adding "ccpDialog_backgroundColor" to CCP's xml.

**Comment by mpierucci** [comment]
@hbb20 Yes sorry I saw that later and forgot to update the question. Thanks!! 
Last one, can I make the dialog go full screen?

**Comment by hbb20** [comment]
For such quick and minor switches, it is good to use dialog rather than
full activity. This eliminates transitions and user remains in context.

So, we can not make dialog to take up full screen.

**Comment by mpierucci** [comment]
I totally understand you and I think you are correct, sadly I have ti implemented what design request me, thanks any way.
