### ISSUE TITLE
CountryCodePicker still depends on old AppCompat, so Jetifier still needs to be used

### ISSUE THREAD

**Issue by BoD** [hbb20/CountryCodePickerProject#451]
Hi!  This library depends on [Recycler Bubble](https://github.com/FutureMind/recycler-fast-scroll), which hasn't been updated in 4 years, and still depends on the old AppCompat. Although there is a [PR to migrate to AndroidX](https://github.com/FutureMind/recycler-fast-scroll/pull/79), waiting to be merged since Jun 2019, it looks like we can assume it will never be merged.

Because of this, unfortunately, users of your lib must use Jetifier, which is a step that contributes to build slowness.

One possible solution would be to simply copy the classes into your own project (it is only 9 classes, and the license is Apache v2) and remove the dependency. Another (more complicated) way would be to fork the project.

Additional note: [this Gradle plugin](https://github.com/plnice/can-i-drop-jetifier) helps detecting if a project still depends on any old AppCompat dependencies, to determine if Jetifier can be disabled. Unfortunately it didn't work with CountryCodePicker and I suspect it is because of this exclusion in your `build.gradle` file:
```
   implementation('com.futuremind.recyclerfastscroll:fastscroll:0.2.5', {
        exclude group: 'com.android.support'
    })
```
I'm not 100% certain this exclusion makes sense.

**Comment by SerggioC** [comment]
copy the fastlib to the ccp project, update the lib and make a pull request to CountryCodePickerProject, maybe it'll be merged.

**Comment by BoD** [comment]
@hbb20 Would that be a good idea?

**Comment by SerggioC** [comment]
Well I've just updated it and added it into the project. 
Check the pull request please.
https://github.com/hbb20/CountryCodePickerProject/pull/453

**Comment by BoD** [comment]
Very cool, I hope this will be merged!
