### ISSUE TITLE
Auto-Detect Country does NOT respect the Country Master List

### ISSUE THREAD

**Issue by SimonHaenle2** [hbb20/CountryCodePickerProject#454]
I just stumbled upon this issue.
When you set up a custom master list, for example "IT, EN, FR" and then  use Auto-Detect Country and sign in for example from german Network, the picker will set the language to "DE" anyway even if you explicitly specified that DE is not allowed.
This is somewhat confusing and quite unexpected as I would consider the master list to restrict also the auto detect country.

Reproducable: Always
Version: 2.4.2

**Comment by hbb20** [comment]
Good catch. Never thought of that. Can I look at it this weekend or is it
too late?

**Comment by SimonHaenle2** [comment]
Of course, it's not urgent :)
