### ISSUE TITLE
android studio can't find the class of hbb20

### ISSUE THREAD

**Issue by mahmoudkhalaf93** [hbb20/CountryCodePickerProject#457]
message error
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.hbb20:country_picker:2.4.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/hbb20/country_picker/2.4.2/country_picker-2.4.2.pom
       - https://jcenter.bintray.com/com/hbb20/country_picker/2.4.2/country_picker-2.4.2.pom
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

in xml activity all next lines are red 
 <com.hbb20.CountryCodePicker
        android:id="@+id/country_picker"
        android:layout_width="355dp"
        android:layout_height="wrap_content"
        android:layout_marginTop="16dp"
        android:background="@drawable/shape"
        app:ccp_arrowColor="@color/light_main"
        app:ccp_contentColor="@color/light_main"
        app:ccpDialog_backgroundColor="@color/dark_main"
        app:ccpDialog_textColor="@color/light_main"
        app:ccp_showFullName="true"
        app:ccp_showNameCode="false"
        app:ccp_showPhoneCode="false"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/button"/>

in main activity 
import com.hbb20.CountryCodePicker; // it's red in hbb20 word and other words is gray
//in onCreate method
CountryCodePicker country;  //it's red in CountryCodePicker 
........
gradle file no error in it

plugins {
    id 'com.android.application'
}

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.0"

    defaultConfig {
        applicationId "com.example.gasstation"
        minSdkVersion 19
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation files('libs\\jtds-1.2.5.jar')
    implementation 'androidx.navigation:navigation-fragment:2.2.2'
    implementation 'androidx.navigation:navigation-ui:2.2.2'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.2.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0'
    implementation 'com.google.android.gms:play-services-maps:17.0.0'
    implementation files('libs\\mail.jar')
    implementation files('libs\\additionnal.jar')
    implementation 'com.hbb20:country_picker:2.4.2'
    implementation files('libs\\activation.jar')
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}

**Comment by SerggioC** [comment]
Where did you get this from?
implementation 'com.hbb20:country_picker:2.4.2' 
it's: implementation 'com.hbb20:ccp:2.4.2'

**Comment by hbb20** [comment]
`com.hbb20:ccp:2.4.2` is the right dependency. Please remove `com.hbb20:country_picker:2.4.2` and use that.
