### ISSUE TITLE
How to apply custom font?

### ISSUE THREAD

**Issue by EvgenePrytula** [hbb20/CountryCodePickerProject#463]
Hey guys, I have faced with problem when I need to apply custom font? How I can do that? I didn't find any mentions about that in docs.

**Comment by hbb20** [comment]
Hopefully this will be helpful:
https://github.com/hbb20/CountryCodePickerProject/wiki/Custom-TypeFace-(FontFamily)

**Comment by EvgenePrytula** [comment]
@hbb20 I can do that easily now. Example:
`countryCodePicker.setTypeFace(ResourcesCompat.getFont(requireContext(), R.font.nunito_regular))`
