### ISSUE TITLE
How to show country flag in circle shape instead of rectangle

### ISSUE THREAD

**Issue by vairaganeshv** [hbb20/CountryCodePickerProject#468]
Hi,

Is there is any option to show country flag as in circle shape ?

**Comment by hbb20** [comment]
Right now library only packs single set of flags which is a requirement to maintain lower side of bundle. But you can override default images by putting images of rounded flags in your project. You need to follow same names of file as in https://github.com/hbb20/CountryCodePickerProject/tree/master/ccp/src/main/res/drawable
