### ISSUE TITLE
jCenter shutdown - solution: use CCP v2.5.0+

### ISSUE THREAD

**Issue by pstens** [hbb20/CountryCodePickerProject#469]
Move away from jcenter since it'll be shutdown on May 1st 2021
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by davidmigloz** [comment]
Any plans on this? MavenCentral would be a good alternative.
https://chris.banes.dev/publishing-to-maven-central/

For now, I'm using JitPack as a workaround (not ideal):
```
allprojects {
    repositories {
        ...
        maven { url 'https://jitpack.io' }
    }
}

dependencies {
    ...
    implementation 'com.github.hbb20:CountryCodePickerProject:2.4.2'
}
```

Your current latest release is 2.4.7, but your latest tag in the repository is 2.4.2. It'd be nice to keep them aligned.

Thanks for your work!

**Comment by hbb20** [comment]
Yes. I'll configure it soon. Before May😂.

**Comment by hbb20** [comment]
Checkout `v2.5.0` that's coming from MavenCentral.

**Comment by SalvatoreScalia** [comment]
I like put this when the number is correct. (✔️) Wish is the name of ticket properties?
