### ISSUE TITLE
Is it possible to change the style of the dialog.

### ISSUE THREAD

**Issue by oreofeolurin** [hbb20/CountryCodePickerProject#47]
Hi @hbb20,

Great work i must say. However I am having trouble the background color of the dialog box to white. Is there a theme configuration for that?

**Comment by hbb20** [comment]
Hi. I think solution of this [issue](https://github.com/hbb20/CountryCodePickerProject/issues/44) might help you.

**Comment by oreofeolurin** [comment]
Thanks @hbb20 it helped
