### ISSUE TITLE
Number Length

### ISSUE THREAD

**Issue by Royal201709** [hbb20/CountryCodePickerProject#472]
Is it possible to stop entering once user reaches to last digit of his/her phone number based on the selected country ?

**Comment by hbb20** [comment]
That seems little different because some countries might have phone numbers
of different lengths.

If you want to ensure that phone number is valid you can check for isValid
or set onValidityChange  listener.

**Comment by Royal201709** [comment]
Thanks for your response. But I have few more questions.
**Question one:** Is not possible to define phone number length from selected country ?
**Question two**. How you make sure that phone number is valid or not? Where from do you take that validity ?

**Comment by hbb20** [comment]
CCP does not do validation / length check on it's own. It uses https://github.com/MichaelRocks/libphonenumber-android to do that.
