### ISSUE TITLE
Change textcolor on dialog

### ISSUE THREAD

**Issue by haris4063** [hbb20/CountryCodePickerProject#48]
I have customizable app theme. User can set text color, background color and theme color of all activities. I want to customize dialog as well according to theme. How is it possible?

**Comment by shad32** [comment]
i'm not sure, maybe create custom style like
<item name="android:dialogTheme">@style/CUSTOM_STYLE</item>
CUSTOM_STYLE Inheritance from Theme.AppCompat.Dialog and there change color of text

**Comment by hbb20** [comment]
Hi. If someone want to change style [issue](https://github.com/hbb20/CountryCodePickerProject/issues/44) will be helpful.

But it looks like you want to change the theme at run time. Sadly it is not supported yet.

**Comment by hbb20** [comment]
Finally you can customize dialog theme programmatically from version 2.0.1.

```
setDialogBackgroundColor();
setDialogTextColor();
setDialogSearchEditTextTintColor();
```

will allow you to modify theme. 

Please read [update guide](https://github.com/hbb20/CountryCodePickerProject/wiki/Update-Guide-for-v2.0.0) before upgrading from any lower version to v2.0.0 or above.
