### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'android.text.Editable android.widget.EditText.getText()' on a null object reference

### ISSUE THREAD

**Issue by vmitkovic** [hbb20/CountryCodePickerProject#487]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.text.Editable android.widget.EditText.getText()' on a null object reference
        at com.hbb20.CountryCodePicker.getFullNumber(CountryCodePicker.java:1837)

When I try to call:
countryCodePicker.getFullNumber()

mavenCentral:
implementation 'com.hbb20:ccp:2.5.1'

**Comment by hbb20** [comment]
Are you calling `ccp.registerCarrierNumberEditText(editTextCarrierNumber);` before `countryCodePicker.getFullNumber()`?

**Comment by vmitkovic** [comment]
It worked. Thanks!

**Comment by THUFU7** [comment]
I got this problem as well how can I fix it?

**Comment by hbb20** [comment]
> I got this problem as well how can I fix it?
> 
> 

Are you calling ccp.registerCarrierNumberEditText(editTextCarrierNumber); before countryCodePicker.getFullNumber()?

**Comment by THUFU7** [comment]
No. How does it work?

**Comment by THUFU7** [comment]
Hello. What does it mean when you say editTextCarrierNumber? Kindly
