### ISSUE TITLE
Version 2.5.2 missing from mavencentral

### ISSUE THREAD

**Issue by androideveloper** [hbb20/CountryCodePickerProject#490]
Hey. I noticed that [version 2.5.2 is released](https://github.com/hbb20/CountryCodePickerProject/blob/master/CHANGELOG.md#252---2021-4-16) but it's missing from maven central. https://search.maven.org/artifact/com.hbb20/ccp/2.5.1/aar Could you please check?

**Comment by hbb20** [comment]
sorry try now

**Comment by androideveloper** [comment]
works now, thanks 🙏
