### ISSUE TITLE
set country to null or blank

### ISSUE THREAD

**Issue by Avramo** [hbb20/CountryCodePickerProject#496]
I get the User's data from the DB, and sometimes for whatever reason the User has "" (empty string) saved as their country.
I use this Picker to edit their country, and if the User does not change his country then I get India "IN" as the `selectedCCPCountry` since the `defaultCCPCountry` automatically returns India if no country was set.
How can I set the `selectedCCPCountry` or some other flag to `null` or "" so that in this case I can know not to change the User's data?

Thanks!

**Comment by hbb20** [comment]
It seems like your primary use case is to select country without phone
number validation, did I get that right? if so, you should try Android
Country Picker (https://github.com/hbb20/AndroidCountryPicker). It has out
of box support for non selection and much more. Please let me know if that
works for you.

**Comment by Avramo** [comment]
Thanks for the quick response!

As I don't want to undo all the code I have already, I made a temporary workaround.  

`        if (mCountryChangedByUser) {
            userUpdate.setCountry(mCountryCCP.getSelectedCountryNameCode() );
        } else {
            userUpdate.setCountry(mUser.getCountry());
        }`


Maybe next time I'll use the AndroidCountryPicker.

Thanks!

**Comment by hbb20** [comment]
Glad that workaround worked for you. Sorry for the inconvenience.

**Comment by Avramo** [comment]
No problem at all!
Keep up the great coding!

Thanks!
