### ISSUE TITLE
Remove India (in the code only ;p )

### ISSUE THREAD

**Issue by Isabellle** [hbb20/CountryCodePickerProject#50]
First of all, this is one of the most awesome android project that I've had the chance to ingrate. Big thanks for that.

I need to limit the list to some countries only, which I could successfully achieved; except that the Indian flag is still in first position, I don't find any place where it has been set.

Here is the code:
`<com.hbb20.CountryCodePicker
android:layout_gravity="center_horizontal"
android:id="@+id/ccp"
android:layout_width="wrap_content"
android:layout_height="wrap_content"
app:ccpLanguage="FRENCH"
app:arrowSize="26sp"
app:textSize="26sp"
app:showFullName="true"
app:customMasterCountries="BE,FR,AU,BG,CY,CZ,ES,FI,GB,HU,IT,LU,NL,PO,PR,RO,SE"/>`

Thank you very for your help

**Comment by hbb20** [comment]
Hi @Isabellle . India is a library default country so you are getting IN at first position. You can set your default country using `app:defaultNameCode="BE"`. Find more documentation [here](https://github.com/hbb20/CountryCodePickerProject#1-default-country).

**Comment by hbb20** [comment]
Is it fixed?

**Comment by Isabellle** [comment]
That was fast! Yes it is working like a charm :)

**Comment by Isabellle** [comment]
Unfortunately I can't seem to be able to change de "defaultNameCode" programmatically.
I'm setting this but it doesn't change:
`countryPicker.setDefaultCountryUsingNameCode("FR"));`

**Comment by hbb20** [comment]
Oh. What is happening? 
Which country is being set if you call `countryPicker.resetToDefaultCountry();` right after `countryPicker.setDefaultCountryUsingNameCode("FR");`?

**Comment by Isabellle** [comment]
I tried what you suggested and unfortunately it crashes.
ERR: stack=java.lang.StackOverflowError: stack size 8MB

at com.hbb20.CountryCodePicker.setSelectedCountry(CountryCodePicker.java:259)
                                                                        at com.hbb20.CountryCodePicker.resetToDefaultCountry(CountryCodePicker.java:723)
                                                                        at

**Comment by Isabellle** [comment]
My fault! It works now, sorry for not having read your documentation till the end.
Thanks so much for your assistance!
