### ISSUE TITLE
Using for RTL ( arabic) cause field hidded

### ISSUE THREAD

**Issue by MoustafaElsaghier** [hbb20/CountryCodePickerProject#501]
hi, I'm trying to use the library for multi-language app

it's working amazing in the English version but, when try to use Arabic the field gets removed or hidden, can you please help in that?

using latest version 2.5.4

XML code :
 <com.hbb20.CountryCodePicker
                        android:id="@+id/ccp_mobile"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:gravity="center"
                        app:ccp_contentColor="@color/disable_txt_color"
                        app:ccp_defaultPhoneCode="973"
                        app:ccp_useFlagEmoji="true"
                        android:layoutDirection="ltr"
                        app:ccp_showNameCode="false"
                        app:ccp_showFlag="true"
                        app:ccp_textSize="15sp" />

the box is hidden for me in RTL layout and must put the attribute 
android:layoutDirection="ltr" which fails the dialog directions so any suggestions?

**Comment by hbb20** [comment]
Sorry for inconvenience. Can you share your xml and screenshot of problem.
I can look at it later today.

**Comment by MoustafaElsaghier** [comment]
I've made the layout RTL from the root and this is the result 
![image](https://user-images.githubusercontent.com/18235731/129912207-97e5e3d6-1c2e-4c3d-8fed-12af9c369479.png)

and if the root layout direction put to locale/LTR 
![image](https://user-images.githubusercontent.com/18235731/129912351-ffb893b4-34e4-43f0-99b7-66551de6ac1b.png)

**Comment by MoustafaElsaghier** [comment]
any update bro? @hbb20

**Comment by hbb20** [comment]
I verified and reproduced the issue last evening but did not have enough
time to fix. I have some free time this evening to fix it. Will that work
for you?

**Comment by hbb20** [comment]
Also if your use case is to pick a country and not phone number support,
you can try
https://github.com/hbb20/AndroidCountryPicker

**Comment by MoustafaElsaghier** [comment]
yes today is okay, please let me know once fixed, I need same as current one appreciate what you suggest

**Comment by hbb20** [comment]
Hey.. try by removing `android:gravity="center"` that worked for me.

**Comment by MoustafaElsaghier** [comment]
after removing it, it's working but the popup alignment is not correct still the same as making layout direction LTR
https://prnt.sc/1qeirpj

**Comment by MoustafaElsaghier** [comment]
@hbb20 any updates?

**Comment by MoustafaElsaghier** [comment]
okay thanks it's working now for me like you, appreciate bro <3

**Comment by shahzadafridi** [comment]
Can you add support to change on app language as well not the only device.
