### ISSUE TITLE
using only the dialog and auto format feature?

### ISSUE THREAD

**Issue by OmarELRayes** [hbb20/CountryCodePickerProject#504]
Is there is a way to only use the dialog and the auto format feature ?
I already made a design and would love to use this library's functionality  

![image](https://user-images.githubusercontent.com/32176855/132422844-10fd698f-8b20-43ac-a054-03c70f4dd19e.png)

I made it using Material TextInputLayout and TextInputEditText.
Is there a way to call the dialog manually and apply the auto format to my edit text ?

**Comment by hbb20** [comment]
Yes you can launch dialog directly. I haven't tried this but this is something you can do.

1. Add a CCP view (`ccp`) with visibility invisible
2. then on click of your custom layout, you can launch dialog by calling `ccp.launchCountrySelectionDialog();`
3. Add selection listener to ccp `setOnCountryChangeListener()`
4. From this listener, set selected country info to your custom layout
