### ISSUE TITLE
Phone Number Auto Formatting does not work properly when first digit matches country code

### ISSUE THREAD

**Issue by ansonallard** [hbb20/CountryCodePickerProject#509]
The per-country phone number formatting does not work properly when the first digit of the phone number matches the first digit of the country code. I was expecting that the formatting would be the same as long as I typed in only 10 digits.
<img src="https://user-images.githubusercontent.com/34141612/134409580-f0f685eb-4da9-4c20-8914-2690185b8c70.jpg" width="300px"/> | <img src="https://user-images.githubusercontent.com/34141612/134409583-0f7292e4-3abc-43c4-881f-cb044da56e10.jpg" width="300px"/>
 
It would be great if the formatting worked properly for all phone numbers with 10 digits!

**Comment by hbb20** [comment]
I roughly remember doing something to handle duplicate coutnry code in
phone. But I remember checking this particular scenario and found that no
valid AREA CODE of phone (at least for USA) starts with 1.
https://www.allareacodes.com/area-code-list.htm

**Comment by ansonallard** [comment]
Awesome - thank you for the quick reply. I didn't know that no US area codes begin with 1. Thanks!
