### ISSUE TITLE
how to set default country 

### ISSUE THREAD

**Issue by kedar2407** [hbb20/CountryCodePickerProject#512]

**Comment by OsamaFarooqi** [comment]
In XML you just need to add this line

`app:ccp_defaultNameCode="PK" `

here PK is the country standard name code of Pakistan, you need to replace it with the ISO country code that you want to set as the default country.
Then your XML will look like this
```
   <com.hbb20.CountryCodePicker
            android:id="@+id/ccp"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:ccp_defaultNameCode="PK"
            />
```
If you want that your app to auto-detect the country code then you just need to add this line in the XML code
`app:ccp_autoDetectCountry="true"`

**Comment by hbb20** [comment]
Thanks @OsamaFarooqi 👍🏼
