### ISSUE TITLE
Limit country code to show in the dialog 

### ISSUE THREAD

**Issue by shubh261096** [hbb20/CountryCodePickerProject#519]
I want to show only certain countries like India, US, Australia, etc, not all of them. 
Is there any method where I can pass a list of those country names, codes and those only show up in the dialog?

**Comment by hbb20** [comment]
https://github.com/hbb20/CountryCodePickerProject/wiki/Custom-Master-Country-List

**Comment by shubh261096** [comment]
Thanks you saved the day!
