### ISSUE TITLE
"Found not to show search" was shown as Toast Message

### ISSUE THREAD

**Issue by ravi8x** [hbb20/CountryCodePickerProject#52]
I have tried the below code snippet to show my spinner dropdown. I have very limited countries and don't want to show search option.
```
<com.hbb20.CountryCodePicker
                android:id="@+id/ccp"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                app:contentColor="@android:color/white"
                app:hideNameCode="true"
                app:showFlag="false"
                app:keyboardAutoPopOnSearch="false"
                app:selectionDialogShowSearch="false"
                android:layout_gravity="center_vertical"
                app:customMasterCountries="US,IN,HK,SG"/>
```
When the dropdown is selected, a toast message saying **Found not to show search** was shown. I think it was caused by [https://github.com/hbb20/CountryCodePickerProject/blob/master/ccp/src/main/java/com/hbb20/CountryCodeDialog.java#L36](url) this line. 

How can I avoid this? What is the purpose of this?

**Comment by hbb20** [comment]
That's my mistake, sorry for that. It was meant for developing mode only
but completely forgot to remove before release.

Can you wait for a day? I will update new version with the fix.

**Comment by ravi8x** [comment]
@hbb20 Yes, I can wait. Thanks for the awesome library.

Please let me know once updated.

**Comment by hbb20** [comment]
Hey @ravi8x , new version is live now. version 1.7.5 should work for you.

Later I found that you are Ravi Tamada. Thank you for the [AndroidHive](http://www.androidhive.info/). Articles are really helpful.

**Comment by ravi8x** [comment]
Thanks Man :) 

I am glad you liked [Androidhive](http://www.androidhive.info)
