### ISSUE TITLE
Keyboard & Dialog Issue With Single Click

### ISSUE THREAD

**Issue by atdev02** [hbb20/CountryCodePickerProject#521]
Country Code Picker Dialog & keyboard are not opening up properly with single user click event but it seems to be worked with the double click. I have also tried with legacy versions but with those version also issue was not fixed. I have tried for any error logs in logcat but not error logs were printed. Please need an solution to this problem its urgent.

**Comment by hbb20** [comment]
I tried to fix a while back but seems like something is changed with newer
android versions. Will have to take a deeper look but don’t have time
right now. If you wanna try and make a pr, I’ll be happy to merge it

**Comment by atdev02** [comment]
I think the issue is not related to android versions as it is working with same android version on same device with older version of country code picker i.e. 2.1.0

**Comment by hbb20** [comment]
Hey, please try v2.6.0. It should fix this,

**Comment by atdev02** [comment]
Sure, Thanks
