### ISSUE TITLE
Search Country Name By Start Value.

### ISSUE THREAD

**Issue by FidaMOhsin** [hbb20/CountryCodePickerProject#527]
Can you add funcationalty of search country name by only its start value?
like now when we write just "P", it gives all countries that contain P value. so for this i will get only those countries which start from P.

**Comment by hbb20** [comment]
Interesting. Thinking behind search in entire name and not just in start is some official names are different than what people use regularly. For example if user type "UAE" they expect to see "United Arab Emirates (UAE)" in result.

**Comment by FidaMOhsin** [comment]
@hbb20 Yes i know. You are right.
But currently i want this functionality in my app. Can you make a simple method like searchCountryNameFromStart().
It would be great if you can this. You just need to change this code.

boolean isEligibleForQuery(String query) {
        query = query.toLowerCase();
        return containsQueryWord("Name", getName(), query);
//                containsQueryWord("NameCode", getNameCode(), query) ||
//                containsQueryWord("PhoneCode", getPhoneCode(), query);
//                containsQueryWord("EnglishName", getEnglishName(), query
//                );
    }

    private boolean containsQueryWord(String fieldName, String fieldValue, String query) {
        try {
            if (fieldValue == null || query == null) {
                return false;
            } else {
                return fieldValue.toLowerCase().startsWith(query.toLowerCase());
            }
        } catch (Exception e) {
            Log.w("CCPCountry", fieldName + ":" + fieldValue +
                    " failed to execute toLowerCase(Locale.ROOT).contains(query) " +
                    "for query:" + query);
            return false;
        }
    }
