### ISSUE TITLE
Title & Placeholders in Strings

### ISSUE THREAD

**Issue by guzfernandez** [hbb20/CountryCodePickerProject#53]
Is it possible to set our own strings? 
By default it says "Select country", "search...", "result not found". But I want to have my own messages. Could it be possible to change them? Thanks.

**Comment by hbb20** [comment]
Well as per current implementation, library can have only one message
string per language.

There is a way to do it. Fork the project and add CCP as module in your
existing project and replace those string messages.

Can you please help me by explaining why you want to change those messages?
What is your exact usecase ? This will help us to cover other possible
usecases of library in upcoming versions.

Thank you.

**Comment by guzfernandez** [comment]
Well, the main reason is to be able to use my own languages and not have to change the library language. Also, I would like to change it to "Select a country", "Search..." and "Results not found". (Uppercasing basically).

**Comment by hbb20** [comment]
Thanks for pointing. I cross checked some apps and found that Uppercase is
the norm and library should follow it. I will definitely correct it.

Can you give me a day to correct it and replace current text by your
suggested messages?

**Comment by guzfernandez** [comment]
Yeah, of course! Thanks a lot for the fast reply and the help! 👍

**Comment by hbb20** [comment]
Try updated version 1.7.6.
Is everything ok?

**Comment by guzfernandez** [comment]
Yeah, looks good. Thanks
