### ISSUE TITLE
setDefaultCountryUsingPhoneCode is not working

### ISSUE THREAD

**Issue by rakshithsj30** [hbb20/CountryCodePickerProject#532]
Hi, 

I  want to show a specific country from api to be selected by default and shown in the ui. But it is not working. every time it shows India in the Ui. Pls help.

Here is the code:

                    binding?.ccp?.setDefaultCountryUsingPhoneCode(1)
                    binding?.ccp?.resetToDefaultCountry()

XML:

  <com.hbb20.CountryCodePicker
                                        android:id="@+id/ccp"
                                        android:layout_width="wrap_content"
                                        android:layout_height="wrap_content"
                                        app:ccpDialog_keyboardAutoPopup="false"
                                        app:ccpDialog_showCloseIcon="true" />

**Comment by hbb20** [comment]
There are multiple countries with that country code. So it's recommended
that you use set Default Country Us ngNameCode and pass "US" or "CA".

**Comment by rakshithsj30** [comment]
I found one observation. If i keep following code in onviewcreated() of fragment, it is working.       
                binding?.ccp?.setDefaultCountryUsingPhoneCode(1)
                binding?.ccp?.resetToDefaultCountry()

But if i execute the same code after i get the country code from api response (usually it takes 5 - 7 seconds to get response from server), it is not working.
