### ISSUE TITLE
Can you add region with country name?

### ISSUE THREAD

**Issue by MOhsain** [hbb20/CountryCodePickerProject#534]
Basiically we are trying to upload the the app to Huawei Playstore and we are using your library but they could not submit our app due to some issues.
Their main point is kindly add chine before Hong Kong/Macao/Taiwan these region like this China /Macao, China /Taiwan, China. 

Here is the respose from Huawei Playstore -->
3.[Description]: We found that it display Hong Kong / Macao / Blue Sky with a White Sun Flag when selecting "country" in the module of registration function in your app,the display is unqualified. Please refer to the rule 4.4 of "AppGallery Review Guidelines": https://developer.huawei.com/consumer/en/doc/app/50104
[Suggestion]: Please change [Select a Country] to [Select a Country/ Region], and change Hong Kong/Macao/Taiwan in the registration function module to Hong Kong, China /Macao, China /Taiwan, China. Please modify the Blue Sky with a White Sun Flag displayed in the module of "Register-Phone".

**Comment by hbb20** [comment]
https://github.com/hbb20/CountryCodePickerProject/issues/420

**Comment by hbb20** [comment]
I realized that #420 might not answer first part where you need to change name. This [wiki page](https://github.com/hbb20/CountryCodePickerProject/wiki/Change-country-names-for-personal-project) should be helpful.
