### ISSUE TITLE
getSelectedCountryNameCode return wrong code with some languages

### ISSUE THREAD

**Issue by mtaran89** [hbb20/CountryCodePickerProject#539]
Sample Phone Language Turkish (TR)

When Choose Hindistan(INDIA), code return İN.
It must be IN.
 public String getSelectedCountryNameCode() {
        return getSelectedCountry().nameCode.toUpperCase();
    }
need toUpperCase with EN locale

**Comment by hbb20** [comment]
Good call. Will fix this in next release :)

**Comment by hbb20** [comment]
Check 2.6.1. Let me know if it's still not resolved.
