### ISSUE TITLE
How to disable automatic flag change when the wrong area code is entered?

### ISSUE THREAD

**Issue by Mark1506** [hbb20/CountryCodePickerProject#542]
Hi, I am using this library. It has an interesting function that when I enter the wrong area code of a country, it automatically changes the flag to match that area code.

For example: I select the country as Canada, then enter the next 3 numbers as 222, the flag changes itself to the United States. Looks like this code detection library should be American. This functionality is quite interesting but it is not suitable for my application. How can I disable this feature?
My expectation is that the format of the phone number and the flag remains unchanged even if I enter the wrong area code.

This is my ccp xml code:
                    <com.hbb20.CountryCodePicker
                            android:id="@+id/ccp"
                            android:layout_width="wrap_content"
                            android:layout_height="match_parent"
                            android:background="@drawable/bg_left_corners_white"
                            android:gravity="center"
                            app:ccp_autoDetectCountry="true"
                            app:ccp_autoDetectLanguage="false"
                            app:ccp_autoFormatNumber="true"
                            app:ccp_countryAutoDetectionPref="LOCALE_NETWORK_SIM"
                            app:ccp_rememberLastSelection="true"
                            app:ccp_showNameCode="false"/>

**Comment by hbb20** [comment]
The flag (selected country) changes to USA for 222 area code because Canada does not have 222 as area code and default country for +1 is USA.

https://www.allareacodes.com/canadian_area_codes.htm

**Comment by Mark1506** [comment]
Ah, yes. Great!
Thank you so much!
If possible, can you help to add all new properties to the wiki of this library. It's very helpful for me or any new guys.
I did not find this property ccp_areaCodeDetectedCountry on the wiki tab.
https://github.com/hbb20/CountryCodePickerProject/wiki/XML-Properties

**Comment by Mark1506** [comment]
Your support is so fast. Thank you!
