### ISSUE TITLE
Some common question

### ISSUE THREAD

**Issue by Mark1506** [hbb20/CountryCodePickerProject#543]
Hi, I have some questions and hope can receive the answers for them.
1. Do we have any way to still keep the phone number format if I enter the too-long number?
Example the format is xx xx xx xx . If I enter 9 numbers instead of 8. Can it still be displayed in format xx xx xx xxx (Just add more numbers in the last)?

2. Some phone number format in Vietnam are strange for me
- number start with 9, 6 have format xx xxx xx xx ; 2-3-2-2
- number start with 1 have format xxxx xxxxxx; 4-6
- number start with 2 have format xxx xxxx xxx; 3-4-3
- number start with 3,7,8 have format xxx xxx xxx; 3-3-3 (only this is familiar)
- number start with 4, 0 have no format
Can I know which is the source to get the phone number format that this library used? And will it be updated if any country changes their phone format?

3. Can I choose the specific format in all phone number formats of one country for that country's hint text?

4. Why do some formats use space (xx xx xx xx) and some formats use - (xx-xx-xx-xx)

Thank you!

**Comment by hbb20** [comment]
To answer 1,2 and 4 - this library does not really do formatting on it's own. It uses https://github.com/MichaelRocks/libphonenumber-android for formatting. And for 3, unfortunately as of now that's not possible.

**Comment by Mark1506** [comment]
Thank you, @hbb20
