### ISSUE TITLE
Shows Null object reference when targetsdkversion is kept 30

### ISSUE THREAD

**Issue by mukul2310** [hbb20/CountryCodePickerProject#545]
It works well with targetsdkversion 29 but on changing it to 30, it shows an error related to null object reference and crashes. I want to host an app on play store and want to keep targetsdkversion = 30, what should I do?

**Comment by hbb20** [comment]
Is there any sample project thst you can share with me to reproduce this?

**Comment by mukul2310** [comment]
Resolved this issue, it was getPackageManager() function that returns null in sdk above 29
