### ISSUE TITLE
Float types not allowed 

### ISSUE THREAD

**Issue by RabieMohimane** [hbb20/CountryCodePickerProject#55]
I have a custom widget in my app which has a custom attribute taking a float value, every things work fine but when i add your lib tpp gradle file app.build i got this error 
Error:(101, 34) Float types not allowed (at 'textSize' with value '16.0').

**Comment by hbb20** [comment]
Ihat is happening because of attribute name clash. Text size should be
dimension and not just float.

Still I will resolve the issue in upcoming version by adding prefix to
attribute name.

**Comment by hbb20** [comment]
@RabieMohimane, please upgrade to vesrion 2.0.0. 
Now all attributes has prefix _ccp__  / _ccpDialog__ to avoid name clashes.

Please read [update guide](https://github.com/hbb20/CountryCodePickerProject/wiki/Update-Guide-for-v2.0.0) before upgrading to v2.0.0.
