### ISSUE TITLE
Default country code

### ISSUE THREAD

**Issue by kukadiyaAni** [hbb20/CountryCodePickerProject#56]
Hello

Thanks for this library

I have try to set default country code using integer code but unfortunately not set  default country programmatically

I will set default country code dynamic using code If I set in xml than it's working

Thanks

**Comment by hbb20** [comment]
Selected country and Default countries are different. In the worst case, when something goes wrong then CCP will set default country as selected country in CCP view.  

As per [documentation](https://github.com/hbb20/CountryCodePickerProject#using-phone-code-1) setDefaultCountryUsingNameCode() or setDefaultCountryUsingPhoneCode() will not set default country as selected country in CCP view. To set default country as selected country in CCP view, call resetToDefaultCountry() method.

If this works for you, you can close the issue.
If this does not solve the problem, show me your xml and java code.

However, setting default country using phone code is not recommended. There are few cases where more than one countries have same phone code. Say US and Canada have +1. Putting '1' will result in Canada even if you were intended for US. Use app:defaultNameCode or app:countryPreference to overcome issue.

**Comment by kukadiyaAni** [comment]
Thanks for replay
This library available for Swahili

**Comment by hbb20** [comment]
If someone is interested in adding language support, it's easy. Check [steps to add new language support.](https://github.com/hbb20/CountryCodePickerProject/issues/12).

**Comment by kukadiyaAni** [comment]
Ok thanks
