### ISSUE TITLE
Could not find io.michaelrocks:libphonenumber-android:8.12.17

### ISSUE THREAD

**Issue by thunder413** [hbb20/CountryCodePickerProject#560]
Hello,
When i use the implement way i run into this error 
"Could not find io.michaelrocks:libphonenumber-android:8.12.17" (MayBe the published version is not up to date ?

But in the code its io.michaelrocks:libphonenumber-android:8.12.52

For now i just import it as a module

Thanks in advance

**Comment by sh3lan93** [comment]
I have faced the same issue with version 2.4.7 and after some search, I have found a new version on maven central 2.6.1 that fix this issue.

**Comment by thunder413** [comment]
@sh3lan93 Thanks i will try it
