### ISSUE TITLE
Error: 'ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and 'package:modal_bottom_sheet/src/bottom_sheet_route.dart'

### ISSUE THREAD

**Issue by Irfadg** [hbb20/CountryCodePickerProject#575]
getting the below error while using this package.

package version:  country_code_picker: ^2.0.2`

**Error: 'ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and 'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.
      .push(ModalBottomSheetRoute<T>(
            ^^^^^^^^^^^^^^^^^^^^^**

the modalbottomsheet also have in this package.there is any one know a solution for this..really help neeeded

**Comment by blackspire212** [comment]
Recently I also got the same error.
Then I found this...

https://pub.dev/packages/country_code_picker_x/changelog

Hopefully can help...

**Comment by Irfadg** [comment]
Hey brother,

Thankyou for your response. Let me check and get back to you.

Irfad

**Comment by hbb20** [comment]
Looks like you created an issue on wrong library.. May be you are using some forked library
