### ISSUE TITLE
Hide Search

### ISSUE THREAD

**Issue by rocketreeves** [hbb20/CountryCodePickerProject#58]
Is there a way to remove the search at the top of the list? 

I have only a shot list ` app:customMasterCountries="ZA,AU,BR,QA,NZ,UE,UK,US"` therefore the search seems a bit pointless in this case.

**Comment by hbb20** [comment]
Yes. There is a way to hide search box from the top.
You can do it by setting `app:selectionDialogShowSearch="false"` from XML layout.
