### ISSUE TITLE
Country preferance

### ISSUE THREAD

**Issue by peter6053** [hbb20/CountryCodePickerProject#589]
i want by default to have ke  as  the deafilt flag thus is my snippet "  app:ccp_countryPreference="KE,UG""
![Screenshot 2023-08-23 at 10 47 40](https://github.com/hbb20/CountryCodePickerProject/assets/35918656/e80af6b4-09bd-40c4-b589-bbd376d459c0)

**Comment by peter6053** [comment]
like it should display ke instead of any other flag

**Comment by rranjithkumar100** [comment]
try this       app:ccp_defaultNameCode="ke"

**Comment by peter6053** [comment]
works, Thanks man
