### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by PtiPingouin** [hbb20/CountryCodePickerProject#6]
Can we have language support?

**Comment by hbb20** [comment]
Definity it can be added with some work. Rather than all language support at a single shot, I will work one by one as time permits. Can you please specify the language you need support for? So that I can provide support for that language first.

**Comment by Konraddd** [comment]
German would be highly appriciated!

**Comment by hbb20** [comment]
Newer version v1.5 of the library has language support.
Check [Documentation](https://github.com/hbb20/CountryCodePickerProject/blob/master/README.md#12-language-support) for detail.
