### ISSUE TITLE
List of countries url not working

### ISSUE THREAD

**Issue by pamgoudarzi** [hbb20/CountryCodePickerProject#64]
There's a 404 error on https://raw.githubusercontent.com/hbb20/CountryCodePickerProject/master/ccp/src/main/res/raw/countries.

**Comment by hbb20** [comment]
Recently internal working of library has been changed to make it light weight. You can refer [language specific list](https://github.com/hbb20/CountryCodePickerProject/tree/master/ccp/src/main/res/raw) for details.
