### ISSUE TITLE
Mexico name in translation

### ISSUE THREAD

**Issue by ArmandoGomez** [hbb20/CountryCodePickerProject#65]
Please change Méjico to México on spanish translation this is the right international grammar. For other languages just remove the ´ it shall be written "Mexico"

**Comment by hbb20** [comment]
Sure.. 👍

**Comment by ArmandoGomez** [comment]
Hi Harsh Bhakta, please let me know when you make this little change. Thank you!

**Comment by hbb20** [comment]
I already have changed this in my branch. But the version is not yet
released. Will do it in one day.

**Comment by hbb20** [comment]
New version has been uploaded with the fix. Try version 1.8.1.
