### ISSUE TITLE
How can I set the flag for +1 code (countries like US ) ? Library shows wrong flag .

### ISSUE THREAD

**Issue by were-wolf** [hbb20/CountryCodePickerProject#68]

**Comment by hbb20** [comment]
Setting country using phone code is not recommended way because more than
one countries can share the same phone code.


2 ways to solve this:
1. Set country using country name code. (Recommended)
2. Set country preferences (details can be found in readme document)

**Comment by were-wolf** [comment]
Thanks ,setting country using phone code and number would be a good idea..

**Comment by hbb20** [comment]
Correct country can be set using phone code if only one country has that code. But when multiple countries share the same phone code, correct country can not be detected only based on phone code.

**Comment by hbb20** [comment]
Hi, requested feature has been implemented in v2.0.0. 

Correct country for numbers starting with +1 are now detected based on area code in the full number.
If you find any problem with area code, please open new issue.

Please read [update guide](https://github.com/hbb20/CountryCodePickerProject/wiki/Update-Guide-for-v2.0.0) before upgrading to v2.0.0.

**Comment by were-wolf** [comment]
Thanks bro
