### ISSUE TITLE
Short country list

### ISSUE THREAD

**Issue by Gustik** [hbb20/CountryCodePickerProject#7]
Is it possible to show only specific countries?

**Comment by hbb20** [comment]
Right now, it's not possible. But there is a feature for country
preference. Setting some countries in your preference will show them first
on the list. You can check demo app to see how they will look when country
selection dialog is opened.

Looking at your requirement I will add a new feature
"customMasterCountries" as soon as possible. But for now if you need that
feature urgently, you can clone the project and remove unwanted countries
from the getMasterCountries() method of Country.java file.

**Comment by hbb20** [comment]
@Gustik , newer version v1.5 has introduced a feature "customMasterCountryList" which does exactly what you asked for. Read [documentation](https://github.com/hbb20/CountryCodePickerProject/blob/master/README.md#10-custom-master-country-list) for more details.
