### ISSUE TITLE
finishComposingText on inactive InputConnection

### ISSUE THREAD

**Issue by ArmandoGomez** [hbb20/CountryCodePickerProject#71]
I found a minor bug, when you are on the dialog box it get automatic focus on editext and shows you the keyboard, so if you clic on the square navigation button and then click the circle icon to close it you keep the keyboard showing. On Android Monitor it shows finishComposingText on inactive InputConnection

**Comment by hbb20** [comment]
@ArmandoGomez, Thank you for reporting.

This issue has been fixed in v2.0.0. 

Please read [update guide](https://github.com/hbb20/CountryCodePickerProject/wiki/Update-Guide-for-v2.0.0) before upgrading to v2.0.0.
