### ISSUE TITLE
Name "updated" for Log after updating country

### ISSUE THREAD

**Issue by ArmandoGomez** [hbb20/CountryCodePickerProject#72]
Hi again, this is a little suggestion for multi language... the name of log of UPDATED + Country should be translatable for example 
English - Updated
Spanish - Actualizado
Portugues - Atualizada
French -  Actualisé
Italia - Aggiornato

**Comment by hbb20** [comment]
Hellow.
Thank you for taking genuine interest in library. 
Debug Log is just for developers' use and translating it will not add any value to end user.
