### ISSUE TITLE
code in arabic

### ISSUE THREAD

**Issue by AnilYd14** [hbb20/CountryCodePickerProject#73]
If I picked the language as Arabic then can we also get country code in arabic language

**Comment by hbb20** [comment]
Right now there is no such provision in library. Those name codes are standard globally recognised [ISO codes](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements).

**Comment by AnilYd14** [comment]
I am asking for the numeric country codes...as when I change language to arabic still getting numberic in english
