### ISSUE TITLE
Search EditText disappear in RTL layout

### ISSUE THREAD

**Issue by mina-william** [hbb20/CountryCodePickerProject#75]
Hi
Thank you for this library. In the RTL layouts if we start typing in the search EditText it will disappear.

and to fix it, In the [layout_picker_dialog.xml](https://github.com/hbb20/CountryCodePickerProject/blob/master/ccp/src/main/res/layout/layout_picker_dialog.xml) we just need to add layout_toStartOf to the EditText:
```xml
<EditText
            android:id="@+id/editText_search"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_toLeftOf="@+id/img_clear_query"
            android:layout_toStartOf="@+id/img_clear_query"
            android:hint="@string/search_hint"
            android:imeOptions="actionSearch"
            android:singleLine="true"
            android:textColor="@android:color/primary_text_light_nodisable"/>
```
Thanks.

**Comment by hbb20** [comment]
@mina-william , thank you for reporting, 
Suggested solution has been implemented in v2.0.2.
