### ISSUE TITLE
Spanish fix name of 2 countries

### ISSUE THREAD

**Issue by ArmandoGomez** [hbb20/CountryCodePickerProject#77]
Hi i found that next two countries are wrong spelling.
This are the correct spelling for spanish:

+225 - Spanish > Costa de Marfil (CI)

+850 - Spanish > República Popular Democrática de Corea (KP)

**Comment by hbb20** [comment]
Nice to see such suggestions for name correction. 
If you can go through entire list and correct all names in on shot then it will be really helpful.

**Comment by ArmandoGomez** [comment]
Here you can have the complete spanish file fixed:
https://we.tl/LF4nsk0FaP

**Comment by hbb20** [comment]
@ArmandoGomez thank you for the list. I have updated it in version 2.0.2.
