### ISSUE TITLE
No default code is needed

### ISSUE THREAD

**Issue by rajkumaranbu94** [hbb20/CountryCodePickerProject#78]
I don't want to set default country code,instead of ,that have to show empty layout or 'Select Country Code' ,item to be added in position 0 of country code list.I think,as per the current status of the code,this is the kind of force users to use default country code option.please do the needful asap.Thank you in advance..!!!

**Comment by hbb20** [comment]
Hey @rajkumaranbu94, default country code is something required to fulfil library's basic purpose. Even if it is forced, it is necessary.

If you want to add some country with name "Select Country Code" locally. Do following 

1. Copy countries XML file in your project.
2. Add country with name "Select Country Code", and name code "zz", phone code "00"
3. Then add "zz" to your preferredCountries,
4. Set defaultNameCode="zz", and autoDetectCountry="false"

**Comment by xdbas** [comment]
Where to find countries xml?

**Comment by Vengat121** [comment]
I am having same problem.. where to find countries xml?
