### ISSUE TITLE
If getting SIM Info failed, calling getSelectedCountryXXX() will throw NullPointerException.

### ISSUE THREAD

**Issue by mina-william** [hbb20/CountryCodePickerProject#80]
Hi,

If the Auto Detect Country is enabled and  [selectCountryFromSimInfo](https://github.com/hbb20/CountryCodePickerProject/blob/master/ccp/src/main/java/com/hbb20/CountryCodePicker.java) method fail (ex: no sim), it will set the selectedCountry = null and any call to getSelectedCountryXXX() will throw NullPointerException (while the widget will show the default country correctly). And to fix it, we can just check for null like this:
```java
public void selectCountryFromSimInfo() {
        try {
            TelephonyManager telephonyManager = (TelephonyManager) context.getSystemService(Context.TELEPHONY_SERVICE);
            String currentCountryISO = telephonyManager.getSimCountryIso();
            if(!TextUtils.isEmpty(currentCountryISO) {
                setSelectedCountry(Country.getCountryForNameCodeFromLibraryMasterList(getContext(), getLanguageToApply(), currentCountryISO));
            }
        } catch (Exception e) {
            Log.w(TAG, "applyCustomProperty: could not set country from sim");
        }
    }
```
and checking for null in the getSelectedCountryXXX() methods too.

Thanks

**Comment by hbb20** [comment]
Hey, @mina-william Thank you for reporting and suggestion. I have covered this in version 2.0.3. Please check it and reopen if something is still wrong.
