### ISSUE TITLE
Turkish language support

### ISSUE THREAD

**Issue by ugurcany** [hbb20/CountryCodePickerProject#82]
Thanks for this great country picker library. Could you please also add Turkish language support?

**Comment by hbb20** [comment]
Sure! But for that, I will need your help.
Can you please verify google translated names? 
Please post the list of countries with corrected names in the comment. 

        <country name="Andorra"   english_name="Andorra"  name_code="ad"   phone_code="376"/>
        <country name="Birleşik Arap Emirlikleri"   english_name="United Arab Emirates"  name_code="ae"   phone_code="971"/>
        <country name="Afganistan"   english_name="Afghanistan"  name_code="af"   phone_code="93"/>
        <country name="Antigua ve Barbuda"   english_name="Antigua and Barbuda"  name_code="ag"   phone_code="1"/>
        <country name="Anguilla"   english_name="Anguilla"  name_code="ai"   phone_code="1"/>
        <country name="Arnavutluk"   english_name="Albania"  name_code="al"   phone_code="355"/>
        <country name="Ermenistan"   english_name="Armenia"  name_code="am"   phone_code="374"/>
        <country name="Angora"   english_name="Angola"  name_code="ao"   phone_code="244"/>
        <country name="Antarktika"   english_name="Antarctica"  name_code="aq"   phone_code="672"/>
        <country name="Arjantin"   english_name="Argentina"  name_code="ar"   phone_code="54"/>
        <country name="Avusturya"   english_name="Austria"  name_code="at"   phone_code="43"/>
        <country name="Avustralya"   english_name="Australia"  name_code="au"   phone_code="61"/>
        <country name="Aruba"   english_name="Aruba"  name_code="aw"   phone_code="297"/>
        <country name="Azerbeycan"   english_name="Azerbaijan"  name_code="az"   phone_code="994"/>
        <country name="Bosna Hersek"   english_name="Bosnia And Herzegovina"  name_code="ba"   phone_code="387"/>
        <country name="Barbados"   english_name="Barbados"  name_code="bb"   phone_code="1"/>
        <country name="Bangladeş"   english_name="Bangladesh"  name_code="bd"   phone_code="880"/>
        <country name="Belçika"   english_name="Belgium"  name_code="be"   phone_code="32"/>
        <country name="Burkina Faso"   english_name="Burkina Faso"  name_code="bf"   phone_code="226"/>
        <country name="Bulgaristan"   english_name="Bulgaria"  name_code="bg"   phone_code="359"/>
        <country name="Bahreyn"   english_name="Bahrain"  name_code="bh"   phone_code="973"/>
        <country name="Burundi"   english_name="Burundi"  name_code="bi"   phone_code="257"/>
        <country name="Benin"   english_name="Benin"  name_code="bj"   phone_code="229"/>
        <country name="Saint Barthélemy"   english_name="Saint Barthélemy"  name_code="bl"   phone_code="590"/>
        <country name="Bermuda"   english_name="Bermuda"  name_code="bm"   phone_code="1"/>
        <country name="Brunei Darussalam"   english_name="Brunei Darussalam"  name_code="bn"   phone_code="673"/>
        <country name="Bolivya, Çok Uluslu Devlet"   english_name="Bolivia, Plurinational State Of"  name_code="bo"   phone_code="591"/>
        <country name="Brezilya"   english_name="Brazil"  name_code="br"   phone_code="55"/>
        <country name="Bahamalar"   english_name="Bahamas"  name_code="bs"   phone_code="1"/>
        <country name="Butan"   english_name="Bhutan"  name_code="bt"   phone_code="975"/>
        <country name="Botsvana"   english_name="Botswana"  name_code="bw"   phone_code="267"/>
        <country name="Belarus"   english_name="Belarus"  name_code="by"   phone_code="375"/>
        <country name="Belize"   english_name="Belize"  name_code="bz"   phone_code="501"/>
        <country name="Kanada"   english_name="Canada"  name_code="ca"   phone_code="1"/>
        <country name="Cocos (keeling) Adaları"   english_name="Cocos (keeling) Islands"  name_code="cc"   phone_code="61"/>
        <country name="Kongo Demokratik Cumhuriyeti"   english_name="Congo, The Democratic Republic Of The"  name_code="cd"   phone_code="243"/>
        <country name="Orta Afrika Cumhuriyeti"   english_name="Central African Republic"  name_code="cf"   phone_code="236"/>
        <country name="Kongo"   english_name="Congo"  name_code="cg"   phone_code="242"/>
        <country name="İsviçre"   english_name="Switzerland"  name_code="ch"   phone_code="41"/>
        <country name="Cote d'Iveire"   english_name="Côte D'ivoire"  name_code="ci"   phone_code="225"/>
        <country name="Cook Adaları"   english_name="Cook Islands"  name_code="ck"   phone_code="682"/>
        <country name="Şili"   english_name="Chile"  name_code="cl"   phone_code="56"/>
        <country name="Kamerun"   english_name="Cameroon"  name_code="cm"   phone_code="237"/>
        <country name="Çin"   english_name="China"  name_code="cn"   phone_code="86"/>
        <country name="Kolombiya"   english_name="Colombia"  name_code="co"   phone_code="57"/>
        <country name="Kosta Rika"   english_name="Costa Rica"  name_code="cr"   phone_code="506"/>
        <country name="Küba"   english_name="Cuba"  name_code="cu"   phone_code="53"/>
        <country name="Cape Verde"   english_name="Cape Verde"  name_code="cv"   phone_code="238"/>
        <country name="Noel Adası"   english_name="Christmas Island"  name_code="cx"   phone_code="61"/>
        <country name="Kıbrıs"   english_name="Cyprus"  name_code="cy"   phone_code="357"/>
        <country name="Çek Cumhuriyeti"   english_name="Czech Republic"  name_code="cz"   phone_code="420"/>
        <country name="Almanya"   english_name="Germany"  name_code="de"   phone_code="49"/>
        <country name="Cibuti"   english_name="Djibouti"  name_code="dj"   phone_code="253"/>
        <country name="Danimarka"   english_name="Denmark"  name_code="dk"   phone_code="45"/>
        <country name="Dominika"   english_name="Dominica"  name_code="dm"   phone_code="1"/>
        <country name="Dominik Cumhuriyeti"   english_name="Dominican Republic"  name_code="do"   phone_code="1"/>
        <country name="Cezayir"   english_name="Algeria"  name_code="dz"   phone_code="213"/>
        <country name="Ekvador"   english_name="Ecuador"  name_code="ec"   phone_code="593"/>
        <country name="Estonya"   english_name="Estonia"  name_code="ee"   phone_code="372"/>
        <country name="Mısır"   english_name="Egypt"  name_code="eg"   phone_code="20"/>
        <country name="Eritre"   english_name="Eritrea"  name_code="er"   phone_code="291"/>
        <country name="ispanya"   english_name="Spain"  name_code="es"   phone_code="34"/>
        <country name="Etiyopya"   english_name="Ethiopia"  name_code="et"   phone_code="251"/>
        <country name="Finlandiya"   english_name="Finland"  name_code="fi"   phone_code="358"/>
        <country name="Fiji"   english_name="Fiji"  name_code="fj"   phone_code="679"/>
        <country name="Falkland Adaları (malvinas)"   english_name="Falkland Islands (malvinas)"  name_code="fk"   phone_code="500"/>
        <country name="Mikronezya, Federe Devletleri"   english_name="Micronesia, Federated States Of"  name_code="fm"   phone_code="691"/>
        <country name="Faroe Adaları"   english_name="Faroe Islands"  name_code="fo"   phone_code="298"/>
        <country name="Fransa"   english_name="France"  name_code="fr"   phone_code="33"/>
        <country name="Gabon"   english_name="Gabon"  name_code="ga"   phone_code="241"/>
        <country name="Birleşik Krallık"   english_name="United Kingdom"  name_code="gb"   phone_code="44"/>
        <country name="Grenada"   english_name="Grenada"  name_code="gd"   phone_code="1"/>
        <country name="Gürcistan"   english_name="Georgia"  name_code="ge"   phone_code="995"/>
        <country name="Fransız Guyana"   english_name="French Guyana"  name_code="gf"   phone_code="594"/>
        <country name="Gana"   english_name="Ghana"  name_code="gh"   phone_code="233"/>
        <country name="Cebelitarık"   english_name="Gibraltar"  name_code="gi"   phone_code="350"/>
        <country name="Grönland"   english_name="Greenland"  name_code="gl"   phone_code="299"/>
        <country name="Gambiya"   english_name="Gambia"  name_code="gm"   phone_code="220"/>
        <country name="Gine"   english_name="Guinea"  name_code="gn"   phone_code="224"/>
        <country name="Ekvator Ginesi"   english_name="Equatorial Guinea"  name_code="gq"   phone_code="240"/>
        <country name="Yunanistan"   english_name="Greece"  name_code="gr"   phone_code="30"/>
        <country name="Guatemala"   english_name="Guatemala"  name_code="gt"   phone_code="502"/>
        <country name="Gine Bissau"   english_name="Guinea-bissau"  name_code="gw"   phone_code="245"/>
        <country name="Guyana"   english_name="Guyana"  name_code="gy"   phone_code="592"/>
        <country name="Hong Kong"   english_name="Hong Kong"  name_code="hk"   phone_code="852"/>
        <country name="Honduras"   english_name="Honduras"  name_code="hn"   phone_code="504"/>
        <country name="Hırvatistan"   english_name="Croatia"  name_code="hr"   phone_code="385"/>
        <country name="Haiti"   english_name="Haiti"  name_code="ht"   phone_code="509"/>
        <country name="Macaristan"   english_name="Hungary"  name_code="hu"   phone_code="36"/>
        <country name="Endonezya"   english_name="Indonesia"  name_code="id"   phone_code="62"/>
        <country name="İrlanda"   english_name="Ireland"  name_code="ie"   phone_code="353"/>
        <country name="İsrail"   english_name="Israel"  name_code="il"   phone_code="972"/>
        <country name="Isle Of Man"   english_name="Isle Of Man"  name_code="im"   phone_code="44"/>
        <country name="Hindistan"   english_name="India"  name_code="in"   phone_code="91"/>
        <country name="Irak"   english_name="Iraq"  name_code="iq"   phone_code="964"/>
        <country name="İran, İslam Cumhuriyeti"   english_name="Iran, Islamic Republic Of"  name_code="ir"   phone_code="98"/>
        <country name="İtalya"   english_name="Italy"  name_code="it"   phone_code="39"/>
        <country name="Jamaika"   english_name="Jamaica"  name_code="jm"   phone_code="1"/>
        <country name="Ürdün"   english_name="Jordan"  name_code="jo"   phone_code="962"/>
        <country name="Japonya"   english_name="Japan"  name_code="jp"   phone_code="81"/>
        <country name="Kenya"   english_name="Kenya"  name_code="ke"   phone_code="254"/>
        <country name="Kırgızistan"   english_name="Kyrgyzstan"  name_code="kg"   phone_code="996"/>
        <country name="Kamboçya"   english_name="Cambodia"  name_code="kh"   phone_code="855"/>
        <country name="Kiribati"   english_name="Kiribati"  name_code="ki"   phone_code="686"/>
        <country name="Komorlar"   english_name="Comoros"  name_code="km"   phone_code="269"/>
        <country name="Saint Kitts ve Nevis"   english_name="Saint Kitts and Nevis"  name_code="kn"   phone_code="1"/>
        <country name="Kuzey Kore"   english_name="North Korea"  name_code="kp"   phone_code="850"/>
        <country name="Güney Kore"   english_name="South Korea"  name_code="kr"   phone_code="82"/>
        <country name="Kuveyt"   english_name="Kuwait"  name_code="kw"   phone_code="965"/>
        <country name="Cayman Adaları"   english_name="Cayman Islands"  name_code="ky"   phone_code="1"/>
        <country name="Kazakistan"   english_name="Kazakhstan"  name_code="kz"   phone_code="7"/>
        <country name="Lao Halkı'nın Demokratik Cumhuriyeti"   english_name="Lao People's Democratic Republic"  name_code="la"   phone_code="856"/>
        <country name="Lübnan"   english_name="Lebanon"  name_code="lb"   phone_code="961"/>
        <country name="Saint Lucia"   english_name="Saint Lucia"  name_code="lc"   phone_code="1"/>
        <country name="Lihtenştayn"   english_name="Liechtenstein"  name_code="li"   phone_code="423"/>
        <country name="Sri Lanka"   english_name="Sri Lanka"  name_code="lk"   phone_code="94"/>
        <country name="Liberya"   english_name="Liberia"  name_code="lr"   phone_code="231"/>
        <country name="Lesotho"   english_name="Lesotho"  name_code="ls"   phone_code="266"/>
        <country name="Litvanya"   english_name="Lithuania"  name_code="lt"   phone_code="370"/>
        <country name="Lüksemburg"   english_name="Luxembourg"  name_code="lu"   phone_code="352"/>
        <country name="Letonya"   english_name="Latvia"  name_code="lv"   phone_code="371"/>
        <country name="Libya"   english_name="Libya"  name_code="ly"   phone_code="218"/>
        <country name="Fas"   english_name="Morocco"  name_code="ma"   phone_code="212"/>
        <country name="Monako"   english_name="Monaco"  name_code="mc"   phone_code="377"/>
        <country name="Moldova, Republic Of"   english_name="Moldova, Republic Of"  name_code="md"   phone_code="373"/>
        <country name="Karadağ"   english_name="Montenegro"  name_code="me"   phone_code="382"/>
        <country name="Madagaskar"   english_name="Madagascar"  name_code="mg"   phone_code="261"/>
        <country name="Marşal Adaları"   english_name="Marshall Islands"  name_code="mh"   phone_code="692"/>
        <country name="Makedonya, Eski Yugoslav Cumhuriyeti"   english_name="Macedonia, The Former Yugoslav Republic Of"  name_code="mk"   phone_code="389"/>
        <country name="Mali"   english_name="Mali"  name_code="ml"   phone_code="223"/>
        <country name="Myanmar"   english_name="Myanmar"  name_code="mm"   phone_code="95"/>
        <country name="Moğolistan"   english_name="Mongolia"  name_code="mn"   phone_code="976"/>
        <country name="Macao"   english_name="Macao"  name_code="mo"   phone_code="853"/>
        <country name="Martinik"   english_name="Martinique"  name_code="mq"   phone_code="596"/>
        <country name="Moritanya"   english_name="Mauritania"  name_code="mr"   phone_code="222"/>
        <country name="Montserrat"   english_name="Montserrat"  name_code="ms"   phone_code="1"/>
        <country name="Malta"   english_name="Malta"  name_code="mt"   phone_code="356"/>
        <country name="Mauritius"   english_name="Mauritius"  name_code="mu"   phone_code="230"/>
        <country name="Maldivler"   english_name="Maldives"  name_code="mv"   phone_code="960"/>
        <country name="Malawi"   english_name="Malawi"  name_code="mw"   phone_code="265"/>
        <country name="Meksika"   english_name="Mexico"  name_code="mx"   phone_code="52"/>
        <country name="Malezya"   english_name="Malaysia"  name_code="my"   phone_code="60"/>
        <country name="Mozambik"   english_name="Mozambique"  name_code="mz"   phone_code="258"/>
        <country name="Namibya"   english_name="Namibia"  name_code="na"   phone_code="264"/>
        <country name="Yeni Kaledonya"   english_name="New Caledonia"  name_code="nc"   phone_code="687"/>
        <country name="Nijer"   english_name="Niger"  name_code="ne"   phone_code="227"/>
        <country name="Nijerya"   english_name="Nigeria"  name_code="ng"   phone_code="234"/>
        <country name="Nikaragua"   english_name="Nicaragua"  name_code="ni"   phone_code="505"/>
        <country name="Hollanda"   english_name="Netherlands"  name_code="nl"   phone_code="31"/>
        <country name="Norveç"   english_name="Norway"  name_code="no"   phone_code="47"/>
        <country name="Nepal"   english_name="Nepal"  name_code="np"   phone_code="977"/>
        <country name="Nauru"   english_name="Nauru"  name_code="nr"   phone_code="674"/>
        <country name="Niue"   english_name="Niue"  name_code="nu"   phone_code="683"/>
        <country name="Yeni Zelanda"   english_name="New Zealand"  name_code="nz"   phone_code="64"/>
        <country name="Umman"   english_name="Oman"  name_code="om"   phone_code="968"/>
        <country name="Panama"   english_name="Panama"  name_code="pa"   phone_code="507"/>
        <country name="Peru"   english_name="Peru"  name_code="pe"   phone_code="51"/>
        <country name="Fransız Polinezyası"   english_name="French Polynesia"  name_code="pf"   phone_code="689"/>
        <country name="Papua Yeni Gine"   english_name="Papua New Guinea"  name_code="pg"   phone_code="675"/>
        <country name="Filipinler"   english_name="Philippines"  name_code="ph"   phone_code="63"/>
        <country name="Pakistan"   english_name="Pakistan"  name_code="pk"   phone_code="92"/>
        <country name="Polonya"   english_name="Poland"  name_code="pl"   phone_code="48"/>
        <country name="Saint Pierre ve Miquelon"   english_name="Saint Pierre And Miquelon"  name_code="pm"   phone_code="508"/>
        <country name="Pitcairn"   english_name="Pitcairn"  name_code="pn"   phone_code="870"/>
        <country name="Porto Riko"   english_name="Puerto Rico"  name_code="pr"   phone_code="1"/>
        <country name="Filistin"   english_name="Palestine"  name_code="ps"   phone_code="970"/>
        <country name="Portekiz"   english_name="Portugal"  name_code="pt"   phone_code="351"/>
        <country name="Palau"   english_name="Palau"  name_code="pw"   phone_code="680"/>
        <country name="Paraguay"   english_name="Paraguay"  name_code="py"   phone_code="595"/>
        <country name="Katar"   english_name="Qatar"  name_code="qa"   phone_code="974"/>
        <country name="Réunion"   english_name="Réunion"  name_code="re"   phone_code="262"/>
        <country name="Romanya"   english_name="Romania"  name_code="ro"   phone_code="40"/>
        <country name="Sırbistan"   english_name="Serbia"  name_code="rs"   phone_code="381"/>
        <country name="Rusya Federasyonu"   english_name="Russian Federation"  name_code="ru"   phone_code="7"/>
        <country name="Ruanda"   english_name="Rwanda"  name_code="rw"   phone_code="250"/>
        <country name="Suudi Arabistan"   english_name="Saudi Arabia"  name_code="sa"   phone_code="966"/>
        <country name="Solomon Adaları"   english_name="Solomon Islands"  name_code="sb"   phone_code="677"/>
        <country name="Seyşeller"   english_name="Seychelles"  name_code="sc"   phone_code="248"/>
        <country name="Sudan"   english_name="Sudan"  name_code="sd"   phone_code="249"/>
        <country name="İsveç"   english_name="Sweden"  name_code="se"   phone_code="46"/>
        <country name="Singapur"   english_name="Singapore"  name_code="sg"   phone_code="65"/>
        <country name="Saint Helena, Yükseliş Ve Tristan Da Cunha"   english_name="Saint Helena, Ascension And Tristan Da Cunha"  name_code="sh"   phone_code="290"/>
        <country name="Slovenya"   english_name="Slovenia"  name_code="si"   phone_code="386"/>
        <country name="Slovakya"   english_name="Slovakia"  name_code="sk"   phone_code="421"/>
        <country name="Sierra Leone"   english_name="Sierra Leone"  name_code="sl"   phone_code="232"/>
        <country name="San Marino"   english_name="San Marino"  name_code="sm"   phone_code="378"/>
        <country name="Senegal"   english_name="Senegal"  name_code="sn"   phone_code="221"/>
        <country name="Somali"   english_name="Somalia"  name_code="so"   phone_code="252"/>
        <country name="Surinam"   english_name="Suriname"  name_code="sr"   phone_code="597"/>
        <country name="Sao Tome ve Principe"   english_name="Sao Tome And Principe"  name_code="st"   phone_code="239"/>
        <country name="El Salvador"   english_name="El Salvador"  name_code="sv"   phone_code="503"/>
        <country name="Sint Maarten"   english_name="Sint Maarten"  name_code="sx"   phone_code="1"/>
        <country name="Suriye Arap Cumhuriyeti"   english_name="Syrian Arab Republic"  name_code="sy"   phone_code="963"/>
        <country name="Svaziland"   english_name="Swaziland"  name_code="sz"   phone_code="268"/>
        <country name="Turks ve Caicos Adaları"   english_name="Turks and Caicos Islands"  name_code="tc"   phone_code="1"/>
        <country name="Çad"   english_name="Chad"  name_code="td"   phone_code="235"/>
        <country name="Gitmek"   english_name="Togo"  name_code="tg"   phone_code="228"/>
        <country name="Tayland"   english_name="Thailand"  name_code="th"   phone_code="66"/>
        <country name="Tacikistan"   english_name="Tajikistan"  name_code="tj"   phone_code="992"/>
        <country name="Tokelau"   english_name="Tokelau"  name_code="tk"   phone_code="690"/>
        <country name="Timor-leste"   english_name="Timor-leste"  name_code="tl"   phone_code="670"/>
        <country name="Türkmenistan"   english_name="Turkmenistan"  name_code="tm"   phone_code="993"/>
        <country name="Tunus"   english_name="Tunisia"  name_code="tn"   phone_code="216"/>
        <country name="Tonga"   english_name="Tonga"  name_code="to"   phone_code="676"/>
        <country name="Türkiye"   english_name="Turkey"  name_code="tr"   phone_code="90"/>
        <country name="Trinidad & amp; Tobago"   english_name="Trinidad &amp; Tobago"  name_code="tt"   phone_code="1"/>
        <country name="Tuvalu"   english_name="Tuvalu"  name_code="tv"   phone_code="688"/>
        <country name="Tayvan, Çin Eyaleti"   english_name="Taiwan, Province Of China"  name_code="tw"   phone_code="886"/>
        <country name="Tanzanya, Birleşik Cumhuriyeti"   english_name="Tanzania, United Republic Of"  name_code="tz"   phone_code="255"/>
        <country name="Ukrayna"   english_name="Ukraine"  name_code="ua"   phone_code="380"/>
        <country name="Uganda"   english_name="Uganda"  name_code="ug"   phone_code="256"/>
        <country name="Amerika Birleşik Devletleri"   english_name="United States"  name_code="us"   phone_code="1"/>
        <country name="Uruguay"   english_name="Uruguay"  name_code="uy"   phone_code="598"/>
        <country name="Özbekistan"   english_name="Uzbekistan"  name_code="uz"   phone_code="998"/>
        <country name="Kutsal Gör (vatikan Şehir Devleti)"   english_name="Holy See (vatican City State)"  name_code="va"   phone_code="39"/>
        <country name="Saint Vincent & amp; Grenadinler"   english_name="Saint Vincent &amp; The Grenadines"  name_code="vc"   phone_code="1"/>
        <country name="Venezuela, Bolivarcı Cumhuriyeti"   english_name="Venezuela, Bolivarian Republic Of"  name_code="ve"   phone_code="58"/>
        <country name="İngiliz Virgin Adaları"   english_name="British Virgin Islands"  name_code="vg"   phone_code="1"/>
        <country name="ABD Virgin Adaları"   english_name="US Virgin Islands"  name_code="vi"   phone_code="1"/>
        <country name="Viet Nam"   english_name="Viet Nam"  name_code="vn"   phone_code="84"/>
        <country name="Vanuatu"   english_name="Vanuatu"  name_code="vu"   phone_code="678"/>
        <country name="Wallis ve Futuna"   english_name="Wallis And Futuna"  name_code="wf"   phone_code="681"/>
        <country name="Samoa"   english_name="Samoa"  name_code="ws"   phone_code="685"/>
        <country name="Yemen"   english_name="Yemen"  name_code="ye"   phone_code="967"/>
        <country name="Mayotte"   english_name="Mayotte"  name_code="yt"   phone_code="262"/>
        <country name="Güney Afrika"   english_name="South Africa"  name_code="za"   phone_code="27"/>
        <country name="Zambiya"   english_name="Zambia"  name_code="zm"   phone_code="260"/>
        <country name="Zimbabve"   english_name="Zimbabwe"  name_code="zw"   phone_code="263"/>

**Comment by ugurcany** [comment]
Here are the countries that have wrong translations together with correct translations:
Angola -> Angola
Azerbaijan -> Azerbaycan
Bolivia, Plurinational State Of -> Bolivya
Bhutan -> Bhutan
Cote D'ivoire -> Fildişi Sahilleri
Micronesia -> Mikronezya
French Guyana -> Fransız Guyanası
Isle Of Man -> Man Adası
Iran, Islamic Republic Of -> İran
Lao People's Democratic Republic -> Laos
Macedonia, The Former Yugoslav Republic Of -> Makedonya
Saint Helena, Ascension And Tristan Da Cunha -> Saint Helena, Ascension ve Tristan da Cunha
Syrian Arab Republic -> Suriye
Togo -> Togo
Taiwan, Province Of China -> Tayvan
Tanzania, United Republic Of -> Tanzanya
Holy See (vatican City State) -> Vatikan
Venezuela, Bolivarian Republic Of -> Venezuela
Viet Nam -> Vietnam

Other translations are correct. And also I wanna provide the correct translations for your `strings.xml` file:

        <ccp_dialog_title translation="Bir ülke seçin"/>
        <ccp_dialog_search_hint_message translation="Ara..."/>
        <ccp_dialog_no_result_ack_message translation="Sonuç bulunamadı"/>

**Comment by hbb20** [comment]
Thank you so much for this😊. I will release new version with updated language support as soon as possible.

**Comment by hbb20** [comment]
Hey, due to your help version 2.0.3 has the support for the Turkish language now. Kindly update the version in your project and check. 😃
