### ISSUE TITLE
java.lang.AssertionError: Unsupported Service: phone

### ISSUE THREAD

**Issue by ugurcany** [hbb20/CountryCodePickerProject#83]
Getting the following error causing rendering issue and cannot see the component in the layout preview:

**The following classes could not be instantiated: com.hbb20.CountryCodePicker**

 **Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.  If this is an unexpected error you can also try to build the project, then manually refresh the layout.**

**_Exception Details java.lang.AssertionError: Unsupported Service: phone**   at com.android.layoutlib.bridge.android.BridgeContext.getSystemService(BridgeContext.java:651)   at com.hbb20.CountryCodePicker.selectCountryFromSimInfo(CountryCodePicker.java:1429)   at com.hbb20.CountryCodePicker.applyCustomProperty(CountryCodePicker.java:254)   at com.hbb20.CountryCodePicker.init(CountryCodePicker.java:158)   at com.hbb20.CountryCodePicker.<init>(CountryCodePicker.java:112)   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:863)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:866)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:866)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:866)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:866)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:866)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:866)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)   at android.view.LayoutInflater.inflate(LayoutInflater.java:515)   at android.view.LayoutInflater.inflate(LayoutInflater.java:394)_

**Comment by hbb20** [comment]
I am sure you must have tried "Clean Project" and "Rebuild Project" in order to solve it.
I tried to reproduce the problem with version 2.0.2 of the library in the new project, but it worked well and rendered correct preview.

Can you please share following details that will help us understand the problem.
1. Version of CCP library that you are using
2. CCP view and applied properties in Layout file
3. Gradle file to check build tool version and target version.


_If you are using v2.0.0 to v2.0.2, then there is a known [issue](https://github.com/hbb20/CountryCodePickerProject/issues/80) which might be the reason for this problem. I will notify here when the new version with the fix is released._

Thanks:)

**Comment by ugurcany** [comment]
The component is not visible at all in preview. My config is as follows:

Version of CCP lib I'm using = 2.0.2
compileSdkVersion = 25
buildToolsVersion = "25.0.3"
Min & target sdk = 16 & 24

Usage:
```
      <com.hbb20.CountryCodePicker
                                android:id="@+id/country_picker"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                app:ccp_showNameCode="false"
                                app:ccp_showPhoneCode="false"
                                app:ccpDialog_allowSearch="false"
                                app:ccp_flagBorderColor="@color/colorPrimary"
                                app:ccpDialog_textColor="@color/colorText"
                                app:ccp_contentColor="@color/colorTextSecondary"
                                app:ccp_textSize="20dp"
                                app:ccp_arrowSize="20dp"/>
```

**Comment by hbb20** [comment]
This should help👍.

I will check and post back.

Thanks.

**Comment by hbb20** [comment]
Hellow @ugurcany ,
I'm trying to reproduce the rendering issue by setting your posted config but it shows expected view in preview. Looks like you want to use this as Country picker and want to show the only flag on CCP. 
Like this 👇  (This is preview in Anroid Studio with your configuration)
<img src="https://user-images.githubusercontent.com/4918760/29148410-c57e0154-7d32-11e7-902b-2ea58bceedef.png" width="300">

Can you please confirm that this problem is persistent in the standalone project too? 
Make a new sample project and put your configuration. Then simply add CCP view in it's mainActivity and check preview.

**Comment by ugurcany** [comment]
Is this preview or view on the emulator? I'm talking about the preview inside IDE.

Besides, I'm using latest Android Studio 3.0.0 beta.

**Comment by hbb20** [comment]
Yes, this is a preview only and not an emulator. 

Can you please confirm that this problem is persistent in the standalone project too?
Make a new sample project and put your configuration. Then simply add CCP view in it's mainActivity and check preview.

**Comment by hbb20** [comment]
Hey @ugurcany , did you try with a standalone project?

**Comment by ugurcany** [comment]
Yes, still same. Could you please check on Android Studio 3.0.0 version? Maybe its preview mode creates the problem.

**Comment by hbb20** [comment]
Yeah that is highly possible reason. As it is not stable version yet, it may create some problem.
