### ISSUE TITLE
setDialogKeyboardAutoPopup(false) not working

### ISSUE THREAD

**Issue by vsmiari** [hbb20/CountryCodePickerProject#84]
I am trying to hide the keyboard once you click on the Country code picker but the method doesn't seem to work. First I tried setting app:ccpDialog_keyboardAutoPopup="false" in the xml but nothing changed and then I tried doing it programmatically but again it didn't work. Am I using it the wrong way?

**Comment by hbb20** [comment]
Thank you for reporting.
This is not expected behaviour. I will check and post back.

**Comment by hbb20** [comment]
Hey, I'm testing with the library version 2.0.2 and it's working correctly on Nexus device. 
Can you please post the name of your testing device and the android version on it?
Thank you

**Comment by vsmiari** [comment]
I have tested it on a tablet Samsung Galaxy Tab A with Android 6 and on the same tablet but with Android 7. Both times I have the same issue.

**Comment by hbb20** [comment]
Finally, I could reproduce the problem on emulator and solved it.

Try with library version 2.0.3. 

Please close the issue if it works for you else give a comment here...

**Comment by annalaufey** [comment]
I ran into the same problem. It works when it's done programmatically with         countryCodePicker.setDialogKeyboardAutoPopup(false);
but not in the xml with  app:ccpDialog_keyboardAutoPopup="false"

**Comment by hbb20** [comment]
@annalaufey Thank you for your inputs.
I inspected the code and it is doing what is expected. It's turning pop-up off just by adding `app:ccpDialog_keyboardAutoPopup="false"` in XML. 

Which **version** are you using? 
and what is your **testing device**?
