### ISSUE TITLE
Crash when trying to search

### ISSUE THREAD

**Issue by mtudora** [hbb20/CountryCodePickerProject#87]
Process: com.tambu.keyboard, PID: 5381
08-21 23:38:07.832  5381  5381 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
08-21 23:38:07.832  5381  5381 E AndroidRuntime: 	at com.hbb20.Country.isEligibleForQuery(Country.java:1117)
08-21 23:38:07.832  5381  5381 E AndroidRuntime: 	at com.hbb20.CountryCodeAdapter.getFilteredCountries(CountryCodeAdapter.java:171)
08-21 23:38:07.832  5381  5381 E AndroidRuntime: 	at com.hbb20.CountryCodeAdapter.applyQuery(CountryCodeAdapter.java:144)
08-21 23:38:07.832  5381  5381 E AndroidRuntime: 	at com.hbb20.CountryCodeAdapter.access$000(CountryCodeAdapter.java:28)
08-21 23:38:07.832  5381  5381 E AndroidRuntime: 	at com.hbb20.CountryCodeAdapter$2.onTextChanged(CountryCodeAdapter.java:90)
08-21 23:38:07.832  5381  5381 E AndroidRuntime: 	at android.widget.TextView.sendOnTextChanged(TextView.java:8187)
08-21 23:38:07.832  5381  5381 E AndroidRuntime: 	at android.widget.TextView.handleTextChanged(TextView.java:8249)
08-21 23:38:07.832  5381  5381 E AndroidRuntime: 	at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:10371)
08-21 23:38:07.832  5381  5381 E AndroidRuntime: 	at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1208)
08-21 23:38:07.832  5381  5381 E AndroidRuntime: 	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:578)
08-21 23:38:07.832  5381  5381 E AndroidRuntime: 	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:509)
08-21 23:38:07.832  5381  5381 E AndroidRuntime: 	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
08-21 23:38:07.832  5381  5381 E AndroidRuntime: 	at android.text.method.QwertyKeyListener.onKeyDown(QwertyKeyListener.java:223)
08-21 23:38:07.832  5381  5381 E AndroidRuntime: 	at android.text.method.TextKeyListener.onKeyDown(TextKeyListener.java:136)
08-21 23:38:07.832  5381  5381 E AndroidRuntime: 	at android.widget.TextView.doKeyDown(TextView.java:6285)
08-21 23:38:07.832  5381  5381 E AndroidRuntime: 	at android.widget.TextView.onKeyDown(TextView.java:6075)

**Comment by hbb20** [comment]
Oh sorry for that. This should not happen.

Can you please share
- what version of library you are using?
- the XML code of layout?
- testing device name?

This will help.🙂

**Comment by mtudora** [comment]
Hello,
Thanks for replying so fast.I have an emulator Pixel, api 25 x86.Version of the library is 2.0.3.The layout looks like this:<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:orientation="vertical"
    android:layout_height="match_parent">

    <TextView
        android:id="@+id/verify_title"
        style="@style/Title"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="24dp"
        android:layout_marginRight="24dp"
        android:layout_marginStart="24dp"
        android:layout_marginTop="40dp"
        android:text="@string/verify_title_label"
        />

    <TextView
        android:id="@+id/verify_message"
        style="@style/RegularText"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginEnd="24dp"
        android:layout_marginLeft="24dp"
        android:layout_marginRight="24dp"
        android:layout_marginStart="24dp"
        android:layout_marginTop="16dp"
        android:text="@string/verify_welcome_label"
       />

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        android:gravity="center_vertical"
        android:layout_marginTop="24dp"
        android:layout_marginLeft="24dp"
        android:layout_gravity="center_vertical">

        <com.hbb20.CountryCodePicker
            android:id="@+id/ccp"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center_vertical"
            app:ccp_autoDetectCountry="true"
            app:ccpDialog_allowSearch="false"
            app:ccp_countryPreference="TR,RO,DE"
            app:ccp_defaultPhoneCode="40"  />

        <include layout="@layout/twilio_phone_number_container"
            />
    </LinearLayout>

    <Button
        android:id="@+id/verify_button"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginEnd="24dp"
        android:layout_marginLeft="24dp"
        android:layout_marginRight="24dp"
        android:layout_marginStart="24dp"
        android:layout_marginTop="24dp"
        android:layout_gravity="right"
        android:stateListAnimator="@null"
        android:text="@string/verify_button_label"
        android:theme="@style/VerifyButtonTheme"
       />


    <include
        android:id="@+id/progress_bar"
        layout="@layout/twilio_progress_bar_overlay"
        android:visibility="gone" />

</LinearLayout>
And the phone number container layout:<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.TextInputLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/phone_number_container"
    android:layout_gravity="center_vertical"
    android:gravity="center_vertical"
    app:errorEnabled="true"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginEnd="24dp"
    android:layout_marginLeft="12dp"
    android:layout_marginRight="24dp"
    android:layout_marginStart="12dp"
    tools:showIn="@layout/twilio_activity_verification_failed">

    <android.support.design.widget.TextInputEditText
        android:id="@+id/phone_number"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center_vertical"
        android:gravity="center_vertical"
        android:ems="10"
        android:hint="@string/phone_number_hint"
        android:inputType="phone" />
</android.support.design.widget.TextInputLayout>
Thanks.
On Monday, August 21, 2017, 11:56:08 PM GMT+3, Harsh Bhakta <notifications@github.com> wrote:

Oh sorry for that. This should not happen.

Can you please share
- what version of library you are using?
- the XML code of layout?
- testing device name?

This will help.🙂

**Comment by hbb20** [comment]
Are you getting problem when  app:ccpDialog_allowSearch="false" is
included? If so, can you please check if it's working without it or not?


Apart from that please use defaultNameCode instead of defaultPhoneCode. We
may decide to deprecate defaultPhoneCode in future.

**Comment by mtudora** [comment]
The search was on false because of the crash. If i use the layout like this still crashes:<com.hbb20.CountryCodePicker
    android:id="@+id/ccp"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_gravity="center_vertical"
    app:ccp_autoDetectCountry="false"
    app:ccpDialog_allowSearch="true"
    app:ccp_countryPreference="TR,RO,DE"
    app:ccp_defaultNameCode="RO"  />

On Tuesday, August 22, 2017, 12:21:38 AM GMT+3, Harsh Bhakta <notifications@github.com> wrote:

Are you getting problem when app:ccpDialog_allowSearch="false" is
included? If so, can you please check if it's working without it or not?


Apart from that please use defaultNameCode instead of defaultPhoneCode. We
may decide to deprecate defaultPhoneCode in future.

**Comment by hbb20** [comment]
Can you please check on any physical device?

**Comment by mtudora** [comment]
Yes but tomorrow at the office. I will check and let you know :).

On Tuesday, August 22, 2017, 12:28:44 AM GMT+3, Harsh Bhakta <notifications@github.com> wrote:

Can you please check on any physical device?

**Comment by hbb20** [comment]
Cool. Till then, I will check the issue on my machine to find out the
problem.

**Comment by mtudora** [comment]
Still crashes on a One Plus 3T

On Tuesday, August 22, 2017, 12:31:28 AM GMT+3, Harsh Bhakta <notifications@github.com> wrote:

Cool. Till then, I will check the issue on my machine to find out the
problem.

**Comment by hbb20** [comment]
I am testing it with provided code but it is working well in my devices.

From error log I can derive that the country that is being picked from the XML file is missing country name or name code or english name.

Do you have any XML file with any of these names in your project? If project file is overriding CCP's file then it can cause the problem.
<img width="314" alt="screen shot 2017-08-23 at 01 25 51" src="https://user-images.githubusercontent.com/4918760/29601623-0ea9c268-87a2-11e7-9a08-398cd3d41121.png">

If none of these files is overridden then can you please test in a standalone app in which only one activity has only CCP view in it?

**Comment by mtudora** [comment]
Hello,
I don't have files with the exact same name but i have smth like rows_arabic.xml because i am working on a keyboard. Unfortunately i don't have the time to test in a standalone app and I am sure it's working if you already tested and probably is smth incompatible with my app. I will just disable the search for now and i can close the bug if you want.
Thanks.

On Wednesday, August 23, 2017, 9:40:19 AM GMT+3, Harsh Bhakta <notifications@github.com> wrote:


I am testing it with provided code but it is working well in my devices.

From error log I can derive that the country that is being picked from the XML file is missing country name or name code or english name.

Do you have any XML file with any of these names in your project? If project file is overriding CCP's file then it can cause the problem.


If none of these files is overridden then can you please test in a standalone app in which only one activity has only CCP view in it?

**Comment by hbb20** [comment]
Are you using compile SDK version 26?

**Comment by kounalem** [comment]
@hbb20  Hi!  The ssue still exist's, when proguard is enabled.

**Comment by rolgalan** [comment]
HI @kounalem If you disable the search, then the app won't crash, but the null values will still continue existing, so problem will persist. If the user chooses the country with null values you will get inconsistent data in your app.

@hbb20 This problem is still existing in version 2.2.2 as reported in https://github.com/hbb20/CountryCodePickerProject/issues/231
