### ISSUE TITLE
Default country not working

### ISSUE THREAD

**Issue by mtudora** [hbb20/CountryCodePickerProject#88]
I tried setting Romania or Turkey from xml or code as default country, in the preview looks ok but in the application shows US

**Comment by hbb20** [comment]
Try by setting "autoDetectCountry" false. That should work...

Sorry for the missing documentation of it. I'm working on it.

**Comment by hbb20** [comment]
Did that work for you? 
If so, please close the issue.

Thanks

**Comment by mtudora** [comment]
Worked with "autoDetectCountry" false
