### ISSUE TITLE
Custom font support

### ISSUE THREAD

**Issue by viveksinha121** [hbb20/CountryCodePickerProject#9]
I am using different font in my project. I want ccp to be as same font.
Please add options.

**Comment by hbb20** [comment]
Are you using different system font (sans-serif-light / sans-serif-thin) or some external fonts ?

**Comment by viveksinha121** [comment]
I am using external font.

**Comment by hbb20** [comment]
@viveksinha121, try recently published v1.5 of the library. It has ccp.setTypeFace(typeFace); and p.setTypeFace(typeFace,customStyle); methods which will let you set external fonts to ccpContent. Here is the [documetation](https://github.com/hbb20/CountryCodePickerProject/blob/master/README.md#11-custom-font) for custom fonts.
