### ISSUE TITLE
NullPointerException for setSelectedCountry()

### ISSUE THREAD

**Issue by milaptank** [hbb20/CountryCodePickerProject#92]
I got this error but i am not able to solve it can you please help me 
I have opt prelaunch report in play store and play store give me this error 

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.hbb20.Country.getNameCode()' on a null object reference
       at com.hbb20.CountryCodePicker.setSelectedCountry(CountryCodePicker.java:497)
       at com.hbb20.CountryCodeAdapter$4.onClick(CountryCodeAdapter.java:192)
       at android.view.View.performClick(View.java:6219)
       at android.view.View$PerformClick.run(View.java:24482)
       at android.os.Handler.handleCallback(Handler.java:769)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6541)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by hbb20** [comment]
Hi, thank you for reporting

I think this is a known issue for some older version. Which version of
library caused this? And what is your XML and Java implementation with CCP?

**Comment by milaptank** [comment]
I have used older version but today I have updated to latest And re upload on play store but no luck same error occurred so please look into

**Comment by hbb20** [comment]
sure... will check... Are line numbers in the crash report still the same as posted or changed after version update?

**Comment by hbb20** [comment]
I think I found the issue. But I will need your help to be sure.
1. Can you please send the used XML Code snippet with CCP
2. You are using prelaunch report with automated testing, right?

**Comment by milaptank** [comment]
yes i can post but right now i dont have code 
and yes its automated testing by google and mostly crash on samsung device

**Comment by hbb20** [comment]
Great.
Until you post the code, can you confirm that you are using "preferred countries" list to show them on top of the list?

**Comment by milaptank** [comment]
yes i am selecting default country by default US and other dynamic based on IP location

**Comment by hbb20** [comment]
So are you setting those detected countries, based on IP, to preferred list using `setCountryPreference();` ?

**Comment by hbb20** [comment]
Can you post the newer crash report with new line numbers? or you already updated it in the question?

**Comment by milaptank** [comment]
yes  i have updated latest one

**Comment by milaptank** [comment]
Hello 
[Java code For CCP with line L128-L129 ](https://gist.github.com/milaptank/ad965db4e0c7249b10ff4d7149f5a91c#file-signupfragment-java-L128-L129)
[Java code CCP With number L236-L237 ](https://gist.github.com/milaptank/ad965db4e0c7249b10ff4d7149f5a91c#file-signupfragment-java-L236-L237)
[Java code CCP With line L449 ](https://gist.github.com/milaptank/ad965db4e0c7249b10ff4d7149f5a91c#file-signupfragment-java-L449)
[Java code CCP With line L300 ](https://gist.github.com/milaptank/ad965db4e0c7249b10ff4d7149f5a91c#file-signupfragment-java-L300)

[XML code for CCP with line number L89-L99 ](https://gist.github.com/milaptank/47ffa98a38d43382d54e242fffb0202f#file-fragment_sign_up-xml-L89-L99)

**Comment by milaptank** [comment]
Hey any luck bcz error is still reporting by automated test system i have added all files with line number

**Comment by hbb20** [comment]
I found the cause. That is something which can be triggered only by automated tests and not with human interaction. Still, I will fix it in an upcoming release.

**Comment by milaptank** [comment]
thanks a lot :+1:

**Comment by hbb20** [comment]
New version 2.04. should solve this issue. Even if that error is there, you should not worry about it.

**Comment by milaptank** [comment]
Hey Thanks for solution 

Hey one more help from you
can you create **hacktoberfest** label and assign to all issue
See
https://hacktoberfest.digitalocean.com/ you will get Tee
