### ISSUE TITLE
Programmatically open Dialog

### ISSUE THREAD

**Issue by xdbas** [hbb20/CountryCodePickerProject#94]
There seem to be no way to programatically open the country picker dialog.
There is no override of the performClick or callOnClick methods.

Is there another way or should I make a pull request to add this behavoir.

**Comment by argj** [comment]
i am tring to call the country picker from title menu option but not luck

**Comment by hbb20** [comment]
So you are not using the default view? You are planning to use your own, that's awesome. But auto click is not something planned for library. 

Still you can try [performClick();](https://developer.android.com/reference/android/view/View.html#performClick()). I'm not sure but worth trying. 

If this does not work for you, let us know. Will find some other way.

**Comment by xdbas** [comment]
performClick(); is not working

**Comment by hbb20** [comment]
Yeah I checked that afterwards. Within 2 Days I will publish a new version. I will add new method to open dialog programmatically.

**Comment by xdbas** [comment]
Great thanks!

**Comment by hbb20** [comment]
hey, please update to version 2.0.4 and you will be able to use `launchCountrySelectionDialog()` to launch dialog programmatically.
