### ISSUE TITLE
autoDetectCountry not work in nougat 7.0

### ISSUE THREAD

**Issue by waseemarain4u** [hbb20/CountryCodePickerProject#97]
Country Code Picker no pick ccp autoDetect Country not work in nougat 7.0 in xml

**Comment by hbb20** [comment]
Oh that should not happen. Can you please tell what is your testing device and how are you testing?

**Comment by waseemarain4u** [comment]
sorry, nougat 7.0, Country Code Picker not work properly, like autoDetect

**Comment by hbb20** [comment]
Thank you for the quick response. Can you please specify what is your testing device? Does it contain SIM card? Because I am unable to reproduce the problem as it's working as expected in my device running on nougat.

**Comment by waseemarain4u** [comment]
that have not SIM card, Samsung S6

**Comment by hbb20** [comment]
Have you connected it to the WIFI? What is your XML code and what country you get when running the app on device? Are you in the same country?

**Comment by waseemarain4u** [comment]
yes i have connected with WiFi. XML code is 
<com.hbb20.CountryCodePicker
                        android:id="@+id/ccp"
                        android:layout_width="0dp"
                        android:layout_height="match_parent"
                        android:layout_marginTop="@dimen/_8sdp"
                        android:layout_weight="0.3"
                        app:ccp_autoDetectCountry="true"
                        app:ccp_contentColor="@android:color/black"
                        app:ccp_flagBorderColor="@color/colorPrimary"
                        app:ccp_showFlag="true"
                        app:ccp_showNameCode="false"
                        app:ccp_textSize="@dimen/ed_textSize" />
i want to auto detect pakistan according to may current location, but it show INDIA

**Comment by ajitjati** [comment]
any update on this i have the same problem?
Does it require permissions?

**Comment by hbb20** [comment]
I think problem is not with the permission. Problem is that it is unable to detect the country.

CCP tries to detect the country using [getNetworkCountryIso()](https://developer.android.com/reference/android/telephony/TelephonyManager.html#getNetworkCountryIso()). If that fails, it will try using [getSimCountryIso()](https://developer.android.com/reference/android/telephony/TelephonyManager.html#getSimCountryIso()). For some edge cases, none of above method can detect the country. In such case, it will set the default country. 
Unless you have declared your own default country it will use library default specified country. So try to declare default country using default name code. @waseemarain4u , In your case it will be `app:ccp_defaultNameCode=“PK"` in XML. So whenever it will fail to detect country, it will set Pakistan in CCP.

**@waseemarain4u  and @ajitjati , can you please send me log with TAG "CCP" from debug log of application? That will help.**

In next version, I will try to solve this issue by using locale country info in addition to networkIso and simCountryIso.

**Comment by hbb20** [comment]
Hey @waseemarain4u and @ajitjati, can you please try recently published version v2.0.5 and confirm if the problem is solved? If not, please comment with ccp log.

**Comment by waseemarain4u** [comment]
ok @hbb20 thanks

**Comment by hbb20** [comment]
Did that work?

**Comment by waseemarain4u** [comment]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs
that error occurs when update lib

**Comment by ajitjati** [comment]
@hbb20 Nice Library first of all.
Couple of things from my side.
1) I had to degrade the library version to 2.0.0 because they were support library conflicts.
2)Auto-detection works with SIM card enabled but without SIM card it fails mostly to detect country automatically.
3) I will create a feature request to get Nationality of selected countries i.e for India -> Indian, for Afganistan -> Afgan etc.
4) There is an issue, if you are using two picker in one xml layout then auto-detection works only for the first one.

Cheers, Great work

**Comment by hbb20** [comment]
@waseemarain4u, I think it will work if you do Build -> Clean Project , Build -> Rebuid Project. Because theoretically, if it was working for v2.0.4, it should work for 2.0.5 as there is no such change that can cause the break.

**Comment by hbb20** [comment]
@ajitjati ,
1. Can you please tell what is the conflict. I believe that if we are able to resolve that conflict then you will be able to detect country correctly with version 2.0.5.
2. This is a good suggestion. We will keep in mind. But as it is not something crucial for primary purpose of library, we can not assure the implementation.
3. I checked in a demo app for both v2.0.5 and v2.0.0. And it detected country for the both.
It is highly possible that I missed something so that I could not reproduce it. Can you please look at what I did and tell me what should I do to reproduce it.


<img src="https://user-images.githubusercontent.com/4918760/31290909-db1ed7fc-aa93-11e7-92cc-ef961ee1eeac.png" height="400" />


and when I run it, 
<img src="https://user-images.githubusercontent.com/4918760/31290997-29b8bcde-aa94-11e7-828c-b3f1c1948638.png" width="400" />

If there is a bug regarding this, it must be solved as soon as possible.

**Comment by ajitjati** [comment]
I see. Strange !

Mine is 

<com.hbb20.CountryCodePicker
                    android:id="@+id/country_picker"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="bottom|right"
                    android:layout_marginBottom="@dimen/margin_3"
                    app:ccpDialog_fastScroller_bubbleColor="@color/colorGrey"
                    app:ccp_autoDetectLanguage="true"
                    app:ccp_autoDetectCountry="true"
                    app:ccp_defaultNameCode="US"
                    app:ccp_showFullName="true"
                    app:ccp_showNameCode="false"
                    app:ccp_showPhoneCode="false" />

<com.hbb20.CountryCodePicker
                    android:id="@+id/nationality_picker"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="bottom|right"
                    android:layout_marginBottom="@dimen/margin_3"
                    app:ccpDialog_fastScroller_bubbleColor="@color/colorGrey"
                    app:ccp_autoDetectLanguage="true"
                    app:ccp_autoDetectCountry="true"
                    app:ccp_defaultNameCode="US"
                    app:ccp_showFullName="true"
                    app:ccp_showNameCode="false"
                    app:ccp_showPhoneCode="false" />

**Comment by LOG-TAG** [comment]
@hbb20 
`ccp.setOnCountryChangeListener(new CountryCodePicker.OnCountryChangeListener() {
            @Override
            public void onCountrySelected() {
                Toast.makeText(PhoneNumberOtpActivity.this, "This is from OnCountryChangeListener. \n Country updated to " + ccp.getSelectedCountryName() + "(" + ccp.getSelectedCountryCodeWithPlus() + ")", Toast.LENGTH_SHORT).show();
            }
        });`

setOnCountryChangeListener will be called when it's autodetection executed/or failed?

onCountrySelected(Error e)  will awesome we are getting error use custom other logic to detect country!
