### ISSUE TITLE
Country missing

### ISSUE THREAD

**Issue by annalaufey** [hbb20/CountryCodePickerProject#98]
Could you add Icelands code please?

**Comment by hbb20** [comment]
Just to make sure. You are referring to this country, right? 
http://flagpedia.net/iceland

**Comment by annalaufey** [comment]
Yes, the code should be +354. 
Thank you!

**Comment by hbb20** [comment]
Thank you for reporting.
"Iceland" has been added to v2.0.5. If you update to this version, you should get "Iceland" on the list.

**Comment by annalaufey** [comment]
Thank you so much!
